/**
 * Type mapping — TS types → Lean types.
 *
 * Single source of truth for type-related decisions.
 * The transform phase imports this.
 */

// ── Type info extracted from TS ──────────────────────────────

export interface VariantInfo {
  name: string;
  fields: { name: string; tsType: string }[];
}

export interface UnionTypeInfo {
  name: string;
  discriminant: string;
  variants: VariantInfo[];
}

export interface TypeDeclInfo {
  name: string;
  kind: "string-union" | "discriminated-union" | "record";
  /** For string unions: the literal values */
  values?: string[];
  /** For discriminated unions: the discriminant field and variants */
  discriminant?: string;
  variants?: VariantInfo[];
  /** For records: the fields */
  fields?: { name: string; tsType: string }[];
}

// ── Primitive mapping ────────────────────────────────────────

export function tsTypeToLean(tsType: string): string {
  const t = tsType.trim();
  if (t === "number") return "Int";
  if (t === "boolean") return "Bool";
  if (t === "string") return "String";
  if (t === "void" || t === "undefined") return "Unit";
  // Array types
  if (t === "number[]") return "Array Int";
  if (t === "boolean[]") return "Array Bool";
  if (t === "string[]") return "Array String";
  const arrMatch = t.match(/^(?:Array<(.+)>|(.+)\[\])$/);
  if (arrMatch) return `Array ${tsTypeToLean(arrMatch[1] || arrMatch[2])}`;
  // User-defined: pass through (same name in Lean)
  return t;
}

// ── Derived queries ──────────────────────────────────────────

export function isNatType(leanType: string): boolean {
  return leanType === "Nat";
}

export function isArrayType(leanType: string): boolean {
  return leanType.startsWith("Array ");
}

// ── .types.lean generation ───────────────────────────────────

export function generateTypesLean(decls: TypeDeclInfo[]): string | null {
  if (decls.length === 0) return null;

  const lines: string[] = [];
  lines.push("/-");
  lines.push("  Generated by lsc — Lean types from TS type declarations.");
  lines.push("-/");
  lines.push("import Velvet.Syntax");
  lines.push("import Velvet.Std");

  for (const decl of decls) {
    lines.push("");
    if (decl.kind === "string-union") {
      lines.push(`inductive ${decl.name} where`);
      lines.push(`  | ${decl.values!.join(" | ")}`);
      lines.push(`deriving Repr, Inhabited, DecidableEq`);
    } else if (decl.kind === "discriminated-union") {
      lines.push(`inductive ${decl.name} where`);
      for (const v of decl.variants!) {
        if (v.fields.length === 0) {
          lines.push(`  | ${v.name} : ${decl.name}`);
        } else {
          const params = v.fields.map(f => `(${f.name} : ${tsTypeToLean(f.tsType)})`).join(" ");
          lines.push(`  | ${v.name} ${params} : ${decl.name}`);
        }
      }
      lines.push(`deriving Repr, Inhabited`);
    } else if (decl.kind === "record") {
      lines.push(`structure ${decl.name} where`);
      for (const f of decl.fields!) {
        lines.push(`  ${f.name} : ${tsTypeToLean(f.tsType)}`);
      }
      lines.push(`deriving Repr, Inhabited, DecidableEq`);
    }
  }

  return lines.join("\n") + "\n";
}
