import { test } from "node:test";
import assert from "node:assert/strict";
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { dafnyCheckDiff, dafnyVerifyArgs } from "../src/dafny-commands.ts";

function fixture(gen: string, proof: string, check: (g: string, p: string, dir: string) => void): void {
  const dir = mkdtempSync(join(tmpdir(), "lsc-git-review-"));
  try {
    const g = join(dir, "file.dfy.gen");
    const p = join(dir, "file.dfy");
    writeFileSync(g, gen);
    writeFileSync(p, proof);
    check(g, p, dir);
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

function env(values: Record<string, string>, run: () => void): void {
  const before = Object.fromEntries(Object.keys(values).map(k => [k, process.env[k]]));
  try { Object.assign(process.env, values); run(); }
  finally {
    for (const [k, v] of Object.entries(before)) {
      if (v === undefined) delete process.env[k]; else process.env[k] = v;
    }
  }
}

test("identical content passes", () => fixture("method M() {}\n", "method M() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), true);
}));
test("proof additions pass", () => fixture("method M() {}\n", "method M() {}\nlemma Proof() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), true);
}));
test("generated modifications fail", () => fixture("method M() {}\n", "method Changed() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), false);
}));
test("missing inputs fail closed", () => fixture("x\n", "x\n", (g, p, dir) => {
  assert.equal(dafnyCheckDiff(join(dir, "missing"), p), false);
  assert.equal(dafnyCheckDiff(g, join(dir, "missing")), false);
}));

test("forced Git color cannot hide deleted generated lines", () => {
  env({ GIT_CONFIG_COUNT: "1", GIT_CONFIG_KEY_0: "color.ui", GIT_CONFIG_VALUE_0: "always" }, () => {
    fixture("method M() {}\n", "method Changed() {}\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
    fixture("method M() {}\n", "method M() {}\nlemma Proof() {}\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), true));
  });
});

test("binary detection cannot turn changed inputs into an additions-only pass", () => {
  fixture("before\0value\n", "after\0value\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
});

test("deletions beginning with dashes inside a hunk are not file headers", () => {
  fixture('const value := @"\n--before\n";\n', 'const value := @"\n--after\n";\n',
    (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
});

test("external diff configuration is not executed for the proof guard", { skip: process.platform === "win32" }, () => {
  fixture("method M() {}\n", "method Changed() {}\n", (g, p, dir) => {
    const command = join(dir, "external-diff");
    writeFileSync(command, "#!/bin/sh\nprintf 'external output\\n'\nexit 0\n");
    chmodSync(command, 0o755);
    env({ GIT_EXTERNAL_DIFF: command }, () => assert.equal(dafnyCheckDiff(g, p), false));
  });
});

for (const script of ["exit 1", "printf 'not a patch\\n'; exit 1", "printf 'partial\\n'; exit 2"]) {
  test(`failed comparison is rejected: ${script}`, { skip: process.platform === "win32" }, () => {
    fixture("x\n", "y\n", (g, p, dir) => {
      const command = join(dir, "git");
      writeFileSync(command, `#!/bin/sh\n${script}\n`);
      chmodSync(command, 0o755);
      env({ PATH: dir }, () => assert.equal(dafnyCheckDiff(g, p), false));
    });
  });
}

test("missing Git executable is not success", () => {
  fixture("x\n", "y\n", (g, p, dir) => env({ PATH: dir }, () => assert.equal(dafnyCheckDiff(g, p), false)));
});

test("no header token pins Dafny's default char mode explicitly", () => {
  assert.deepEqual(dafnyVerifyArgs("// Generated by lsc from a.ts\nmethod M() {}\n").args, ["verify", "--unicode-char:true"]);
  assert.deepEqual(dafnyVerifyArgs("method M() {}\n").args, ["verify", "--unicode-char:true"]);
});

test("javascript-utf16 selects code-unit chars and only the deprecation waiver", () => {
  const { args, error } = dafnyVerifyArgs("// Generated by lsc from a.ts\n// lsc options: string-semantics=javascript-utf16\n");
  assert.equal(error, undefined);
  assert.deepEqual(args, ["verify", "--unicode-char:false", "--allow-deprecation"]);
});

test("javascript-utf16 refuses the Unicode-scalar standard library", () => {
  const { error } = dafnyVerifyArgs("// lsc options: string-semantics=javascript-utf16\nimport opened Std.Arithmetic.Mul\n");
  assert.match(error ?? "", /string-semantics/);
});

test("an unknown string-semantics token is an error, not a silent default", () => {
  assert.match(dafnyVerifyArgs("// lsc options: string-semantics=utf8\n").error ?? "", /unknown string-semantics 'utf8'/);
});

test("time limit and extra flags keep their positions before the char-mode pin", () => {
  assert.deepEqual(
    dafnyVerifyArgs("method M() {}\n", 30, "--isolate-assertions").args,
    ["verify", "--verification-time-limit", "30", "--isolate-assertions", "--unicode-char:true"],
  );
});
