// Generated by lsc. Program source: blockScopeReuse.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MblockScopeReuse_b5e522675de6

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_sumThenCount  (v_xs:(S.seq int))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_total_2 : int = (0) in
  let v_i_5f_2_3 : int = (0) in
  let rec ls_loop_4 (v_total_6:int) (v_i_5f_2_7:int)
    : Ghost int
        (requires (
          0 <= v_total_6 /\ 0 <= v_i_5f_2_7 /\ (v_i_5f_2_7 <= (S.length (v_xs))) /\ (v_total_6 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int ((S.length (v_xs)) - v_i_5f_2_7))) =
    if (v_i_5f_2_7 < (S.length (v_xs))) then (
      if ((S.index (v_xs) (v_i_5f_2_7)) > (0)) then (
        let v_total_8 : int = (v_total_6 + (1)) in
        let v_i_5f_2_9 : int = (v_i_5f_2_7 + (1)) in
        (ls_loop_4 (v_total_8) (v_i_5f_2_9))
      ) else (
        let v_i_5f_2_10 : int = (v_i_5f_2_7 + (1)) in
        (ls_loop_4 (v_total_6) (v_i_5f_2_10))
      )
    ) else (
      let v_i_11 : int = (0) in
      let rec ls_loop_12 (v_i_14:int)
        : Ghost int
            (requires (
              0 <= v_i_14 /\ ((0) <= v_i_14) /\ (v_i_14 <= v_total_6) /\ (v_total_6 >= (0))
            ))
            (ensures (fun ls_result ->
              (ls_result >= (0))
            ))
            (decreases (R.nat_of_int (v_total_6 - v_i_14))) =
        if (v_i_14 < v_total_6) then (
          let v_i_15 : int = (v_i_14 + (1)) in
          (ls_loop_12 (v_i_15))
        ) else (
          v_total_6
        )
      in
      (ls_loop_12 (v_i_11))
    )
  in
  (ls_loop_4 (v_total_2) (v_i_5f_2_3))

let v_dodgeTakenName  (v_n:int)
  : Ghost int
      (requires (
        (v_n >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_acc_18 : int = (0) in
  let v_i_5f_2_19 : int = v_n in
  let v_i_5f_3_20 : int = (0) in
  let rec ls_loop_21 (v_acc_23:int) (v_i_5f_3_24:int)
    : Ghost int
        (requires (
          0 <= v_acc_23 /\ 0 <= v_i_5f_3_24 /\ (v_i_5f_3_24 <= v_n) /\ (v_acc_23 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int (v_n - v_i_5f_3_24))) =
    if (v_i_5f_3_24 < v_n) then (
      let v_acc_25 : int = (v_acc_23 + (1)) in
      let v_i_5f_3_26 : int = (v_i_5f_3_24 + (1)) in
      (ls_loop_21 (v_acc_25) (v_i_5f_3_26))
    ) else (
      let v_i_27 : int = (0) in
      let rec ls_loop_28 (v_acc_30:int) (v_i_31:int)
        : Ghost int
            (requires (
              0 <= v_acc_30 /\ 0 <= v_i_31 /\ ((0) <= v_i_31) /\ (v_i_31 <= v_n) /\ (v_acc_30 >= (0))
            ))
            (ensures (fun ls_result ->
              (ls_result >= (0))
            ))
            (decreases (R.nat_of_int (v_n - v_i_31))) =
        if (v_i_31 < v_n) then (
          let v_acc_32 : int = (v_acc_30 + (1)) in
          let v_i_33 : int = (v_i_31 + (1)) in
          (ls_loop_28 (v_acc_32) (v_i_33))
        ) else (
          (v_acc_30 + (v_i_5f_2_19 - v_i_5f_2_19))
        )
      in
      (ls_loop_28 (v_acc_23) (v_i_27))
    )
  in
  (ls_loop_21 (v_acc_18) (v_i_5f_3_20))
