// Generated by lsc. Program source: declareTypeShadow.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MdeclareTypeShadow_6c80ce1e7ace

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_RawMsg  = {
  f_v_RawMsg_v_kind: R.string;
}

let v_countMsgs  (v_msgs:(S.seq v_RawMsg))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  (S.length (v_msgs))
