// Generated by lsc. Program source: forContinue.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MforContinue_60c55b7355ff

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Kind  =
| C_v_Kind_v_keep : v_Kind
| C_v_Kind_v_skip : v_Kind
| C_v_Kind_v_stop : v_Kind

type v_Item  = {
  f_v_Item_v_kind: v_Kind;
}

let v_countOdds  (v_xs:(S.seq int))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result <= (S.length (v_xs)))
      )) =
  let v_n_2 : int = (0) in
  let v_i_3 : int = (0) in
  let rec ls_loop_4 (v_n_6:int) (v_i_7:int)
    : Ghost int
        (requires (
          0 <= v_n_6 /\ 0 <= v_i_7 /\ (v_i_7 <= (S.length (v_xs))) /\ (v_n_6 <= v_i_7)
        ))
        (ensures (fun ls_result ->
          (ls_result <= (S.length (v_xs)))
        ))
        (decreases (R.nat_of_int ((S.length (v_xs)) - v_i_7))) =
    if (v_i_7 < (S.length (v_xs))) then (
      if (R.decide (((R.rem ((S.index (v_xs) (v_i_7))) ((2))) == (0)))) then (
        let v_i_8 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_n_6) (v_i_8))
      ) else (
        let v_n_9 : int = (v_n_6 + (1)) in
        let v_i_10 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_n_9) (v_i_10))
      )
    ) else (
      v_n_6
    )
  in
  (ls_loop_4 (v_n_2) (v_i_3))

let v_copyNonzero  (v_xs:(S.seq int))
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) <= (S.length (v_xs)))
      )) =
  let v_out_13 : (S.seq int) = S.empty in
  let v_i_14 : int = (0) in
  let rec ls_loop_15 (v_out_17:(S.seq int)) (v_i_18:int)
    : Ghost (S.seq int)
        (requires (
          0 <= v_i_18 /\ (v_i_18 <= (S.length (v_xs))) /\ ((S.length (v_out_17)) <= v_i_18)
        ))
        (ensures (fun ls_result ->
          ((S.length (ls_result)) <= (S.length (v_xs)))
        ))
        (decreases (R.nat_of_int ((S.length (v_xs)) - v_i_18))) =
    if (v_i_18 < (S.length (v_xs))) then (
      let v_v_19 : int = (S.index (v_xs) (v_i_18)) in
      if (R.decide ((v_v_19 == (0)))) then (
        let v_i_20 : int = (v_i_18 + (1)) in
        (ls_loop_15 (v_out_17) (v_i_20))
      ) else (
        if (v_v_19 < (0)) then (
          let v_i_21 : int = (v_i_18 + (1)) in
          (ls_loop_15 (v_out_17) (v_i_21))
        ) else (
          let v_out_22 : (S.seq int) = (S.build (v_out_17) (v_v_19)) in
          let v_i_23 : int = (v_i_18 + (1)) in
          (ls_loop_15 (v_out_22) (v_i_23))
        )
      )
    ) else (
      v_out_17
    )
  in
  (ls_loop_15 (v_out_13) (v_i_14))

let v_countPositivesNonNested  (v_grid:(S.seq (S.seq int)))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_total_26 : int = (0) in
  let v_i_27 : int = (0) in
  let rec ls_loop_28 (v_total_30:int) (v_i_31:int)
    : Ghost int
        (requires (
          0 <= v_total_30 /\ 0 <= v_i_31 /\ (v_i_31 <= (S.length (v_grid))) /\ (v_total_30 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int ((S.length (v_grid)) - v_i_31))) =
    if (v_i_31 < (S.length (v_grid))) then (
      let v_row_32 : (S.seq int) = (S.index (v_grid) (v_i_31)) in
      let v__5f_x_5f_idx_33 : int = (0) in
      let rec ls_loop_34 (v_total_36:int) (v__5f_x_5f_idx_37:int)
        : Ghost int
            (requires (
              0 <= v_total_36 /\ 0 <= v__5f_x_5f_idx_37 /\ (v__5f_x_5f_idx_37 <= (S.length (v_row_32))) /\ (v__5f_x_5f_idx_37 <= (S.length (v_row_32))) /\ (v_total_36 >= (0))
            ))
            (ensures (fun ls_result ->
              (ls_result >= (0))
            ))
            (decreases (R.nat_of_int ((S.length (v_row_32)) - v__5f_x_5f_idx_37))) =
        if (v__5f_x_5f_idx_37 < (S.length (v_row_32))) then (
          let v_x_38 : int = (S.index (v_row_32) (v__5f_x_5f_idx_37)) in
          if (not (v_x_38 <= (0))) then (
            let v_total_39 : int = (v_total_36 + (1)) in
            let v__5f_x_5f_idx_40 : int = (v__5f_x_5f_idx_37 + (1)) in
            (ls_loop_34 (v_total_39) (v__5f_x_5f_idx_40))
          ) else (
            let v__5f_x_5f_idx_41 : int = (v__5f_x_5f_idx_37 + (1)) in
            (ls_loop_34 (v_total_36) (v__5f_x_5f_idx_41))
          )
        ) else (
          let v_i_42 : int = (v_i_31 + (1)) in
          (ls_loop_28 (v_total_36) (v_i_42))
        )
      in
      (ls_loop_34 (v_total_30) (v__5f_x_5f_idx_33))
    ) else (
      v_total_30
    )
  in
  (ls_loop_28 (v_total_26) (v_i_27))

let v_lastPresent  (v_xs:(S.seq (option int)))
  : Ghost (option int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  let v_cur_44 : (option int) = None in
  let v__5f_x_5f_idx_45 : int = (0) in
  let rec ls_loop_46 (v_cur_48:(option int)) (v__5f_x_5f_idx_49:int)
    : Ghost (option int)
        (requires (
          0 <= v__5f_x_5f_idx_49 /\ (v__5f_x_5f_idx_49 <= (S.length (v_xs))) /\ (v__5f_x_5f_idx_49 <= (S.length (v_xs)))
        ))
        (ensures (fun ls_result ->
          True
        ))
        (decreases (R.nat_of_int ((S.length (v_xs)) - v__5f_x_5f_idx_49))) =
    if (v__5f_x_5f_idx_49 < (S.length (v_xs))) then (
      let v_x_50 : (option int) = (S.index (v_xs) (v__5f_x_5f_idx_49)) in
      match v_x_50 with
      | Some v__5f_x_5f_val -> (
        let v_cur_52 : (option int) = (Some (v__5f_x_5f_val)) in
        let v__5f_x_5f_idx_53 : int = (v__5f_x_5f_idx_49 + (1)) in
        (ls_loop_46 (v_cur_52) (v__5f_x_5f_idx_53))
      )
      | None -> (
        let v__5f_x_5f_idx_54 : int = (v__5f_x_5f_idx_49 + (1)) in
        (ls_loop_46 (v_cur_48) (v__5f_x_5f_idx_54))
      )
    ) else (
      v_cur_48
    )
  in
  (ls_loop_46 (v_cur_44) (v__5f_x_5f_idx_45))

let v_lastBeforeGap  (v_xs:(S.seq (option int)))
  : Ghost (option int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  let v_cur_56 : (option int) = None in
  let v__5f_x_5f_idx_57 : int = (0) in
  let rec ls_loop_58 (v_cur_60:(option int)) (v__5f_x_5f_idx_61:int)
    : Ghost (option int)
        (requires (
          0 <= v__5f_x_5f_idx_61 /\ (v__5f_x_5f_idx_61 <= (S.length (v_xs))) /\ (v__5f_x_5f_idx_61 <= (S.length (v_xs)))
        ))
        (ensures (fun ls_result ->
          True
        ))
        (decreases (R.nat_of_int ((S.length (v_xs)) - v__5f_x_5f_idx_61))) =
    if (v__5f_x_5f_idx_61 < (S.length (v_xs))) then (
      let v_x_62 : (option int) = (S.index (v_xs) (v__5f_x_5f_idx_61)) in
      match v_x_62 with
      | Some v__5f_x_5f_val -> (
        let v_cur_64 : (option int) = (Some (v__5f_x_5f_val)) in
        let v__5f_x_5f_idx_65 : int = (v__5f_x_5f_idx_61 + (1)) in
        (ls_loop_58 (v_cur_64) (v__5f_x_5f_idx_65))
      )
      | None -> (
        v_cur_60
      )
    ) else (
      v_cur_60
    )
  in
  (ls_loop_58 (v_cur_56) (v__5f_x_5f_idx_57))

let v_countKeep  (v_items:(S.seq v_Item))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((0) <= ls_result) /\ (ls_result <= (S.length (v_items)))
      )) =
  let v_count_69 : int = (0) in
  let v_i_70 : int = (0) in
  let rec ls_loop_71 (v_count_73:int) (v_i_74:int)
    : Ghost int
        (requires (
          0 <= v_count_73 /\ 0 <= v_i_74 /\ ((0) <= v_i_74) /\ (v_i_74 <= (S.length (v_items))) /\ ((0) <= v_count_73) /\ (v_count_73 <= v_i_74)
        ))
        (ensures (fun ls_result ->
          ((0) <= ls_result) /\ (ls_result <= (S.length (v_items)))
        ))
        (decreases (R.nat_of_int ((S.length (v_items)) - v_i_74))) =
    if (v_i_74 < (S.length (v_items))) then (
      match ((S.index (v_items) (v_i_74))).f_v_Item_v_kind with
      | C_v_Kind_v_skip -> (
        let v_i_75 : int = (v_i_74 + (1)) in
        (ls_loop_71 (v_count_73) (v_i_75))
      )
      | C_v_Kind_v_stop -> (
        v_count_73
      )
      | C_v_Kind_v_keep -> (
        let v_count_76 : int = (v_count_73 + (1)) in
        let v_i_77 : int = (v_i_74 + (1)) in
        (ls_loop_71 (v_count_76) (v_i_77))
      )
    ) else (
      v_count_73
    )
  in
  (ls_loop_71 (v_count_69) (v_i_70))
