// Generated by lsc. Program source: pureGuard.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MpureGuard_e947a27225a4

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Post  = {
  f_v_Post_v_title: (option R.string);
}

let v_suffixed  (v_post:v_Post) (v_suffix:(option R.string))
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.equal (ls_result) ((S.build ((S.build ((S.build (S.empty) (121))) (101))) (115)))) \/ (S.equal (ls_result) ((S.build ((S.build (S.empty) (110))) (111)))))
      )) =
  (match v_suffix with
  | Some v__5f_suffix_5f_val -> (if (match (match (v_post).f_v_Post_v_title with
  | Some v__5f_oc0_5f_val -> (Some ((R.endsWith (v__5f_oc0_5f_val) (v__5f_suffix_5f_val))))
  | None -> None) with
  | Some v__5f_oc1_5f_val -> v__5f_oc1_5f_val
  | None -> false) then (S.build ((S.build ((S.build (S.empty) (121))) (101))) (115)) else (S.build ((S.build (S.empty) (110))) (111)))
  | None -> (S.build ((S.build (S.empty) (110))) (111)))
