// Generated by lsc. Program source: setFromArray.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MsetFromArray_417a2e59437e

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_dedupSize  (v_arr:(S.seq int))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (let v_s_1 = (R.set_from_seq (v_arr)) in
  (FS.cardinality (v_s_1)))

let v_member  (v_arr:(S.seq int)) (v_x:int)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result <==> (exists (v_i:nat). ((v_i < (S.length (v_arr))) /\ ((S.index (v_arr) (v_i)) == v_x))))
      )) =
  (let v_s_6 = (R.set_from_seq (v_arr)) in
  (FS.mem (v_x) (v_s_6)))
