// Generated by lsc. Program source: swap.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mswap_cccc900a12e2

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_swap  (v_arr:(S.seq int)) (v_i:nat) (v_j:nat)
  : Ghost (S.seq int)
      (requires (
        (v_i < (S.length (v_arr))) /\ (v_j < (S.length (v_arr)))
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) == (S.length (v_arr))) /\ ((S.index (ls_result) (v_i)) == (S.index (v_arr) (v_j))) /\ ((S.index (ls_result) (v_j)) == (S.index (v_arr) (v_i)))
      )) =
  let v_result_6 : (S.seq int) = v_arr in
  let v_tmp_7 : int = (S.index (v_result_6) (v_i)) in
  let v_result_8 : (S.seq int) = (S.update (v_result_6) (v_i) ((S.index (v_result_6) (v_j)))) in
  let v_result_9 : (S.seq int) = (S.update (v_result_8) (v_j) (v_tmp_7)) in
  v_result_9
