// Generated by lsc. Program source: switchFallthrough.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MswitchFallthrough_1283c811633f

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Tag  =
| C_v_Tag_v_a : v_Tag
| C_v_Tag_v_b : v_Tag
| C_v_Tag_v_c : v_Tag
| C_v_Tag_v_skip : v_Tag

type v_Item  = {
  f_v_Item_v_tag: v_Tag;
}

let v_collect  (v_items:(S.seq v_Item))
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) <= (S.length (v_items)))
      )) =
  let v_out_2 : (S.seq int) = S.empty in
  let v_i_3 : int = (0) in
  let rec ls_loop_4 (v_out_6:(S.seq int)) (v_i_7:int)
    : Ghost (S.seq int)
        (requires (
          0 <= v_i_7 /\ ((0) <= v_i_7) /\ (v_i_7 <= (S.length (v_items))) /\ ((S.length (v_out_6)) <= v_i_7)
        ))
        (ensures (fun ls_result ->
          ((S.length (ls_result)) <= (S.length (v_items)))
        ))
        (decreases (R.nat_of_int ((S.length (v_items)) - v_i_7))) =
    if (v_i_7 < (S.length (v_items))) then (
      let v_t_8 : v_Tag = ((S.index (v_items) (v_i_7))).f_v_Item_v_tag in
      match v_t_8 with
      | C_v_Tag_v_a -> (
        let v_out_9 : (S.seq int) = (S.build (v_out_6) (v_i_7)) in
        let v_i_10 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_out_9) (v_i_10))
      )
      | C_v_Tag_v_b -> (
        let v_out_11 : (S.seq int) = (S.build (v_out_6) (v_i_7)) in
        let v_i_12 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_out_11) (v_i_12))
      )
      | C_v_Tag_v_c -> (
        let v_out_13 : (S.seq int) = (S.build (v_out_6) (v_i_7)) in
        let v_i_14 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_out_13) (v_i_14))
      )
      | C_v_Tag_v_skip -> (
        let v_i_15 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_out_6) (v_i_15))
      )
    ) else (
      v_out_6
    )
  in
  (ls_loop_4 (v_out_2) (v_i_3))

let v_score  (v_tag:v_Tag)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_r_18 : int = (0) in
  match v_tag with
  | C_v_Tag_v_a -> (
    let v_r_19 : int = (v_r_18 + (1)) in
    let v_r_20 : int = (v_r_19 + (10)) in
    v_r_20
  )
  | C_v_Tag_v_b -> (
    let v_r_21 : int = (v_r_18 + (10)) in
    v_r_21
  )
  | C_v_Tag_v_c -> (
    let v_r_22 : int = (v_r_18 + (100)) in
    v_r_22
  )
  | C_v_Tag_v_skip -> (
    v_r_18
  )
