// Generated by lsc. Program source: templateConcat.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MtemplateConcat_659afe04ed10

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_noSep  (v_a:int) (v_b:int)
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (S.append ((S.append (S.empty) ((R.int_to_string (v_a))))) ((R.int_to_string (v_b))))

let v_bracketed  (v_a:int) (v_b:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (4))
      )) =
  (S.length ((S.append ((S.append ((S.append ((S.append ((S.build (S.empty) (91))) ((R.int_to_string (v_a))))) ((S.build ((S.build (S.empty) (93))) (91))))) ((R.int_to_string (v_b))))) ((S.build (S.empty) (93))))))
