// Generated by lsc. Program source: tuples.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mtuples_e8e551aa565a

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_swap  (v_p:(int & R.string))
  : Ghost (R.string & int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (S.equal ((let (ls_item, _) = ls_result in ls_item)) ((let (_, ls_item) = v_p in ls_item))) /\ ((let (_, ls_item) = ls_result in ls_item) == (let (ls_item, _) = v_p in ls_item))
      )) =
  ((let (_, ls_item) = v_p in ls_item), (let (ls_item, _) = v_p in ls_item))

let v_middle  (v_t:(int & R.string & bool))
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (S.equal (ls_result) ((let (_, ls_item, _) = v_t in ls_item)))
      )) =
  (let (_, ls_item, _) = v_t in ls_item)

let v_addFirstTwo  (v_p:(int & int & R.string))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == ((let (ls_item, _, _) = v_p in ls_item) + (let (_, ls_item, _) = v_p in ls_item)))
      )) =
  (let v_a_7 = (let (ls_item, _, _) = v_p in ls_item) in
  (let v_b_8 = (let (_, ls_item, _) = v_p in ls_item) in
  (v_a_7 + v_b_8)))

let v_homogeneousStaysSeq  (v_xs:(S.seq int))
  : Ghost int
      (requires (
        ((S.length (v_xs)) == (2))
      ))
      (ensures (fun ls_result ->
        (ls_result == ((S.index (v_xs) ((0))) + (S.index (v_xs) ((1)))))
      )) =
  ((S.index (v_xs) ((0))) + (S.index (v_xs) ((1))))

let v_sumFirsts  (v_pairs:(S.seq (int & R.string)))
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  let v_out_12 : (S.seq int) = S.empty in
  let v__5f_n_5f_idx_13 : int = (0) in
  let rec ls_loop_14 (v_out_16:(S.seq int)) (v__5f_n_5f_idx_17:int)
    : Ghost (S.seq int)
        (requires (
          0 <= v__5f_n_5f_idx_17 /\ (v__5f_n_5f_idx_17 <= (S.length (v_pairs))) /\ (v__5f_n_5f_idx_17 <= (S.length (v_pairs)))
        ))
        (ensures (fun ls_result ->
          True
        ))
        (decreases (R.nat_of_int ((S.length (v_pairs)) - v__5f_n_5f_idx_17))) =
    if (v__5f_n_5f_idx_17 < (S.length (v_pairs))) then (
      let v__5f_n_5f_elem_18 : (int & R.string) = (S.index (v_pairs) (v__5f_n_5f_idx_17)) in
      let v_n_19 : int = (let (ls_item, _) = v__5f_n_5f_elem_18 in ls_item) in
      let v_label_20 : R.string = (let (_, ls_item) = v__5f_n_5f_elem_18 in ls_item) in
      let v_out_21 : (S.seq int) = (S.build (v_out_16) (v_n_19)) in
      let v__5f_n_5f_idx_22 : int = (v__5f_n_5f_idx_17 + (1)) in
      (ls_loop_14 (v_out_21) (v__5f_n_5f_idx_22))
    ) else (
      v_out_16
    )
  in
  (ls_loop_14 (v_out_12) (v__5f_n_5f_idx_13))
