// Generated by lsc from accessPolicy.ts

datatype AccessRequest = AccessRequest(member: bool, invited: bool, suspended: bool)

function either<A>(first: (A) -> bool, second: (A) -> bool): (A) -> bool
{
  (value: A) => (first(value) || second(value))
}

lemma either_ensures<A>(first: (A) -> bool, second: (A) -> bool)
  ensures forall value: A :: ((var i_callee := either(first, second); i_callee(value)) == (first(value) || second(value)))
{
}

function denyOverride<A>(eligible: (A) -> bool, denied: (A) -> bool): (A) -> bool
{
  (value: A) => (eligible(value) && !(denied(value)))
}

lemma denyOverride_ensures<A>(eligible: (A) -> bool, denied: (A) -> bool)
  ensures forall value: A :: ((var i_callee := denyOverride(eligible, denied); i_callee(value)) == (eligible(value) && !(denied(value))))
{
}

function accessPolicy<A>(primary: (A) -> bool, fallback: (A) -> bool, denied: (A) -> bool): (A) -> bool
{
  var eligible := either(primary, fallback);
  denyOverride(eligible, denied)
}

lemma accessPolicy_ensures<A>(primary: (A) -> bool, fallback: (A) -> bool, denied: (A) -> bool)
  ensures forall value: A :: ((var i_callee := accessPolicy(primary, fallback, denied); i_callee(value)) == ((primary(value) || fallback(value)) && !(denied(value))))
{
}

function canEnter(request: AccessRequest): bool
{
  var i_callee := accessPolicy((candidate: AccessRequest) => candidate.member, (candidate: AccessRequest) => candidate.invited, (candidate: AccessRequest) => candidate.suspended);
  i_callee(request)
}

lemma canEnter_ensures(request: AccessRequest)
  ensures (canEnter(request) == ((request.member || request.invited) && !(request.suspended)))
{
}

function suspendedCannotEnter(request: AccessRequest): bool
  requires request.suspended
{
  canEnter(request)
}

lemma suspendedCannotEnter_ensures(request: AccessRequest)
  requires request.suspended
  ensures !(suspendedCannotEnter(request))
{
}
