/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure Inner where
  val : Int
deriving Repr, Inhabited, DecidableEq

structure Box where
  items : Array Int
  inner : Option Inner
deriving Repr, Inhabited, DecidableEq

namespace Pure

def total (xs : Array Int) : Int :=
  xs.size

def use (v : Int) : Int :=
  v

def plain (p : Bool) (q : Bool) : Bool :=
  p ∧ q

end Pure
