// Generated by lsc. Program source: arrayIsArrayChain.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MarrayIsArrayChain_c0423acd11c6

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Part  = {
  f_v_Part_v_type: R.string;
}

noeq type v_ArrayOf_5f_Part_5f_Or_5f_string  =
| C_v_ArrayOf_5f_Part_5f_Or_5f_string_v_ArrayBranch : (S.seq v_Part) -> v_ArrayOf_5f_Part_5f_Or_5f_string
| C_v_ArrayOf_5f_Part_5f_Or_5f_string_v_NonArrayBranch : R.string -> v_ArrayOf_5f_Part_5f_Or_5f_string

noeq type v_Msg  = {
  f_v_Msg_v_role: R.string;
  f_v_Msg_v_content: v_ArrayOf_5f_Part_5f_Or_5f_string;
}

let v_countAssistantParts  (v_msgs:(S.seq v_Msg))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_n_2 : int = (0) in
  let v_i_3 : int = (0) in
  let rec ls_loop_4 (v_n_6:int) (v_i_7:int)
    : Ghost int
        (requires (
          0 <= v_i_7 /\ (v_i_7 <= (S.length (v_msgs))) /\ (v_n_6 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int ((S.length (v_msgs)) - v_i_7))) =
    if (v_i_7 < (S.length (v_msgs))) then (
      let v_m_8 : v_Msg = (S.index (v_msgs) (v_i_7)) in
      match (v_m_8).f_v_Msg_v_content with
      | C_v_ArrayOf_5f_Part_5f_Or_5f_string_v_ArrayBranch v__5f_m_5f_content_5f_arr -> (
        if (R.decide ((S.equal ((v_m_8).f_v_Msg_v_role) ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (97))) (115))) (115))) (105))) (115))) (116))) (97))) (110))) (116)))))) then (
          let v_n_10 : int = (v_n_6 + (S.length (v__5f_m_5f_content_5f_arr))) in
          let v_i_11 : int = (v_i_7 + (1)) in
          (ls_loop_4 (v_n_10) (v_i_11))
        ) else (
          let v_i_12 : int = (v_i_7 + (1)) in
          (ls_loop_4 (v_n_6) (v_i_12))
        )
      )
      | C_v_ArrayOf_5f_Part_5f_Or_5f_string_v_NonArrayBranch v__5f_m_5f_content_5f_val -> (
        let v_i_14 : int = (v_i_7 + (1)) in
        (ls_loop_4 (v_n_6) (v_i_14))
      )
    ) else (
      v_n_6
    )
  in
  (ls_loop_4 (v_n_2) (v_i_3))
