/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure Entry where
  key : String
  val : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def lookup (entries : Array Entry) (key : String) : Int :=
  let e := entries.find? (fun x => x.key = key)
  match (match e with | .some _oc0_val => Option.some _oc0_val.val | .none => Option.none) with
  | .some _oc1_val =>
    _oc1_val
  | .none =>
    0

def hasEntry (entries : Array Entry) (key : String) : Bool :=
  match entries.find? (fun x => x.key = key) with
  | .some _ =>
    true
  | .none =>
    false

end Pure
