/-
  Generated by lsc from arraySum.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «arraySum.spec»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method arraySum (arr : Array Int) return (res : Int)
  ensures res = sumTo arr arr.size
  do
    let mut sum : Int := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant 0 ≤ i
      invariant i ≤ arr.size
      invariant sum = sumTo arr i
      decreasing arr.size - i
    do
      sum := sum + arr[i]!
      i := i + 1
    return sum
