// Generated by lsc. Program source: arrayContains.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MarrayContains_5fe38c5a6851

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_arrayContains  (v_arr:(S.seq int)) (v_target:int)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == true) ==> (exists (v_k:nat). ((v_k < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) == v_target)))) /\ ((ls_result == false) ==> (forall (v_k:nat). ((v_k < (S.length (v_arr))) ==> ((S.index (v_arr) (v_k)) =!= v_target))))
      )) =
  let v_found_6 : bool = false in
  let v__5f_x_5f_idx_7 : int = (0) in
  let rec ls_loop_8 (v_found_10:bool) (v__5f_x_5f_idx_11:int)
    : Ghost bool
        (requires (
          0 <= v__5f_x_5f_idx_11 /\ (v__5f_x_5f_idx_11 <= (S.length (v_arr))) /\ (v__5f_x_5f_idx_11 <= (S.length (v_arr))) /\ ((v_found_10 == false) ==> (forall (v_k:nat). ((v_k < v__5f_x_5f_idx_11) ==> ((S.index (v_arr) (v_k)) =!= v_target)))) /\ ((v_found_10 == true) ==> (exists (v_k:nat). ((v_k < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) == v_target))))
        ))
        (ensures (fun ls_result ->
          ((ls_result == true) ==> (exists (v_k:nat). ((v_k < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) == v_target)))) /\ ((ls_result == false) ==> (forall (v_k:nat). ((v_k < (S.length (v_arr))) ==> ((S.index (v_arr) (v_k)) =!= v_target))))
        ))
        (decreases (R.nat_of_int ((S.length (v_arr)) - v__5f_x_5f_idx_11))) =
    if (v__5f_x_5f_idx_11 < (S.length (v_arr))) then (
      let v_x_14 : int = (S.index (v_arr) (v__5f_x_5f_idx_11)) in
      if (R.decide ((v_x_14 == v_target))) then (
        let v_found_15 : bool = true in
        v_found_15
      ) else (
        let v__5f_x_5f_idx_16 : int = (v__5f_x_5f_idx_11 + (1)) in
        (ls_loop_8 (v_found_10) (v__5f_x_5f_idx_16))
      )
    ) else (
      v_found_10
    )
  in
  (ls_loop_8 (v_found_6) (v__5f_x_5f_idx_7))
