/-
  Generated by lsc from arrayFind.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «arrayFind.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method lookup (entries : Array Entry) (key : String) return (res : Int)
  do
    return Pure.lookup entries key

method hasEntry (entries : Array Entry) (key : String) return (res : Bool)
  do
    return Pure.hasEntry entries key
