// Generated by lsc from arrayFind.ts
// LemmaScript string model: javascript-utf16-code-units

datatype Option<T> = None | Some(value: T)

function SeqFind<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFind(s, p).Some? ==> p(SeqFind(s, p).value)
  ensures SeqFind(s, p).Some? ==> SeqFind(s, p).value in s
  ensures SeqFind(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFind(s, p).value && p(s[i]) &&
                     (forall j: nat :: j < i ==> !p(s[j]))
  ensures SeqFind(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[0]) then Some(s[0])
  else SeqFind(s[1..], p)
}

datatype Entry = Entry(key: string, val: int)

function lookup(entries: seq<Entry>, key: string): int
{
  var e := SeqFind(entries, (x: Entry) => (x.key == key));
  match (match e { case Some(i_oc0_val) => Option.Some(i_oc0_val.val) case None => Option.None }) {
    case Some(i_oc1_val) =>
      i_oc1_val
    case None =>
      0
  }
}

function hasEntry(entries: seq<Entry>, key: string): bool
{
  match SeqFind(entries, (x: Entry) => (x.key == key)) {
    case Some(i_) =>
      true
    case None =>
      false
  }
}
