// Generated by lsc from assume.ts

method shortenString(text: string) returns (res: int)
  ensures (res >= 0)
  ensures (res <= |text|)
{
  var cleaned: string := *;
  assume {:axiom} (|cleaned| <= |text|);
  return |cleaned|;
}
