// Generated by lsc. Program source: auction.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mauction_e573c1ede1cf

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Bid  = {
  f_v_Bid_v_key: R.string;
  f_v_Bid_v_amount: int;
}

let v_highestBid  (v_bids:(S.seq (option v_Bid))) (v_key:R.string) (v_reserve:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_reserve)
      )) =
  let v_best_4 : int = v_reserve in
  let v_i_5 : int = (0) in
  let rec ls_loop_6 (v_best_8:int) (v_i_9:int)
    : Ghost int
        (requires (
          0 <= v_i_9 /\ (v_best_8 >= v_reserve)
        ))
        (ensures (fun ls_result ->
          (ls_result >= v_reserve)
        ))
        (decreases (R.nat_of_int ((S.length (v_bids)) - v_i_9))) =
    if (v_i_9 < (S.length (v_bids))) then (
      let v_bid_10 : (option v_Bid) = (S.index (v_bids) (v_i_9)) in
      match v_bid_10 with
      | Some v__5f_bid_5f_val -> (
        if (R.decide ((not (S.equal ((v__5f_bid_5f_val).f_v_Bid_v_key) (v_key))))) then (
          let v_i_12 : int = (v_i_9 + (1)) in
          (ls_loop_6 (v_best_8) (v_i_12))
        ) else (
          if ((v__5f_bid_5f_val).f_v_Bid_v_amount > v_best_8) then (
            let v_best_13 : int = (v__5f_bid_5f_val).f_v_Bid_v_amount in
            let v_i_14 : int = (v_i_9 + (1)) in
            (ls_loop_6 (v_best_13) (v_i_14))
          ) else (
            let v_i_15 : int = (v_i_9 + (1)) in
            (ls_loop_6 (v_best_8) (v_i_15))
          )
        )
      )
      | None -> (
        let v_i_16 : int = (v_i_9 + (1)) in
        (ls_loop_6 (v_best_8) (v_i_16))
      )
    ) else (
      v_best_8
    )
  in
  (ls_loop_6 (v_best_4) (v_i_5))

let v_winningBidder  (v_bids:(S.seq (option v_Bid))) (v_key:R.string) (v_reserve:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == (-1)) \/ (((0) <= ls_result) /\ (ls_result < (S.length (v_bids)))))
      )) =
  let v_winner_21 : int = (-1) in
  let v_best_22 : int = v_reserve in
  let v_i_23 : int = (0) in
  let rec ls_loop_24 (v_winner_26:int) (v_best_27:int) (v_i_28:int)
    : Ghost int
        (requires (
          0 <= v_i_28 /\ ((v_winner_26 == (-1)) \/ (((0) <= v_winner_26) /\ (v_winner_26 < (S.length (v_bids)))))
        ))
        (ensures (fun ls_result ->
          ((ls_result == (-1)) \/ (((0) <= ls_result) /\ (ls_result < (S.length (v_bids)))))
        ))
        (decreases (R.nat_of_int ((S.length (v_bids)) - v_i_28))) =
    if (v_i_28 < (S.length (v_bids))) then (
      let v_bid_29 : (option v_Bid) = (S.index (v_bids) (v_i_28)) in
      match v_bid_29 with
      | Some v__5f_bid_5f_val -> (
        if (R.decide ((not (S.equal ((v__5f_bid_5f_val).f_v_Bid_v_key) (v_key))))) then (
          let v_i_31 : int = (v_i_28 + (1)) in
          (ls_loop_24 (v_winner_26) (v_best_27) (v_i_31))
        ) else (
          if ((v__5f_bid_5f_val).f_v_Bid_v_amount > v_best_27) then (
            let v_best_32 : int = (v__5f_bid_5f_val).f_v_Bid_v_amount in
            let v_winner_33 : int = v_i_28 in
            let v_i_34 : int = (v_i_28 + (1)) in
            (ls_loop_24 (v_winner_33) (v_best_32) (v_i_34))
          ) else (
            let v_i_35 : int = (v_i_28 + (1)) in
            (ls_loop_24 (v_winner_26) (v_best_27) (v_i_35))
          )
        )
      )
      | None -> (
        let v_i_36 : int = (v_i_28 + (1)) in
        (ls_loop_24 (v_winner_26) (v_best_27) (v_i_36))
      )
    ) else (
      v_winner_26
    )
  in
  (ls_loop_24 (v_winner_21) (v_best_22) (v_i_23))

let v_secondPrice  (v_bids:(S.seq (option v_Bid))) (v_key:R.string) (v_reserve:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_reserve)
      )) =
  let v_best_41 : int = v_reserve in
  let v_second_42 : int = v_reserve in
  let v_i_43 : int = (0) in
  let rec ls_loop_44 (v_best_46:int) (v_second_47:int) (v_i_48:int)
    : Ghost int
        (requires (
          0 <= v_i_48 /\ (v_second_47 >= v_reserve) /\ (v_best_46 >= v_second_47)
        ))
        (ensures (fun ls_result ->
          (ls_result >= v_reserve)
        ))
        (decreases (R.nat_of_int ((S.length (v_bids)) - v_i_48))) =
    if (v_i_48 < (S.length (v_bids))) then (
      let v_bid_49 : (option v_Bid) = (S.index (v_bids) (v_i_48)) in
      match v_bid_49 with
      | Some v__5f_bid_5f_val -> (
        if (R.decide ((not (S.equal ((v__5f_bid_5f_val).f_v_Bid_v_key) (v_key))))) then (
          let v_i_51 : int = (v_i_48 + (1)) in
          (ls_loop_44 (v_best_46) (v_second_47) (v_i_51))
        ) else (
          if ((v__5f_bid_5f_val).f_v_Bid_v_amount > v_best_46) then (
            let v_second_52 : int = v_best_46 in
            let v_best_53 : int = (v__5f_bid_5f_val).f_v_Bid_v_amount in
            let v_i_54 : int = (v_i_48 + (1)) in
            (ls_loop_44 (v_best_53) (v_second_52) (v_i_54))
          ) else (
            if ((v__5f_bid_5f_val).f_v_Bid_v_amount > v_second_47) then (
              let v_second_55 : int = (v__5f_bid_5f_val).f_v_Bid_v_amount in
              let v_i_56 : int = (v_i_48 + (1)) in
              (ls_loop_44 (v_best_46) (v_second_55) (v_i_56))
            ) else (
              let v_i_57 : int = (v_i_48 + (1)) in
              (ls_loop_44 (v_best_46) (v_second_47) (v_i_57))
            )
          )
        )
      )
      | None -> (
        let v_i_58 : int = (v_i_48 + (1)) in
        (ls_loop_44 (v_best_46) (v_second_47) (v_i_58))
      )
    ) else (
      v_second_47
    )
  in
  (ls_loop_44 (v_best_41) (v_second_42) (v_i_43))

let v_firstFunded  (v_bids:(S.seq (option v_Bid))) (v_key:R.string)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == (-1)) \/ (((0) <= ls_result) /\ (ls_result < (S.length (v_bids)))))
      )) =
  let v_i_62 : int = (0) in
  let rec ls_loop_63 (v_i_65:int)
    : Ghost int
        (requires (
          0 <= v_i_65 /\ ((0) <= v_i_65) /\ (v_i_65 <= (S.length (v_bids)))
        ))
        (ensures (fun ls_result ->
          ((ls_result == (-1)) \/ (((0) <= ls_result) /\ (ls_result < (S.length (v_bids)))))
        ))
        (decreases (R.nat_of_int ((S.length (v_bids)) - v_i_65))) =
    if (v_i_65 < (S.length (v_bids))) then (
      let v_bid_66 : (option v_Bid) = (S.index (v_bids) (v_i_65)) in
      match v_bid_66 with
      | Some v__5f_bid_5f_val -> (
        if ((R.decide ((not (S.equal ((v__5f_bid_5f_val).f_v_Bid_v_key) (v_key))))) || ((v__5f_bid_5f_val).f_v_Bid_v_amount <= (0))) then (
          let v_i_68 : int = (v_i_65 + (1)) in
          (ls_loop_63 (v_i_68))
        ) else (
          v_i_65
        )
      )
      | None -> (
        let v_i_69 : int = (v_i_65 + (1)) in
        (ls_loop_63 (v_i_69))
      )
    ) else (
      (-1)
    )
  in
  (ls_loop_63 (v_i_62))
