// Generated by lsc from bigintBits.ts

function shiftWide(x: int): int
  requires (x >= 0)
{
  (x * 1180591620717411303424)
}

lemma shiftWide_ensures(x: int)
  requires (x >= 0)
  ensures (shiftWide(x) >= x)
{
}

function low64(x: int): int
  requires (x >= 0)
{
  (x % 18446744073709551616)
}

lemma low64_ensures(x: int)
  requires (x >= 0)
  ensures (low64(x) < 18446744073709551616)
  ensures (low64(x) >= 0)
{
}
