/-
  Generated by lsc from binarySearch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «binarySearch.spec»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method binarySearch (arr : Array Int) (target : Int) return (res : Int)
  require sorted arr
  require arr.size > 0
  ensures res ≥ -1
  ensures res < arr.size
  ensures res ≥ 0 → arr[res.toNat]! = target
  ensures res = -1 → ∀ k : Int, 0 ≤ k → k < arr.size → arr[k.toNat]! ≠ target
  do
    let mut lo : Int := 0
    let mut hi : Int := arr.size - 1
    let mut result : Int := -1
    while lo ≤ hi
      invariant 0 ≤ lo
      invariant lo ≤ arr.size
      invariant -1 ≤ hi
      invariant hi < arr.size
      invariant ∀ k : Int, 0 ≤ k → k < lo → arr[k.toNat]! ≠ target
      invariant ∀ k : Int, hi < k → k < arr.size → arr[k.toNat]! ≠ target
      invariant result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target
      done_with result ≠ -1 ∨ ¬(lo ≤ hi)
      decreasing (hi - lo + 1).toNat
    do
      let mid := (lo + hi) / 2
      if arr[mid.toNat]! = target then
        result := mid
        break
      else if arr[mid.toNat]! < target then
        lo := mid + 1
      else
        hi := mid - 1
    return result
