// Generated by lsc. Program source: bitOr.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MbitOr_c5c7c56dc611

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_orZero  (v_x:int)
  : Ghost int
      (requires (
        (v_x >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result == v_x)
      )) =
  (R.bit_or (v_x) ((0)))

let v_zeroOr  (v_x:int)
  : Ghost int
      (requires (
        (v_x >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result == v_x)
      )) =
  (R.bit_or ((0)) (v_x))
