// Generated by lsc. Program source: clamp.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mclamp_d2060df04168

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_clamp  (v_x:int) (v_lo:int) (v_hi:int)
  : Ghost int
      (requires (
        (v_lo <= v_hi)
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_lo) /\ (ls_result <= v_hi)
      )) =
  let v_result_5 : int = v_x in
  if (v_result_5 < v_lo) then (
    let v_result_6 : int = v_lo in
    if (v_result_6 > v_hi) then (
      let v_result_7 : int = v_hi in
      v_result_7
    ) else (
      v_result_6
    )
  ) else (
    if (v_result_5 > v_hi) then (
      let v_result_8 : int = v_hi in
      v_result_8
    ) else (
      v_result_5
    )
  )
