// Generated by lsc. Program source: clampAll.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MclampAll_a01921702d55

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_clampElement  (v_x:int) (v_lo:int) (v_hi:int)
  : Ghost int
      (requires (
        (v_lo <= v_hi)
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_lo) /\ (ls_result <= v_hi)
      )) =
  let v_result_5 : int = v_x in
  if (v_result_5 < v_lo) then (
    let v_result_6 : int = v_lo in
    if (v_result_6 > v_hi) then (
      let v_result_7 : int = v_hi in
      v_result_7
    ) else (
      v_result_6
    )
  ) else (
    if (v_result_5 > v_hi) then (
      let v_result_8 : int = v_hi in
      v_result_8
    ) else (
      v_result_5
    )
  )

let v_clampAll  (v_arr:(S.seq int)) (v_lo:int) (v_hi:int)
  : Ghost (S.seq int)
      (requires (
        (v_lo <= v_hi)
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (R.map ((fun (v_x:int) ->
    let v__5f_t0_13 : int = (v_clampElement (v_x) (v_lo) (v_hi)) in
    v__5f_t0_13)) (v_arr))
