/-
  Generated by lsc from clampAll.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import LemmaScript

set_option velvet.semantics.termination "total"

method clampElement (x : Int) (lo : Int) (hi : Int) returns (res : Int)
  requires require_1: (lo ≤ hi : Prop)
  ensures ensures_1: (res ≥ lo : Prop)
  ensures ensures_2: (res ≤ hi : Prop)
  do
    let mut result : Int := x
    if result < lo then
      result := lo
    if result > hi then
      result := hi
    return result

method clampAll (arr : Array Int) (lo : Int) (hi : Int) returns (res : Array Int)
  requires require_1: (lo ≤ hi : Prop)
  do
    let _t1 ← arr.mapM (fun x => do
    let _t0 ← clampElement x lo hi
    return _t0)
    return _t1
