/-
  Generated by lsc from closureLift.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «closureLift.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method flush (result : Array Int) (pending : Array Int) return (res : FlushState)
  ensures (res.result).size ≥ result.size
  do
    let mut out : Array Int := result
    for _x_idx in [:pending.size]
      invariant _x_idx ≤ pending.size
      invariant out.size ≥ result.size
    do
      let x := pending[_x_idx]!
      out := out ++ #[x]
    return { result := out, pending := #[] }

method transform (items : Array (Array Int)) return (res : Array Int)
  do
    let mut result : Array Int := #[]
    let mut pending : Array Int := #[]
    for _batch_idx in [:items.size]
      invariant _batch_idx ≤ items.size
    do
      let batch := items[_batch_idx]!
      for _x_idx in [:batch.size]
        invariant _x_idx ≤ batch.size
      do
        let x := batch[_x_idx]!
        pending := pending ++ #[x]
      let _t0 ← flush result pending
      let s := _t0
      result := s.result
      pending := s.pending
    return result
