// Generated by lsc. Program source: compiler.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mcompiler_75bfbd17ff82

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Expression  =
| C_v_Expression_v_literal : int -> v_Expression
| C_v_Expression_v_variable : int -> v_Expression
| C_v_Expression_v_add : v_Expression -> v_Expression -> v_Expression
| C_v_Expression_v_multiply : v_Expression -> v_Expression -> v_Expression
| C_v_Expression_v_let : int -> v_Expression -> v_Expression -> v_Expression

type v_Environment  = (int -> GTot int)

type v_Continuation  = (int -> GTot int)

type v_Code  = (v_Environment -> v_Continuation -> GTot int)

let v_bind  (v_environment:v_Environment) (v_name:int) (v_value:int)
  : Ghost v_Environment
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_query:int). ((ls_result (v_query)) == (if (R.decide ((v_query == v_name))) then v_value else (v_environment (v_query)))))
      )) =
  (fun (v_query:int) ->
    (if (R.decide ((v_query == v_name))) then v_value else (v_environment (v_query))))

let rec v_evaluate  (v_expression:v_Expression) (v_environment:v_Environment)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (match v_expression with
  | C_v_Expression_v_literal v__5f_expression_5f_value -> v__5f_expression_5f_value
  | C_v_Expression_v_variable v__5f_expression_5f_name -> (v_environment (v__5f_expression_5f_name))
  | C_v_Expression_v_add v__5f_expression_5f_left v__5f_expression_5f_right -> ((v_evaluate (v__5f_expression_5f_left) (v_environment)) + (v_evaluate (v__5f_expression_5f_right) (v_environment)))
  | C_v_Expression_v_multiply v__5f_expression_5f_left v__5f_expression_5f_right -> ((v_evaluate (v__5f_expression_5f_left) (v_environment)) * (v_evaluate (v__5f_expression_5f_right) (v_environment)))
  | C_v_Expression_v_let v__5f_expression_5f_name v__5f_expression_5f_value v__5f_expression_5f_body -> (v_evaluate (v__5f_expression_5f_body) ((v_bind (v_environment) (v__5f_expression_5f_name) ((v_evaluate (v__5f_expression_5f_value) (v_environment)))))))

// Callers use the checked compiler contract without unfolding generated code.
[@@"opaque_to_smt"]
let rec v_compile  (v_expression:v_Expression)
  : Ghost v_Code
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_environment:v_Environment). (forall (v_continuation:v_Continuation). ((ls_result (v_environment) (v_continuation)) == (v_continuation ((v_evaluate (v_expression) (v_environment)))))))
      )) =
  (match v_expression with
  | C_v_Expression_v_literal v__5f_expression_5f_value -> (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_continuation ((match v_expression with | C_v_Expression_v_literal ls_field -> ls_field))))
  | C_v_Expression_v_variable v__5f_expression_5f_name -> (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_continuation ((v_environment ((match v_expression with | C_v_Expression_v_variable ls_field -> ls_field | C_v_Expression_v_let ls_field _ _ -> ls_field))))))
  | C_v_Expression_v_add v__5f_expression_5f_left v__5f_expression_5f_right -> (if ((R.decide ((match v__5f_expression_5f_left with | C_v_Expression_v_literal _ -> true | _ -> false))) && (R.decide ((match v__5f_expression_5f_right with | C_v_Expression_v_literal _ -> true | _ -> false)))) then (let v_folded_29 = ((match v__5f_expression_5f_left with | C_v_Expression_v_literal ls_field -> ls_field) + (match v__5f_expression_5f_right with | C_v_Expression_v_literal ls_field -> ls_field)) in
  (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_continuation (v_folded_29)))) else (let v_left_32 = (v_compile (v__5f_expression_5f_left)) in
  (let v_right_33 = (v_compile (v__5f_expression_5f_right)) in
  (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_left_32 (v_environment) ((fun (v_x:int) ->
      (v_right_33 (v_environment) ((fun (v_y:int) ->
        (v_continuation ((v_x + v_y)))))))))))))
  | C_v_Expression_v_multiply v__5f_expression_5f_left v__5f_expression_5f_right -> (if ((R.decide ((match v__5f_expression_5f_right with | C_v_Expression_v_literal _ -> true | _ -> false))) && (R.decide (((match v__5f_expression_5f_right with | C_v_Expression_v_literal ls_field -> ls_field) == (0))))) then (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_continuation ((0)))) else (if ((R.decide ((match v__5f_expression_5f_left with | C_v_Expression_v_literal _ -> true | _ -> false))) && (R.decide ((match v__5f_expression_5f_right with | C_v_Expression_v_literal _ -> true | _ -> false)))) then (let v_folded_42 = ((match v__5f_expression_5f_left with | C_v_Expression_v_literal ls_field -> ls_field) * (match v__5f_expression_5f_right with | C_v_Expression_v_literal ls_field -> ls_field)) in
  (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_continuation (v_folded_42)))) else (let v_left_45 = (v_compile (v__5f_expression_5f_left)) in
  (let v_right_46 = (v_compile (v__5f_expression_5f_right)) in
  (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_left_45 (v_environment) ((fun (v_x:int) ->
      (v_right_46 (v_environment) ((fun (v_y:int) ->
        (v_continuation ((v_x * v_y))))))))))))))
  | C_v_Expression_v_let v__5f_expression_5f_name v__5f_expression_5f_value v__5f_expression_5f_body -> (let v_value_54 = (v_compile (v__5f_expression_5f_value)) in
  (let v_body_55 = (v_compile (v__5f_expression_5f_body)) in
  (fun (v_environment:v_Environment) (v_continuation:v_Continuation) ->
    (v_value_54 (v_environment) ((fun (v_x:int) ->
      (v_body_55 ((v_bind (v_environment) ((match v_expression with | C_v_Expression_v_variable ls_field -> ls_field | C_v_Expression_v_let ls_field _ _ -> ls_field)) (v_x))) (v_continuation)))))))))

let v_run  (v_expression:v_Expression) (v_environment:v_Environment)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (v_evaluate (v_expression) (v_environment)))
      )) =
  (let v__5f_callee_62 = (v_compile (v_expression)) in
  (v__5f_callee_62 (v_environment) ((fun (v_value:int) ->
    v_value))))

// Normalize the concrete syntax tree separately from the recursive compiler.
unfold let shadowing_expression =
  C_v_Expression_v_let 0
    (C_v_Expression_v_add (C_v_Expression_v_variable 0) (C_v_Expression_v_literal 1))
    (C_v_Expression_v_add
      (C_v_Expression_v_let 0
        (C_v_Expression_v_multiply (C_v_Expression_v_variable 0) (C_v_Expression_v_literal 2))
        (C_v_Expression_v_variable 0))
      (C_v_Expression_v_variable 0))

let shadowing_value (x:int) : Lemma
  (v_evaluate shadowing_expression (fun name -> if R.decide (name == 0) then x else 0) == 3 * (x + 1))
  [SMTPat (v_evaluate shadowing_expression (fun name -> if R.decide (name == 0) then x else 0))] =
  assert_norm (v_evaluate shadowing_expression (fun name -> if R.decide (name == 0) then x else 0) == 3 * (x + 1))

let v_shadowingDemo  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (((30) * (v_x + (1))) + (1)))
      )) =
  let v_program_66 : v_Expression = (C_v_Expression_v_let ((0)) ((C_v_Expression_v_add ((C_v_Expression_v_variable ((0)))) ((C_v_Expression_v_literal ((1)))))) ((C_v_Expression_v_add ((C_v_Expression_v_let ((0)) ((C_v_Expression_v_multiply ((C_v_Expression_v_variable ((0)))) ((C_v_Expression_v_literal ((2)))))) ((C_v_Expression_v_variable ((0)))))) ((C_v_Expression_v_variable ((0))))))) in
  let v__5f_t0_67 : (v_Environment -> v_Continuation -> GTot int) = (v_compile (v_program_66)) in
  let v_code_68 : v_Code = v__5f_t0_67 in
  let v_environment_69 : (int -> GTot int) = (fun (v_name:int) ->
    (if (R.decide ((v_name == (0)))) then v_x else (0))) in
  let v_answer_71 : int = (v_code_68 (v_environment_69) ((fun (v_value:int) ->
    v_value))) in
  let v_transformed_73 : int = (v_code_68 (v_environment_69) ((fun (v_value:int) ->
    (((10) * v_value) + (1))))) in
  assert ((v_transformed_73 == (((10) * v_answer_71) + (1))));
  v_transformed_73
