// Generated by lsc from compiler.ts

// Avoid nonlinear solver search on the concrete shadowing calculation.
module {:disableNonlinearArithmetic} Compiler {

datatype Expression = literal(value_literal: int) | variable(name: int) | add(left: Expression, right: Expression) | multiply(left: Expression, right: Expression) | let(name: int, value_let: Expression, body: Expression)

type Environment = (int) -> int

type Continuation = (int) -> int

type Code = (Environment, Continuation) -> int

function bind(environment: Environment, name: int, value: int): Environment
{
  (query: int) => (if (query == name) then value else environment(query))
}

lemma bind_ensures(environment: Environment, name: int, value: int)
  ensures forall query: int :: ((var i_callee := bind(environment, name, value); i_callee(query)) == (if (query == name) then value else environment(query)))
{
}

function evaluate(expression: Expression, environment: Environment): int
{
  match expression {
    case literal(i_expression_value) =>
      i_expression_value
    case variable(i_expression_name) =>
      environment(i_expression_name)
    case add(i_expression_left, i_expression_right) =>
      (evaluate(i_expression_left, environment) + evaluate(i_expression_right, environment))
    case multiply(i_expression_left, i_expression_right) =>
      (evaluate(i_expression_left, environment) * evaluate(i_expression_right, environment))
    case let(i_expression_name, i_expression_value, i_expression_body) =>
      evaluate(i_expression_body, bind(environment, i_expression_name, evaluate(i_expression_value, environment)))
  }
}

opaque
function compile(expression: Expression): Code
{
  match expression {
    case literal(i_expression_value) =>
      (environment: Environment, continuation: Continuation) => continuation(expression.value_literal)
    case variable(i_expression_name) =>
      (environment: Environment, continuation: Continuation) => continuation(environment(expression.name))
    case add(i_expression_left, i_expression_right) =>
      if (i_expression_left.literal? && i_expression_right.literal?) then
        var folded := (i_expression_left.value_literal + i_expression_right.value_literal);
        (environment: Environment, continuation: Continuation) => continuation(folded)
      else
        var left := compile(i_expression_left);
        var right := compile(i_expression_right);
        (environment: Environment, continuation: Continuation) => left(environment, (x: int) => right(environment, (y: int) => continuation((x + y))))
    case multiply(i_expression_left, i_expression_right) =>
      if (i_expression_right.literal? && (i_expression_right.value_literal == 0)) then
        (environment: Environment, continuation: Continuation) => continuation(0)
      else
        if (i_expression_left.literal? && i_expression_right.literal?) then
          var folded := (i_expression_left.value_literal * i_expression_right.value_literal);
          (environment: Environment, continuation: Continuation) => continuation(folded)
        else
          var left := compile(i_expression_left);
          var right := compile(i_expression_right);
          (environment: Environment, continuation: Continuation) => left(environment, (x: int) => right(environment, (y: int) => continuation((x * y))))
    case let(i_expression_name, i_expression_value, i_expression_body) =>
      var value := compile(i_expression_value);
      var body := compile(i_expression_body);
      (environment: Environment, continuation: Continuation) => value(environment, (x: int) => body(bind(environment, expression.name, x), continuation))
  }
}

lemma compile_ensures(expression: Expression)
  ensures forall environment: Environment, continuation: Continuation :: ((var i_callee := compile(expression); i_callee(environment, continuation)) == continuation(evaluate(expression, environment)))
{
  reveal compile();
}

function run(expression: Expression, environment: Environment): int
{
  var i_callee := compile(expression);
  i_callee(environment, (value: int) => value)
}

lemma run_ensures(expression: Expression, environment: Environment)
  ensures (run(expression, environment) == evaluate(expression, environment))
{
  compile_ensures(expression);
}

// Normalize the concrete shadowing demo separately from compiler correctness.
lemma shadowing_value(x: int)
  ensures evaluate(let(0, add(variable(0), literal(1)), add(let(0, multiply(variable(0), literal(2)), variable(0)), variable(0))),
    (name: int) => if name == 0 then x else 0) == 3 * (x + 1)
{
}

method shadowingDemo(x: int) returns (res: int)
  ensures (res == ((30 * (x + 1)) + 1))
{
  var program := let(0, add(variable(0), literal(1)), add(let(0, multiply(variable(0), literal(2)), variable(0)), variable(0)));
  compile_ensures(program);
  var i_t0 := compile(program);
  var code := i_t0;
  var environment := (name: int) => (if (name == 0) then x else 0);
  shadowing_value(x);
  assert evaluate(program, environment) == 3 * (x + 1);
  var answer := code(environment, (value: int) => value);
  assert answer == evaluate(program, environment);
  var transformed := code(environment, (value: int) => ((10 * value) + 1));
  assert transformed == 10 * evaluate(program, environment) + 1;
  assert (transformed == ((10 * answer) + 1));
  return transformed;
}

}
