// Generated by lsc. Program source: ctorName.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MctorName_d3a3dfd5c0d6

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_CallKind  =
| C_v_CallKind_v_spec_2d_pure : int -> v_CallKind
| C_v_CallKind_v_plain : v_CallKind

let v_depthOf  (v_k:v_CallKind)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  (match v_k with
  | C_v_CallKind_v_spec_2d_pure v__5f_k_5f_depth -> (if (v__5f_k_5f_depth >= (0)) then v__5f_k_5f_depth else (0))
  | C_v_CallKind_v_plain -> (0))

let v_specPure  (v_depth:int)
  : Ghost v_CallKind
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (C_v_CallKind_v_spec_2d_pure (v_depth))

let v_plain  ()
  : Ghost v_CallKind
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  C_v_CallKind_v_plain
