// Generated by lsc from ctorName.ts

datatype CallKind = spec_pure(depth: int) | plain

function depthOf(k: CallKind): int
{
  match k {
    case spec_pure(i_k_depth) =>
      if (i_k_depth >= 0) then
        i_k_depth
      else
        0
    case plain =>
      0
  }
}

lemma depthOf_ensures(k: CallKind)
  ensures (depthOf(k) >= 0)
{
}

function specPure(depth: int): CallKind
{
  spec_pure(depth)
}

function plain(): CallKind
{
  CallKind.plain
}
