/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive CallKind where
  | «spec-pure» (depth : Int) : CallKind
  | plain : CallKind
deriving Repr, Inhabited

namespace Pure

def depthOf (k : CallKind) : Int :=
  match k with
  | .«spec-pure» _k_depth =>
    if _k_depth ≥ 0 then
      _k_depth
    else
      0
  | .plain =>
    0

def specPure (depth : Int) : CallKind :=
  CallKind.«spec-pure» depth

def plain  : CallKind :=
  CallKind.plain

end Pure
