// Generated by lsc. Program source: declareTypeEnum.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MdeclareTypeEnum_5b1f6aa23f25

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Role  =
| C_v_Role_v_user : v_Role
| C_v_Role_v_assistant : v_Role
| C_v_Role_v_toolResult : v_Role

type v_Msg  = {
  f_v_Msg_v_role: v_Role;
}

let v_roleTag  (v_m:v_Msg)
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        true
      )) =
  (let v_role_2 = (v_m).f_v_Msg_v_role in
  (match v_role_2 with
  | C_v_Role_v_user -> (S.build (S.empty) (117))
  | C_v_Role_v_assistant -> (S.build (S.empty) (97))
  | C_v_Role_v_toolResult -> (S.build (S.empty) (116))))

let v_isToolResult  (v_m:v_Msg)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (R.decide (((v_m).f_v_Msg_v_role == C_v_Role_v_toolResult))))
      )) =
  (R.decide (((v_m).f_v_Msg_v_role == C_v_Role_v_toolResult)))
