// Generated by lsc from declareTypeEnum.ts

datatype Role = user | assistant | toolResult

datatype Msg = Msg(role: Role)

function roleTag(m: Msg): string
{
  var role := m.role;
  match role {
    case user =>
      "u"
    case assistant =>
      "a"
    case toolResult =>
      "t"
  }
}

lemma roleTag_ensures(m: Msg)
  ensures true
{
}

function isToolResult(m: Msg): bool
{
  m.role.toolResult?
}

lemma isToolResult_ensures(m: Msg)
  ensures (isToolResult(m) == m.role.toolResult?)
{
}
