// Generated by lsc from declareTypeShadow.ts

datatype RawMsg = RawMsg(kind: string)

function countMsgs(msgs: seq<RawMsg>): int
{
  |msgs|
}

lemma countMsgs_ensures(msgs: seq<RawMsg>)
  ensures (countMsgs(msgs) >= 0)
{
}
