// Generated by lsc. Program source: discriminantTrailing.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MdiscriminantTrailing_acc21329a733

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Shape  =
| C_v_Shape_v_circle : v_Shape
| C_v_Shape_v_square : v_Shape
| C_v_Shape_v_triangle : v_Shape

let v_classify  (v_s:v_Shape)
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (match v_s with
  | C_v_Shape_v_circle -> (S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (114))) (111))) (117))) (110))) (100))
  | C_v_Shape_v_square -> (S.build ((S.build ((S.build ((S.build (S.empty) (98))) (111))) (120))) (121))
  | C_v_Shape_v_triangle -> (S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (111))) (116))) (104))) (101))) (114)))

let v_tally  (v_s:v_Shape)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (10))
      )) =
  let v_n_3 : int = (0) in
  match v_s with
  | C_v_Shape_v_circle -> (
    let v_n_4 : int = (1) in
    (v_n_4 + (10))
  )
  | C_v_Shape_v_square -> (
    let v_n_5 : int = (2) in
    (v_n_5 + (10))
  )
  | C_v_Shape_v_triangle -> (
    (v_n_3 + (10))
  )
