// Generated by lsc from discriminantTrailing.ts

datatype Shape = circle | square | triangle

function classify(s: Shape): string
{
  match s {
    case circle =>
      "round"
    case square =>
      "boxy"
    case triangle =>
      "other"
  }
}

method tally(s: Shape) returns (res: int)
  ensures (res >= 10)
{
  var n := 0;
  match s {
    case circle =>
      n := 1;
    case square =>
      n := 2;
    case triangle =>

  }
  return (n + 10);
}
