// Generated by lsc. Program source: division.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mdivision_040fb6afe0b8

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_threeHalves  ()
  : Ghost real
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result *. (FStar.Real.of_int ((2)))) == (FStar.Real.of_int ((3)))) /\ (ls_result == (1.5R))
      )) =
  ((FStar.Real.of_int ((3))) /. (FStar.Real.of_int ((2))))

let v_divide  (v_a:int) (v_b:int)
  : Ghost real
      (requires (
        (v_b =!= (0))
      ))
      (ensures (fun ls_result ->
        ((ls_result *. (FStar.Real.of_int (v_b))) == (FStar.Real.of_int (v_a)))
      )) =
  ((FStar.Real.of_int (v_a)) /. (FStar.Real.of_int (v_b)))

let v_floorDivision  ()
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == true)
      )) =
  ((R.decide (((R.floor_div ((7)) ((2))) == (3)))) && (R.decide (((R.floor_div ((-7)) ((2))) == (-4)))))
