// Generated by lsc. Program source: dual.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mdual_8fc3c6e1a61c

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Predicate (v_A:Type) = (v_A -> GTot bool)

type v_Account  = {
  f_v_Account_v_member: bool;
  f_v_Account_v_suspended: bool;
}

type v_Request  = {
  f_v_Request_v_account: v_Account;
}

let v_dual (#v_A:Type) (#v_B:Type) (#v_R:Type) (v_body:(v_A -> v_B -> GTot v_R))
  : Ghost (v_B -> GTot (v_A -> GTot v_R))
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_that:v_B). (forall (v_self:v_A). ((let v__5f_callee_4 = (ls_result (v_that)) in
(v__5f_callee_4 (v_self))) == (v_body (v_self) (v_that)))))
      )) =
  (fun (v_that:v_B) ->
    (fun (v_self:v_A) ->
      (v_body (v_self) (v_that))))

let v_denyOverride (#v_A:Type) (v_self:(v_Predicate v_A)) (v_denied:(v_Predicate v_A))
  : Ghost (v_Predicate v_A)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_value:v_A). ((ls_result (v_value)) == ((v_self (v_value)) && (not (v_denied (v_value))))))
      )) =
  (fun (v_value:v_A) ->
    ((v_self (v_value)) && (not (v_denied (v_value)))))

let v_mapInput (#v_A:Type) (#v_B:Type) (v_self:(v_Predicate v_A)) (v_project:(v_B -> GTot v_A))
  : Ghost (v_Predicate v_B)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_value:v_B). ((ls_result (v_value)) == (v_self ((v_project (v_value))))))
      )) =
  (fun (v_value:v_B) ->
    (v_self ((v_project (v_value)))))

let v_curriedPolicy (#v_A:Type) (#v_B:Type) (v_eligible:(v_Predicate v_A)) (v_denied:(v_Predicate v_A)) (v_project:(v_B -> GTot v_A))
  : Ghost (v_Predicate v_B)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (forall (v_value:v_B). ((ls_result (v_value)) == ((v_eligible ((v_project (v_value)))) && (not (v_denied ((v_project (v_value))))))))
      )) =
  (let v_denyLast_22 = (v_dual ((fun (v_self:(v_Predicate v_A)) (v_denied:(v_Predicate v_A)) ->
    (v_denyOverride (v_self) (v_denied))))) in
  (let v_mapLast_25 = (v_dual ((fun (v_self:(v_Predicate v_A)) (v_project:(v_B -> GTot v_A)) ->
    (v_mapInput (v_self) (v_project))))) in
  (let v_withDenial_28 = (v_denyLast_22 (v_denied)) in
  (let v_onInput_29 = (v_mapLast_25 (v_project)) in
  (v_onInput_29 ((v_withDenial_28 (v_eligible))))))))

let v_callingFormsAgree (#v_A:Type) (#v_B:Type) (v_eligible:(v_Predicate v_A)) (v_denied:(v_Predicate v_A)) (v_project:(v_B -> GTot v_A)) (v_value:v_B)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ls_result
      )) =
  (let v_direct_35 = (v_mapInput ((v_denyOverride (v_eligible) (v_denied))) (v_project)) in
  (let v_curried_36 = (v_curriedPolicy (v_eligible) (v_denied) (v_project)) in
  (R.decide (((v_direct_35 (v_value)) == (v_curried_36 (v_value)))))))

let v_canEnter  (v_request:v_Request)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (((v_request).f_v_Request_v_account).f_v_Account_v_member && (not ((v_request).f_v_Request_v_account).f_v_Account_v_suspended)))
      )) =
  (let v__5f_callee_39 = (v_curriedPolicy ((fun (v_account:v_Account) ->
    (v_account).f_v_Account_v_member)) ((fun (v_account:v_Account) ->
    (v_account).f_v_Account_v_suspended)) ((fun (v_request:v_Request) ->
    (v_request).f_v_Request_v_account))) in
  (v__5f_callee_39 (v_request)))
