// Generated by lsc. Program source: enumLiteralPositions.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MenumLiteralPositions_f1ddf57781ce

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Lang  =
| C_v_Lang_v_en : v_Lang
| C_v_Lang_v_ru : v_Lang

type v_Color  =
| C_v_Color_v_red : v_Color
| C_v_Color_v_blue : v_Color

type v_Doc  = {
  f_v_Doc_v_lang: v_Lang;
  f_v_Doc_v_n: int;
}

let v_idLang  (v_l:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_l)
      )) =
  v_l

let v_flipTernary  (v_lang:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result =!= v_lang)
      )) =
  (if (R.decide ((v_lang == C_v_Lang_v_en))) then C_v_Lang_v_ru else C_v_Lang_v_en)

let v_flipIf  (v_lang:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result =!= v_lang)
      )) =
  (if (R.decide ((v_lang == C_v_Lang_v_en))) then C_v_Lang_v_ru else C_v_Lang_v_en)

let v_flipMixed  (v_lang:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == v_lang) \/ (ls_result == C_v_Lang_v_en))
      )) =
  (if (R.decide ((v_lang == C_v_Lang_v_ru))) then v_lang else C_v_Lang_v_en)

let v_flipLet  (v_lang:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result =!= v_lang)
      )) =
  (let v_flipped_10 = (if (R.decide ((v_lang == C_v_Lang_v_en))) then C_v_Lang_v_ru else C_v_Lang_v_en) in
  v_flipped_10)

let v_flipArg  (v_lang:v_Lang)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result =!= v_lang)
      )) =
  (v_idLang ((if (R.decide ((v_lang == C_v_Lang_v_en))) then C_v_Lang_v_ru else C_v_Lang_v_en)))

let v_flipDoc  (v_lang:v_Lang)
  : Ghost v_Doc
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result).f_v_Doc_v_lang =!= v_lang)
      )) =
  { f_v_Doc_v_lang = (if (R.decide ((v_lang == C_v_Lang_v_en))) then C_v_Lang_v_ru else C_v_Lang_v_en); f_v_Doc_v_n = (0) }

let v_orDefault  (v_lang:(option v_Lang)) (v_toRu:bool)
  : Ghost v_Lang
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (match v_lang with
| Some v__5f_lang_5f_val -> (R.decide ((ls_result == v__5f_lang_5f_val)))
| None -> true)
      )) =
  (match v_lang with
  | Some v__5f_oc0_5f_val -> v__5f_oc0_5f_val
  | None -> (if v_toRu then C_v_Lang_v_ru else C_v_Lang_v_en))

let v_pick  (v_n:int)
  : Ghost (option v_Color)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((v_n == (1)) ==> (match ls_result with
| Some v__5f_value -> (R.decide ((v__5f_value == C_v_Color_v_red)))
| None -> false)) /\ ((v_n =!= (1)) /\ (v_n =!= (2)) ==> (match ls_result with
| Some v__5f_ -> false
| None -> true))
      )) =
  (if (R.decide ((v_n == (1)))) then (Some (C_v_Color_v_red)) else (if (R.decide ((v_n == (2)))) then (Some (C_v_Color_v_blue)) else None))

let v_pickNull  (v_n:int)
  : Ghost (option v_Color)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((v_n == (1)) ==> (match ls_result with
| Some v__5f_value -> (R.decide ((v__5f_value == C_v_Color_v_red)))
| None -> false))
      )) =
  (if (R.decide ((v_n == (1)))) then (Some (C_v_Color_v_red)) else None)

let v_pickLet  (v_n:int)
  : Ghost (option v_Color)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((v_n == (1)) ==> (match ls_result with
| Some v__5f_value -> (R.decide ((v__5f_value == C_v_Color_v_red)))
| None -> false))
      )) =
  (let v_c_31 = (if (R.decide ((v_n == (1)))) then (Some (C_v_Color_v_red)) else None) in
  v_c_31)

let v_nameOf  (v_n:int)
  : Ghost R.string
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((v_n == (1)) ==> (S.equal (ls_result) ((S.build ((S.build ((S.build (S.empty) (114))) (101))) (100)))))
      )) =
  (let v_c_34 = (v_pick (v_n)) in
  (match v_c_34 with
  | Some v__5f_c_5f_val -> (if (R.decide ((v__5f_c_5f_val == C_v_Color_v_red))) then (S.build ((S.build ((S.build (S.empty) (114))) (101))) (100)) else (S.build ((S.build ((S.build ((S.build (S.empty) (98))) (108))) (117))) (101)))
  | None -> (S.build ((S.build ((S.build ((S.build (S.empty) (110))) (111))) (110))) (101))))
