/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Kind where
  | keep : Kind
  | skip : Kind
  | stop : Kind
deriving Repr, Inhabited, DecidableEq

structure Item where
  kind : Kind
deriving Repr, Inhabited, DecidableEq
