/-
  Generated by lsc from forContinue.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «forContinue.types»

set_option velvet.semantics.termination "total"

method countOdds (xs : Array Int) returns (res : Int)
  ensures ensures_1: (res ≤ xs.size : Prop)
  do
    let mut n : Int := 0
    let mut i : Nat := 0
    while i < xs.size
      invariant invariant_1: (i ≤ xs.size : Prop)
      invariant invariant_2: (n ≤ i : Prop)
      decreasing xs.size - i
    do
      if Int.tmod xs[i]! 2 = 0 then
        i := i + 1
      else
        n := n + 1
        i := i + 1
    return n

method copyNonzero (xs : Array Int) returns (res : Array Int)
  ensures ensures_1: (res.size ≤ xs.size : Prop)
  do
    let mut out : Array Int := #[]
    let mut i : Nat := 0
    while i < xs.size
      invariant invariant_1: (i ≤ xs.size : Prop)
      invariant invariant_2: (out.size ≤ i : Prop)
      decreasing xs.size - i
    do
      let v := xs[i]!
      if v = 0 then
        i := i + 1
      else if v < 0 then
        i := i + 1
      else
        out := Array.push out v
        i := i + 1
    return out

method countPositivesNonNested (grid : Array (Array Int)) returns (res : Int)
  ensures ensures_1: (res ≥ 0 : Prop)
  do
    let mut total : Int := 0
    let mut i : Nat := 0
    while i < grid.size
      invariant invariant_1: (i ≤ grid.size : Prop)
      invariant invariant_2: (total ≥ 0 : Prop)
      decreasing grid.size - i
    do
      let mut row : Array Int := grid[i]!
      let _rangeStop0 : Nat := row.size
      for _x_idx in [:_rangeStop0]
        invariant invariant_3: (_x_idx ≤ row.size : Prop)
        invariant invariant_4: (total ≥ 0 : Prop)
        done_with (let _x_idx : Nat := _rangeStop0; (_x_idx ≤ row.size : Prop) ∧ (total ≥ 0 : Prop))
      do
        let _x_idx : Nat := _x_idx
        let x := row[_x_idx]!
        if !(x ≤ 0) then
          total := total + 1
      i := i + 1
    return total

method lastPresent (xs : Array (Option Int)) returns (res : Option Int)
  do
    let mut cur : Option Int := none
    let _rangeStop0 : Nat := xs.size
    for _x_idx in [:_rangeStop0]
      invariant invariant_1: (_x_idx ≤ xs.size : Prop)
      done_with (let _x_idx : Nat := _rangeStop0; (_x_idx ≤ xs.size : Prop))
    do
      let _x_idx : Nat := _x_idx
      let x := xs[_x_idx]!
      if h_x : (x).isSome = true then
        let _x_val := (x).get h_x
        cur := some _x_val
      else
        pure ()
    return cur

method lastBeforeGap (xs : Array (Option Int)) returns (res : Option Int)
  do
    let mut cur : Option Int := none
    let _rangeStop0 : Nat := xs.size
    for _x_idx in [:_rangeStop0]
      invariant invariant_1: (_x_idx ≤ xs.size : Prop)
      done_with (let _x_idx : Nat := _rangeStop0; (_x_idx ≤ xs.size : Prop))
    do
      let _x_idx : Nat := _x_idx
      let x := xs[_x_idx]!
      if h_x : (x).isSome = true then
        let _x_val := (x).get h_x
        cur := some _x_val
      else
        break
    return cur

method countKeep (items : Array Item) returns (res : Int)
  ensures ensures_1: (0 ≤ res : Prop)
  ensures ensures_2: (res ≤ items.size : Prop)
  do
    let mut count : Int := 0
    let mut i : Nat := 0
    let mut _loopRet : Int := count
    while i < items.size
      invariant invariant_1: (0 ≤ i : Prop)
      invariant invariant_2: (i ≤ items.size : Prop)
      invariant invariant_3: (0 ≤ count : Prop)
      invariant invariant_4: (count ≤ i : Prop)
      invariant invariant_5: (0 ≤ _loopRet : Prop)
      invariant invariant_6: (_loopRet ≤ items.size : Prop)
      decreasing items.size - i
      done_with (true : Prop)
    do
      if (items[i]!).kind = Kind.skip then
        i := i + 1
        continue
      else if (items[i]!).kind = Kind.stop then
        _loopRet := count
        break
      count := count + 1
      i := i + 1
    return _loopRet
