// Generated by lsc. Program source: fstarIteration.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MfstarIteration_435f07dc11c1

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let rec v_repeat  (v_n:int) (v_f:(int -> GTot int)) (v_x:int)
  : Ghost int
      (requires (
        (v_n >= (0)) /\ (forall (v_y:int). ((v_f (v_y)) >= v_y))
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_x)
      ))
      (decreases v_n) =
  (if (R.decide ((v_n == (0)))) then v_x else (v_repeat ((v_n - (1))) (v_f) ((v_f (v_x)))))

let v_iterate  (v_n:int) (v_f:(int -> GTot int))
  : Ghost (int -> GTot int)
      (requires (
        (v_n >= (0)) /\ (forall (v_y:int). ((v_f (v_y)) >= v_y))
      ))
      (ensures (fun ls_result ->
        (forall (v_x:int). ((ls_result (v_x)) >= v_x))
      )) =
  (fun (v_x:int) ->
    (v_repeat (v_n) (v_f) (v_x)))

let v_incrementThreeTimes  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_x)
      )) =
  ((v_iterate ((3)) ((fun (v_y:int) ->
    (v_y + (1))))) (v_x))
