// Generated by lsc from genericExtern.ts

function {:axiom} step<S, A>(s: S, a: A): S

function applyTwice<S(==), A>(s: S, a: A): S
{
  var s1 := step(s, a);
  step(s1, a)
}

lemma applyTwice_ensures<S, A>(s: S, a: A)
  ensures (applyTwice(s, a) == step(step(s, a), a))
{
}
