/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import Velvet.Syntax
import Velvet.Std

namespace Pure

def doubleAll (arr : Array Int) : Array Int :=
  arr.map (fun x => x * 2)

def positives (arr : Array Int) : Array Int :=
  arr.filter (fun x => x > 0)

def allPositive (arr : Array Int) : Bool :=
  arr.all (fun x => x > 0)

def hasNegative (arr : Array Int) : Bool :=
  arr.any (fun x => x < 0)

end Pure
