/-
  Generated by lsc from hof.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «hof.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method doubleAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.doubleAll arr

method positives (arr : Array Int) return (res : Array Int)
  do
    return Pure.positives arr

method allPositive (arr : Array Int) return (res : Bool)
  do
    return Pure.allPositive arr

method hasNegative (arr : Array Int) return (res : Bool)
  do
    return Pure.hasNegative arr
