// Generated by lsc from hof.ts
import Std.Collections.Seq

function doubleAll(arr: seq<int>): seq<int>
{
  Seq.Map((x: int) => (x * 2), arr)
}

lemma doubleAll_ensures(arr: seq<int>)
  ensures (|doubleAll(arr)| == |arr|)
{
}

function positives(arr: seq<int>): seq<int>
{
  Seq.Filter((x: int) => (x > 0), arr)
}

function allPositive(arr: seq<int>): bool
{
  Seq.All(arr, (x: int) => (x > 0))
}

function hasNegative(arr: seq<int>): bool
{
  (exists x :: x in arr && (x < 0))
}
