/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isEven (x : Int) : Bool :=
  x % 2 = 0

def sameParity (x : Int) (y : Int) : Bool :=
  x % 2 = y % 2

end Pure
