/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isEven (x : Int) : Bool :=
  Int.tmod x 2 = 0

def sameParity (x : Int) (y : Int) : Bool :=
  Int.tmod x 2 = Int.tmod y 2

end Pure
