// Generated by lsc. Program source: impureExtern.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MimpureExtern_6631a4e6ec71

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

// Trusted source declaration: impure extern.
assume val v_rollDie : (ls_trace:list int) -> Ghost int (requires (True)) (ensures (fun ls_result -> (((1) <= ls_result) /\ (ls_result <= (6)))))

let v_sumTwoRolls  (ls_trace:list int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((2) <= ls_result) /\ (ls_result <= (12))
      )) =
  let v__5f_t0_3 : int = (v_rollDie ((4 :: ls_trace))) in
  let v_a_5 : int = v__5f_t0_3 in
  let v__5f_t1_6 : int = (v_rollDie ((7 :: ls_trace))) in
  let v_b_8 : int = v__5f_t1_6 in
  (v_a_5 + v_b_8)
