// Generated by lsc from impureExtern.ts

method {:axiom} rollDie() returns (res: int)
  ensures ((1 <= res) && (res <= 6))

method sumTwoRolls() returns (res: int)
  ensures (2 <= res)
  ensures (res <= 12)
{
  var i_t0 := rollDie();
  var a := i_t0;
  var i_t1 := rollDie();
  var b := i_t1;
  return (a + b);
}
