// Generated by lsc. Program source: isSorted.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MisSorted_7d1dd761cd03

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_isSorted  (v_arr:(S.seq int))
  : Ghost bool
      (requires (
        ((S.length (v_arr)) > (0))
      ))
      (ensures (fun ls_result ->
        ((ls_result == true) ==> (forall (v_k:nat). (((v_k + (1)) < (S.length (v_arr))) ==> ((S.index (v_arr) (v_k)) <= (S.index (v_arr) ((v_k + (1)))))))) /\ ((ls_result == false) ==> (exists (v_k:nat). (((v_k + (1)) < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) > (S.index (v_arr) ((v_k + (1))))))))
      )) =
  let v_result_5 : bool = true in
  let v_i_6 : int = (0) in
  let rec ls_loop_7 (v_result_9:bool) (v_i_10:int)
    : Ghost bool
        (requires (
          0 <= v_i_10 /\ (v_i_10 < (S.length (v_arr))) /\ ((v_result_9 == true) ==> (forall (v_k:nat). ((v_k < v_i_10) ==> ((S.index (v_arr) (v_k)) <= (S.index (v_arr) ((v_k + (1)))))))) /\ ((v_result_9 == false) ==> (exists (v_k:nat). (((v_k + (1)) < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) > (S.index (v_arr) ((v_k + (1))))))))
        ))
        (ensures (fun ls_result ->
          ((ls_result == true) ==> (forall (v_k:nat). (((v_k + (1)) < (S.length (v_arr))) ==> ((S.index (v_arr) (v_k)) <= (S.index (v_arr) ((v_k + (1)))))))) /\ ((ls_result == false) ==> (exists (v_k:nat). (((v_k + (1)) < (S.length (v_arr))) /\ ((S.index (v_arr) (v_k)) > (S.index (v_arr) ((v_k + (1))))))))
        ))
        (decreases (R.nat_of_int ((S.length (v_arr)) - v_i_10))) =
    if ((v_i_10 + (1)) < (S.length (v_arr))) then (
      if ((S.index (v_arr) (v_i_10)) > (S.index (v_arr) ((v_i_10 + (1))))) then (
        let v_result_13 : bool = false in
        v_result_13
      ) else (
        let v_i_14 : int = (v_i_10 + (1)) in
        (ls_loop_7 (v_result_9) (v_i_14))
      )
    ) else (
      v_result_9
    )
  in
  (ls_loop_7 (v_result_5) (v_i_6))
