/-
  Generated by lsc from leftPad.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import LemmaScript

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method leftPad (str : String) (len : Nat) (ch : String) return (res : String)
  require ch.length = 1
  ensures str.length ≥ len → res = str
  ensures str.length < len → res.length = len
  do
    let mut len : Nat := len
    let mut result : String := str
    len := len - str.length
    let mut i : Nat := 0
    while i < len
      invariant result.length = str.length + i
      invariant i ≥ 0
      invariant len > 0 → i ≤ len
      invariant len ≤ 0 → result = str
      decreasing len - i
    do
      result := ch + result
      i := i + 1
    return result
