// Generated by lsc. Program source: counter.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mcounter_03d4a557ea7c

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Counter  = {
  f_v_Counter_v_count: int;
  f_v_Counter_v_max: int;
}

let v_Counter_2e_increment  (v_this:v_Counter)
  : Ghost (int & v_Counter)
      (requires (
        ((v_this).f_v_Counter_v_count < (v_this).f_v_Counter_v_max)
      ))
      (ensures (fun ls_result ->
        (((let (_, ls_item) = ls_result in ls_item)).f_v_Counter_v_count <= ((let (_, ls_item) = ls_result in ls_item)).f_v_Counter_v_max)
      )) =
  let v_old_2 : int = (v_this).f_v_Counter_v_count in
  let v_this_3 : v_Counter = { v_this with f_v_Counter_v_count = ((v_this).f_v_Counter_v_count + (1)) } in
  (v_old_2, v_this_3)

let v_Counter_2e_getCount  (v_this:v_Counter)
  : Ghost (int & v_Counter)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((let (ls_item, _) = ls_result in ls_item) == ((let (_, ls_item) = ls_result in ls_item)).f_v_Counter_v_count)
      )) =
  ((v_this).f_v_Counter_v_count, v_this)

let v_Counter_2e_isAtMax  (v_this:v_Counter)
  : Ghost (bool & v_Counter)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((let (ls_item, _) = ls_result in ls_item) == (((let (_, ls_item) = ls_result in ls_item)).f_v_Counter_v_count >= ((let (_, ls_item) = ls_result in ls_item)).f_v_Counter_v_max))
      )) =
  (((v_this).f_v_Counter_v_count >= (v_this).f_v_Counter_v_max), v_this)
