// Generated by lsc. Program source: bigintBits.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MbigintBits_606414c5a39c

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_shiftWide  (v_x:int)
  : Ghost int
      (requires (
        (v_x >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_x)
      )) =
  (v_x * 1180591620717411303424)

let v_low64  (v_x:int)
  : Ghost int
      (requires (
        (v_x >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result < (18446744073709551616)) /\ (ls_result >= (0))
      )) =
  (v_x % 18446744073709551616)
