// Generated by lsc. Program source: countBadPairs.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.McountBadPairs_3df3122fe448

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Pair  = {
  f_v_Pair_v_i: nat;
  f_v_Pair_v_j: nat;
}

// Finite pair sets connect the imperative counters to the source specification.
[@@"opaque_to_smt"]
let rec filter_set (#a:eqtype) (p:a -> GTot bool) (s:FS.set a)
  : GTot (r:FS.set a{forall x. FS.mem x r <==> FS.mem x s /\ p x})
    (decreases (FS.cardinality s)) =
  if FS.cardinality s = 0 then FS.emptyset else
  let x = FS.choose s in
  let tail = filter_set p (FS.remove x s) in
  if p x then FS.insert x tail else tail

unfold let pair (i j:nat) : v_Pair = { f_v_Pair_v_i = i; f_v_Pair_v_j = j }
[@@"opaque_to_smt"]
let rec column (j:nat) (m:nat{m <= j})
  : GTot (s:FS.set v_Pair{FS.cardinality s == m /\
      (forall p. FS.mem p s <==> p.f_v_Pair_v_j == j /\ p.f_v_Pair_v_i < m)})
    (decreases m) =
  if m = 0 then FS.emptyset else FS.insert (pair (m-1) j) (column j (m-1))
[@@"opaque_to_smt"]
let rec all_pairs (n:nat)
  : GTot (s:FS.set v_Pair{2 * FS.cardinality s == n * (n-1) /\
      (forall p. FS.mem p s <==> p.f_v_Pair_v_i < p.f_v_Pair_v_j /\ p.f_v_Pair_v_j < n)})
    (decreases n) =
  if n = 0 then FS.emptyset else
  let a = all_pairs (n-1) in
  let b = column (n-1) (n-1) in
  assert (FS.disjoint a b);
  FS.union a b
let good_test (nums:S.seq int) (p:v_Pair) : Tot bool =
  p.f_v_Pair_v_i < p.f_v_Pair_v_j && p.f_v_Pair_v_j < S.length nums &&
  S.index nums p.f_v_Pair_v_j - S.index nums p.f_v_Pair_v_i = p.f_v_Pair_v_j - p.f_v_Pair_v_i
[@@"opaque_to_smt"]
let good_pairs (nums:S.seq int)
  : GTot (s:FS.set v_Pair{forall p. FS.mem p s <==> good_test nums p}) =
  let a = all_pairs (S.length nums) in filter_set (good_test nums) a
[@@"opaque_to_smt"]
let bad_pairs (nums:S.seq int)
  : GTot (s:FS.set v_Pair{forall p. FS.mem p s <==> p.f_v_Pair_v_i < p.f_v_Pair_v_j /\ p.f_v_Pair_v_j < S.length nums /\ not (good_test nums p)}) =
  let a = all_pairs (S.length nums) in filter_set (fun p -> not (good_test nums p)) a
[@@"opaque_to_smt"]
let rows (nums:S.seq int) (i:nat)
  : GTot (s:FS.set v_Pair{forall p. FS.mem p s <==> good_test nums p /\ p.f_v_Pair_v_i < i}) =
  let g = good_pairs nums in filter_set (fun p -> p.f_v_Pair_v_i < i) g
[@@"opaque_to_smt"]
let row_part (nums:S.seq int) (i k:nat)
  : GTot (s:FS.set v_Pair{forall p. FS.mem p s <==> good_test nums p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k)}) =
  let g = good_pairs nums in
  filter_set (fun p -> p.f_v_Pair_v_i < i || (p.f_v_Pair_v_i = i && p.f_v_Pair_v_j < k)) g
[@@"opaque_to_smt"]
let cols (nums:S.seq int) (i:nat)
  : GTot (s:FS.set v_Pair{forall p. FS.mem p s <==> good_test nums p /\ p.f_v_Pair_v_j < i}) =
  let g = good_pairs nums in filter_set (fun p -> p.f_v_Pair_v_j < i) g

let partition_arithmetic (n a g b:nat)
  : Lemma (requires (2*a == n*(n-1) /\ g+b == a))
      (ensures (b == n*(n-1)/2-g)) =
  FStar.Math.Lemmas.cancel_mul_div a 2;
  assert (n*(n-1) == a*2)

let partition_size (nums:S.seq int)
  : Lemma (FS.cardinality (bad_pairs nums) == (S.length nums * (S.length nums-1))/2 - FS.cardinality (good_pairs nums)) =
  let a = all_pairs (S.length nums) in
  let g = good_pairs nums in
  let b = bad_pairs nums in
  assert (FS.equal (FS.union g b) a);
  assert (FS.disjoint g b);
  assert (FS.cardinality g + FS.cardinality b == FS.cardinality a);
  partition_arithmetic (S.length nums) (FS.cardinality a) (FS.cardinality g) (FS.cardinality b)

let row_start (nums:S.seq int) (i:nat)
  : Lemma (row_part nums i (i+1) == rows nums i) =
  assert (FS.equal (row_part nums i (i+1)) (rows nums i))
let row_logic (good:v_Pair -> Tot bool) (i k:nat) (p:v_Pair)
  : Lemma ((good p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k+1)) <==>
      (good p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k)) \/
      (good (pair i k) /\ p == pair i k)) = ()

let row_step (nums:S.seq int) (i k:nat)
  : Lemma (requires (i < k /\ k < S.length nums))
      (ensures (FS.cardinality (row_part nums i (k+1)) == FS.cardinality (row_part nums i k) +
        (if good_test nums (pair i k) then 1 else 0))) =
  let old = row_part nums i k in
  let next = row_part nums i (k+1) in
  if good_test nums (pair i k) then (
    assert (not (FS.mem (pair i k) old));
    let member (p:v_Pair) : Lemma (FS.mem p next <==> FS.mem p old \/ p == pair i k) =
      row_logic (good_test nums) i k p;
      assert (FS.mem p old <==> good_test nums p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k));
      assert (FS.mem p next <==> good_test nums p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k+1));
      assert ((p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j == k) <==> p == pair i k)
    in FStar.Classical.forall_intro member;
    assert (FS.equal next (FS.insert (pair i k) old));
    assert (FS.cardinality next == FS.cardinality old + 1)
  ) else (
    let member (p:v_Pair) : Lemma (FS.mem p next <==> FS.mem p old) =
      row_logic (good_test nums) i k p;
      assert (FS.mem p old <==> good_test nums p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k));
      assert (FS.mem p next <==> good_test nums p /\ (p.f_v_Pair_v_i < i \/ p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j < k+1));
      assert ((p.f_v_Pair_v_i == i /\ p.f_v_Pair_v_j == k) <==> p == pair i k)
    in FStar.Classical.forall_intro member;
    assert (FS.equal next old);
    assert (next == old);
    assert (FS.cardinality next == FS.cardinality old);
    assert ((if good_test nums (pair i k) then 1 else 0) == 0)
  )
let row_end (nums:S.seq int) (i:nat)
  : Lemma (row_part nums i (S.length nums) == rows nums (i+1)) =
  assert (FS.equal (row_part nums i (S.length nums)) (rows nums (i+1)))
let rows_done (nums:S.seq int)
  : Lemma (requires (S.length nums > 0))
      (ensures (rows nums (S.length nums-1) == good_pairs nums)) =
  assert (FS.equal (rows nums (S.length nums-1)) (good_pairs nums))

let rec frequency (nums:S.seq int) (i:nat{i <= S.length nums}) (d:int)
  : Tot (n:nat{n <= i}) (decreases i) =
  if i = 0 then 0 else frequency nums (i-1) d + (if S.index nums (i-1) - (i-1) = d then 1 else 0)
[@@"opaque_to_smt"]
let rec good_column (nums:S.seq int) (j:nat{j < S.length nums}) (m:nat{m <= j})
  : GTot (s:FS.set v_Pair{FS.cardinality s == frequency nums m (S.index nums j - j) /\
      (forall p. FS.mem p s <==> p.f_v_Pair_v_j == j /\ p.f_v_Pair_v_i < m /\ good_test nums p)})
    (decreases m) =
  if m = 0 then FS.emptyset else
  let tail = good_column nums j (m-1) in
  if good_test nums (pair (m-1) j) then FS.insert (pair (m-1) j) tail else tail
let good_domain (nums:S.seq int) (p:v_Pair)
  : Lemma (good_test nums p ==> p.f_v_Pair_v_i < p.f_v_Pair_v_j /\ p.f_v_Pair_v_j < S.length nums) = ()
let column_step (nums:S.seq int) (i:nat{i < S.length nums})
  : Lemma (FS.cardinality (cols nums (i+1)) == FS.cardinality (cols nums i) + frequency nums i (S.index nums i - i)) =
  let old = cols nums i in
  let added = good_column nums i i in
  assert (FS.disjoint old added);
  let next = cols nums (i+1) in
  let member (p:v_Pair) : Lemma (FS.mem p next <==> FS.mem p old \/ FS.mem p added) =
    good_domain nums p;
    assert (FS.mem p old <==> good_test nums p /\ p.f_v_Pair_v_j < i);
    assert (FS.mem p next <==> good_test nums p /\ p.f_v_Pair_v_j < i+1);
    assert (FS.mem p added <==> p.f_v_Pair_v_j == i /\ p.f_v_Pair_v_i < i /\ good_test nums p)
  in FStar.Classical.forall_intro member;
  assert (FS.equal (cols nums (i+1)) (FS.union old added))
let cols_done (nums:S.seq int)
  : Lemma (cols nums (S.length nums) == good_pairs nums) =
  assert (FS.equal (cols nums (S.length nums)) (good_pairs nums))
let map_count (m:FM.map int int) (d:int) : int =
  match FM.elements m d with | None -> 0 | Some n -> n
unfold let frequency_map (nums:S.seq int) (i:nat{i <= S.length nums}) (m:FM.map int int) : prop =
  forall (d:int). map_count m d == frequency nums i d
let frequency_step (nums:S.seq int) (i:nat{i < S.length nums}) (m:FM.map int int)
  : Lemma (requires (frequency_map nums i m))
      (ensures (let d = S.index nums i - i in frequency_map nums (i+1) (FM.insert d (map_count m d + 1) m))) = ()

[@@"opaque_to_smt"]
let v_allPairsImpl  (v_nums:(S.seq int))
  : Ghost (FS.set v_Pair)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  let v_result_1 : (FS.set v_Pair) = FS.emptyset in
  let v_i_2 : int = (0) in
  let rec ls_loop_3 (v_result_5:(FS.set v_Pair)) (v_i_6:int)
    : Ghost (FS.set v_Pair)
        (requires (
          0 <= v_i_6 /\ ((0) <= v_i_6) /\ (v_i_6 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_5) ==> ((((v_p).f_v_Pair_v_i < v_i_6) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_6) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_5))))
        ))
        (ensures (fun ls_result ->
          True
        ))
        (decreases (R.nat_of_int ((S.length (v_nums)) - v_i_6))) =
    if (v_i_6 < (S.length (v_nums))) then (
      let v_j_10 : int = (v_i_6 + (1)) in
      let rec ls_loop_11 (v_result_13:(FS.set v_Pair)) (v_j_14:int)
        : Ghost (FS.set v_Pair)
            (requires (
              ((v_i_6 + (1)) <= v_j_14) /\ (v_j_14 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_13) ==> (((((v_p).f_v_Pair_v_i < v_i_6) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) \/ ((((v_p).f_v_Pair_v_i == v_i_6) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ ((v_p).f_v_Pair_v_j < v_j_14))))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_6) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_13)))) /\ (forall (v_y:nat). ((v_i_6 < v_y) /\ (v_y < v_j_14) ==> (FS.mem { f_v_Pair_v_i = v_i_6; f_v_Pair_v_j = v_y } v_result_13)))
            ))
            (ensures (fun ls_result ->
              True
            ))
            (decreases (R.nat_of_int ((S.length (v_nums)) - v_j_14))) =
        if (v_j_14 < (S.length (v_nums))) then (
          let v_result_19 : (FS.set v_Pair) = (FS.insert ({ f_v_Pair_v_i = v_i_6; f_v_Pair_v_j = v_j_14 }) (v_result_13)) in
          let v_j_20 : int = (v_j_14 + (1)) in
          (ls_loop_11 (v_result_19) (v_j_20))
        ) else (
          let v_i_21 : int = (v_i_6 + (1)) in
          (ls_loop_3 (v_result_13) (v_i_21))
        )
      in
      (ls_loop_11 (v_result_5) (v_j_10))
    ) else (
      v_result_5
    )
  in
  (ls_loop_3 (v_result_1) (v_i_2))

[@@"opaque_to_smt"]
let v_goodPairsImpl  (v_nums:(S.seq int))
  : Ghost (FS.set v_Pair)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  let v_result_23 : (FS.set v_Pair) = FS.emptyset in
  let v_i_24 : int = (0) in
  let rec ls_loop_25 (v_result_27:(FS.set v_Pair)) (v_i_28:int)
    : Ghost (FS.set v_Pair)
        (requires (
          0 <= v_i_28 /\ ((0) <= v_i_28) /\ (v_i_28 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_27) ==> (((((v_p).f_v_Pair_v_i < v_i_28) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) == ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i))))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_28) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_x))) == (v_y - v_x)) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_27))))
        ))
        (ensures (fun ls_result ->
          True
        ))
        (decreases (R.nat_of_int ((S.length (v_nums)) - v_i_28))) =
    if (v_i_28 < (S.length (v_nums))) then (
      let v_j_32 : int = (v_i_28 + (1)) in
      let rec ls_loop_33 (v_result_35:(FS.set v_Pair)) (v_j_36:int)
        : Ghost (FS.set v_Pair)
            (requires (
              ((v_i_28 + (1)) <= v_j_36) /\ (v_j_36 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_35) ==> ((((((v_p).f_v_Pair_v_i < v_i_28) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) == ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i))) \/ (((((v_p).f_v_Pair_v_i == v_i_28) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ ((v_p).f_v_Pair_v_j < v_j_36)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) == ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i)))))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_28) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_x))) == (v_y - v_x)) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_35)))) /\ (forall (v_y:nat). ((v_i_28 < v_y) /\ (v_y < v_j_36) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_i_28))) == (v_y - v_i_28)) ==> (FS.mem { f_v_Pair_v_i = v_i_28; f_v_Pair_v_j = v_y } v_result_35)))
            ))
            (ensures (fun ls_result ->
              True
            ))
            (decreases (R.nat_of_int ((S.length (v_nums)) - v_j_36))) =
        if (v_j_36 < (S.length (v_nums))) then (
          if (R.decide ((((S.index (v_nums) (v_j_36)) - (S.index (v_nums) (v_i_28))) == (v_j_36 - v_i_28)))) then (
            let v_result_41 : (FS.set v_Pair) = (FS.insert ({ f_v_Pair_v_i = v_i_28; f_v_Pair_v_j = v_j_36 }) (v_result_35)) in
            let v_j_42 : int = (v_j_36 + (1)) in
            let included (y:nat) : Lemma (v_i_28 < y /\ y < v_j_42 /\ S.index v_nums y - S.index v_nums v_i_28 == y - v_i_28 ==> FS.mem (pair v_i_28 y) v_result_41) =
              if y < v_j_42 then (if y = v_j_36 then () else assert (y < v_j_36))
            in FStar.Classical.forall_intro included;
            (ls_loop_33 (v_result_41) (v_j_42))
          ) else (
            let v_j_43 : int = (v_j_36 + (1)) in
            (ls_loop_33 (v_result_35) (v_j_43))
          )
        ) else (
          let v_i_44 : int = (v_i_28 + (1)) in
          (ls_loop_25 (v_result_35) (v_i_44))
        )
      in
      (ls_loop_33 (v_result_27) (v_j_32))
    ) else (
      v_result_27
    )
  in
  (ls_loop_25 (v_result_23) (v_i_24))

[@@"opaque_to_smt"]
let v_badPairsImpl  (v_nums:(S.seq int))
  : Ghost (FS.set v_Pair)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
          /\ FS.equal ls_result (bad_pairs v_nums)
      )) =
  let v_result_46 : (FS.set v_Pair) = FS.emptyset in
  let v_i_47 : int = (0) in
  let rec ls_loop_48 (v_result_50:(FS.set v_Pair)) (v_i_51:int)
    : Ghost (FS.set v_Pair)
        (requires (
          0 <= v_i_51 /\ ((0) <= v_i_51) /\ (v_i_51 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_50) ==> (((((v_p).f_v_Pair_v_i < v_i_51) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) =!= ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i))))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_51) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_x))) =!= (v_y - v_x)) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_50))))
        ))
        (ensures (fun ls_result ->
          True
          /\ FS.equal ls_result (bad_pairs v_nums)
        ))
        (decreases (R.nat_of_int ((S.length (v_nums)) - v_i_51))) =
    if (v_i_51 < (S.length (v_nums))) then (
      let v_j_55 : int = (v_i_51 + (1)) in
      let rec ls_loop_56 (v_result_58:(FS.set v_Pair)) (v_j_59:int)
        : Ghost (FS.set v_Pair)
            (requires (
              ((v_i_51 + (1)) <= v_j_59) /\ (v_j_59 <= (S.length (v_nums))) /\ (forall (v_p:v_Pair). ((FS.mem v_p v_result_58) ==> ((((((v_p).f_v_Pair_v_i < v_i_51) /\ ((v_p).f_v_Pair_v_j < (S.length (v_nums)))) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) =!= ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i))) \/ (((((v_p).f_v_Pair_v_i == v_i_51) /\ ((v_p).f_v_Pair_v_i < (v_p).f_v_Pair_v_j)) /\ ((v_p).f_v_Pair_v_j < v_j_59)) /\ (((S.index (v_nums) ((v_p).f_v_Pair_v_j)) - (S.index (v_nums) ((v_p).f_v_Pair_v_i))) =!= ((v_p).f_v_Pair_v_j - (v_p).f_v_Pair_v_i)))))) /\ (forall (v_x:nat). (forall (v_y:nat). ((v_x < v_i_51) /\ (v_y < (S.length (v_nums))) /\ (v_x < v_y) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_x))) =!= (v_y - v_x)) ==> (FS.mem { f_v_Pair_v_i = v_x; f_v_Pair_v_j = v_y } v_result_58)))) /\ (forall (v_y:nat). ((v_i_51 < v_y) /\ (v_y < v_j_59) /\ (((S.index (v_nums) (v_y)) - (S.index (v_nums) (v_i_51))) =!= (v_y - v_i_51)) ==> (FS.mem { f_v_Pair_v_i = v_i_51; f_v_Pair_v_j = v_y } v_result_58)))
            ))
            (ensures (fun ls_result ->
              True
          /\ FS.equal ls_result (bad_pairs v_nums)
            ))
            (decreases (R.nat_of_int ((S.length (v_nums)) - v_j_59))) =
        if (v_j_59 < (S.length (v_nums))) then (
          if (R.decide ((((S.index (v_nums) (v_j_59)) - (S.index (v_nums) (v_i_51))) =!= (v_j_59 - v_i_51)))) then (
            let v_result_64 : (FS.set v_Pair) = (FS.insert ({ f_v_Pair_v_i = v_i_51; f_v_Pair_v_j = v_j_59 }) (v_result_58)) in
            let v_j_65 : int = (v_j_59 + (1)) in
            let included (y:nat) : Lemma (v_i_51 < y /\ y < v_j_65 /\ S.index v_nums y - S.index v_nums v_i_51 =!= y - v_i_51 ==> FS.mem (pair v_i_51 y) v_result_64) =
              if y < v_j_65 then (if y = v_j_59 then () else assert (y < v_j_59))
            in FStar.Classical.forall_intro included;
            (ls_loop_56 (v_result_64) (v_j_65))
          ) else (
            let v_j_66 : int = (v_j_59 + (1)) in
            (ls_loop_56 (v_result_58) (v_j_66))
          )
        ) else (
          let v_i_67 : int = (v_i_51 + (1)) in
          (ls_loop_48 (v_result_58) (v_i_67))
        )
      in
      (ls_loop_56 (v_result_50) (v_j_55))
    ) else (
      v_result_50
    )
  in
  (ls_loop_48 (v_result_46) (v_i_47))

[@@"opaque_to_smt"]
let v_countBadPairsNaive  (v_nums:(S.seq int))
  : Ghost int
      (requires (
        ((S.length (v_nums)) > (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0)) /\ (ls_result == (FS.cardinality ((v_badPairsImpl (v_nums)))))
      )) =
  assert (FS.equal (rows v_nums 0) FS.emptyset);
  let v_count_71 : int = (0) in
  let v_n_72 : int = (S.length (v_nums)) in
  let v_i_73 : int = (0) in
  let rec ls_loop_74 (v_count_76:int) (v_i_77:int)
    : Ghost int
        (requires (
          0 <= v_count_76 /\ 0 <= v_i_77 /\ ((0) <= v_i_77) /\ (v_i_77 <= (v_n_72 - (1))) /\ (v_count_76 >= (0))
          /\ v_count_76 == FS.cardinality (rows v_nums v_i_77)
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0)) /\ (ls_result == (FS.cardinality ((v_badPairsImpl (v_nums)))))
        ))
        (decreases (R.nat_of_int ((v_n_72 - (1)) - v_i_77))) =
    if (v_i_77 < (v_n_72 - (1))) then (
      let v_iprime_78 : int = ((S.index (v_nums) (v_i_77)) - v_i_77) in
      row_start v_nums v_i_77;
      let v_k_79 : int = (v_i_77 + (1)) in
      let rec ls_loop_80 (v_count_82:int) (v_k_83:int)
        : Ghost int
            (requires (
              0 <= v_count_82 /\ ((v_i_77 + (1)) <= v_k_83) /\ (v_k_83 <= v_n_72) /\ (v_count_82 >= (0))
          /\ v_count_82 == FS.cardinality (row_part v_nums v_i_77 v_k_83)
            ))
            (ensures (fun ls_result ->
              (ls_result >= (0)) /\ (ls_result == (FS.cardinality ((v_badPairsImpl (v_nums)))))
            ))
            (decreases (R.nat_of_int (v_n_72 - v_k_83))) =
        if (v_k_83 < v_n_72) then (
          row_step v_nums v_i_77 v_k_83;
          if (R.decide ((((S.index (v_nums) (v_k_83)) - v_k_83) == v_iprime_78))) then (
            let v_count_84 : int = (v_count_82 + (1)) in
            let v_k_85 : int = (v_k_83 + (1)) in
            (ls_loop_80 (v_count_84) (v_k_85))
          ) else (
            let v_k_86 : int = (v_k_83 + (1)) in
            (ls_loop_80 (v_count_82) (v_k_86))
          )
        ) else (
          row_end v_nums v_i_77;
          assert (v_k_83 == S.length v_nums);
          assert (row_part v_nums v_i_77 v_k_83 == rows v_nums (v_i_77+1));
          assert (v_count_82 == FS.cardinality (rows v_nums (v_i_77+1)));
          let v_i_87 : int = (v_i_77 + (1)) in
          (ls_loop_74 (v_count_82) (v_i_87))
        )
      in
      (ls_loop_80 (v_count_76) (v_k_79))
    ) else (
      rows_done v_nums;
      partition_size v_nums;
      let v_pairs_88 : int = ((R.floor_div (((v_n_72 - (1)) * v_n_72)) ((2))) - v_count_76) in
      assert (R.floor_div ((v_n_72-1)*v_n_72) 2 == (v_n_72*(v_n_72-1))/2);
      assert (v_pairs_88 == FS.cardinality (bad_pairs v_nums));
      let specified = v_badPairsImpl v_nums in
      assert (specified == bad_pairs v_nums);
      v_pairs_88
    )
  in
  (ls_loop_74 (v_count_71) (v_i_73))

[@@"opaque_to_smt"]
let v_countBadPairs  (v_nums:(S.seq int))
  : Ghost int
      (requires (
        ((S.length (v_nums)) > (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0)) /\ (ls_result == (FS.cardinality ((v_badPairsImpl (v_nums)))))
      )) =
  assert (FS.equal (cols v_nums 0) FS.emptyset);
  let v_goodCount_92 : int = (0) in
  let v_n_93 : int = (S.length (v_nums)) in
  let v_diffMap_94 : (FM.map int int) = FM.emptymap in
  let v_i_95 : int = (0) in
  let rec ls_loop_96 (v_goodCount_98:int) (v_diffMap_99:(FM.map int int)) (v_i_100:int)
    : Ghost int
        (requires (
          0 <= v_i_100 /\ ((0) <= v_i_100) /\ (v_i_100 <= v_n_93) /\ (v_goodCount_98 >= (0))
          /\ v_goodCount_98 == FS.cardinality (cols v_nums v_i_100) /\ frequency_map v_nums v_i_100 v_diffMap_99
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0)) /\ (ls_result == (FS.cardinality ((v_badPairsImpl (v_nums)))))
        ))
        (decreases (R.nat_of_int (v_n_93 - v_i_100))) =
    if (v_i_100 < v_n_93) then (
      column_step v_nums v_i_100;
      frequency_step v_nums v_i_100 v_diffMap_99;
      let v_diff_101 : int = ((S.index (v_nums) (v_i_100)) - v_i_100) in
      let v_count_102 : int = (match (FM.elements (v_diffMap_99) (v_diff_101)) with
      | Some v__5f_oc0_5f_val -> v__5f_oc0_5f_val
      | None -> (0)) in
      let v_goodCount_104 : int = (v_goodCount_98 + v_count_102) in
      let v_diffMap_105 : (FM.map int int) = (FM.insert (v_diff_101) ((v_count_102 + (1))) (v_diffMap_99)) in
      let v_i_106 : int = (v_i_100 + (1)) in
      (ls_loop_96 (v_goodCount_104) (v_diffMap_105) (v_i_106))
    ) else (
      cols_done v_nums;
      partition_size v_nums;
      let specified = v_badPairsImpl v_nums in
      assert (specified == bad_pairs v_nums);
      assert (v_goodCount_98 == FS.cardinality (good_pairs v_nums));
      assert (R.floor_div ((v_n_93-1)*v_n_93) 2 == (v_n_93*(v_n_93-1))/2);
      assert (R.floor_div ((v_n_93-1)*v_n_93) 2 - v_goodCount_98 == FS.cardinality (bad_pairs v_nums));
      ((R.floor_div (((v_n_93 - (1)) * v_n_93)) ((2))) - v_goodCount_98)
    )
  in
  (ls_loop_96 (v_goodCount_92) (v_diffMap_94) (v_i_95))
