// Generated by lsc. Program source: majority.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mmajority_484d28700439

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let rec v_occOf  (v_arr:(S.seq int)) (v_x:int) (v_n:nat)
  : Ghost int
      (requires (
        ((0) <= v_n) /\ (v_n <= (S.length (v_arr)))
      ))
      (ensures (fun ls_result ->
        True
      ))
      (decreases v_n) =
  (if (R.decide ((v_n == (0)))) then (0) else ((v_occOf (v_arr) (v_x) ((v_n - (1)))) + (if (R.decide (((S.index (v_arr) ((v_n - (1)))) == v_x))) then (1) else (0))))

let occurrence_step (arr:S.seq int) (x:int) (j:nat{j < S.length arr})
  : Lemma (v_occOf arr x (j+1) == v_occOf arr x j + (if S.index arr j = x then 1 else 0)) = ()

let no_majority (arr:S.seq int) (candidate:int) (count:nat)
  : Lemma (requires (2 * v_occOf arr candidate (S.length arr) <= S.length arr /\
      (forall (x:int). x =!= candidate ==> 2 * v_occOf arr x (S.length arr) <= S.length arr - count)))
      (ensures (forall (x:int). 2 * v_occOf arr x (S.length arr) <= S.length arr)) =
  let bound (x:int) : Lemma (2 * v_occOf arr x (S.length arr) <= S.length arr) =
    if x = candidate then () else ()
  in FStar.Classical.forall_intro bound

let v_majority  (v_arr:(S.seq int))
  : Ghost int
      (requires (
        (forall (v_k:nat). ((v_k < (S.length (v_arr))) ==> ((S.index (v_arr) (v_k)) >= (0))))
      ))
      (ensures (fun ls_result ->
        ((ls_result == (-1)) \/ ((ls_result >= (0)) /\ (((2) * (v_occOf (v_arr) (ls_result) ((S.length (v_arr))))) > (S.length (v_arr))))) /\ ((exists (v_x:nat). (((2) * (v_occOf (v_arr) (v_x) ((S.length (v_arr))))) > (S.length (v_arr)))) ==> (ls_result =!= (-1)))
      )) =
  let v_cand_8 : int = (0) in
  let v_cnt_9 : int = (0) in
  let v_i_10 : int = (0) in
  let rec ls_loop_11 (v_cand_13:int) (v_cnt_14:int) (v_i_15:int)
    : Ghost int
        (requires (
          0 <= v_i_15 /\ ((0) <= v_i_15) /\ (v_i_15 <= (S.length (v_arr))) /\ (v_cnt_14 >= (0)) /\ (v_cand_13 >= (0)) /\ (((2) * (v_occOf (v_arr) (v_cand_13) (v_i_15))) <= (v_i_15 + v_cnt_14)) /\ (forall (v_y:int). ((v_y =!= v_cand_13) ==> (((2) * (v_occOf (v_arr) (v_y) (v_i_15))) <= (v_i_15 - v_cnt_14))))
        ))
        (ensures (fun ls_result ->
          ((ls_result == (-1)) \/ ((ls_result >= (0)) /\ (((2) * (v_occOf (v_arr) (ls_result) ((S.length (v_arr))))) > (S.length (v_arr))))) /\ ((exists (v_x:nat). (((2) * (v_occOf (v_arr) (v_x) ((S.length (v_arr))))) > (S.length (v_arr)))) ==> (ls_result =!= (-1)))
        ))
        (decreases (R.nat_of_int ((S.length (v_arr)) - v_i_15))) =
    if (v_i_15 < (S.length (v_arr))) then (
      if (R.decide ((v_cnt_14 == (0)))) then (
        let v_cand_17 : int = (S.index (v_arr) (v_i_15)) in
        let v_cnt_18 : int = (1) in
        let v_i_19 : int = (v_i_15 + (1)) in
        (ls_loop_11 (v_cand_17) (v_cnt_18) (v_i_19))
      ) else (
        if (R.decide (((S.index (v_arr) (v_i_15)) == v_cand_13))) then (
          let v_cnt_20 : int = (v_cnt_14 + (1)) in
          let v_i_21 : int = (v_i_15 + (1)) in
          (ls_loop_11 (v_cand_13) (v_cnt_20) (v_i_21))
        ) else (
          let v_cnt_22 : int = (v_cnt_14 - (1)) in
          let v_i_23 : int = (v_i_15 + (1)) in
          (ls_loop_11 (v_cand_13) (v_cnt_22) (v_i_23))
        )
      )
    ) else (
      let v_occ_24 : int = (0) in
      let v_j_25 : int = (0) in
      let rec ls_loop_26 (v_occ_28:int) (v_j_29:int)
        : Ghost int
            (requires (
              0 <= v_occ_28 /\ 0 <= v_j_29 /\ ((0) <= v_j_29) /\ (v_j_29 <= (S.length (v_arr))) /\ (v_occ_28 == (v_occOf (v_arr) (v_cand_13) (v_j_29)))
            ))
            (ensures (fun ls_result ->
              ((ls_result == (-1)) \/ ((ls_result >= (0)) /\ (((2) * (v_occOf (v_arr) (ls_result) ((S.length (v_arr))))) > (S.length (v_arr))))) /\ ((exists (v_x:nat). (((2) * (v_occOf (v_arr) (v_x) ((S.length (v_arr))))) > (S.length (v_arr)))) ==> (ls_result =!= (-1)))
            ))
            (decreases (R.nat_of_int ((S.length (v_arr)) - v_j_29))) =
        if (v_j_29 < (S.length (v_arr))) then (
          occurrence_step v_arr v_cand_13 v_j_29;
          if (R.decide (((S.index (v_arr) (v_j_29)) == v_cand_13))) then (
            let v_occ_30 : int = (v_occ_28 + (1)) in
            let v_j_31 : int = (v_j_29 + (1)) in
            (ls_loop_26 (v_occ_30) (v_j_31))
          ) else (
            let v_j_32 : int = (v_j_29 + (1)) in
            (ls_loop_26 (v_occ_28) (v_j_32))
          )
        ) else (
          if (((2) * v_occ_28) > (S.length (v_arr))) then (
            v_cand_13
          ) else (
            no_majority v_arr v_cand_13 v_cnt_14;
            (-1)
          )
        )
      in
      (ls_loop_26 (v_occ_24) (v_j_25))
    )
  in
  (ls_loop_11 (v_cand_8) (v_cnt_9) (v_i_10))
