// Generated by lsc. Program source: mapRecord.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MmapRecord_d12b35fb9782

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_In  = {
  f_v_In_v_tag: R.string;
  f_v_In_v_n: int;
}

noeq type v_Out  = {
  f_v_Out_v_label: R.string;
  f_v_Out_v_doubled: int;
}

let v_relabel  (v_items:(S.seq v_In))
  : Ghost (S.seq v_Out)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) == (S.length (v_items)))
      )) =
  (R.map ((fun (v_it:v_In) ->
    { f_v_Out_v_label = (v_it).f_v_In_v_tag; f_v_Out_v_doubled = ((v_it).f_v_In_v_n * (2)) })) (v_items))
