// Generated by lsc from mapRecord.ts

datatype In = In(tag: string, n: int)

datatype Out = Out(label_: string, doubled: int)

function relabel(items: seq<In>): seq<Out>
{
  Std.Collections.Seq.Map((it: In) => Out(it.tag, (it.n * 2)), items)
}

lemma relabel_ensures(items: seq<In>)
  ensures (|relabel(items)| == |items|)
{
}
