// Generated by lsc. Program source: maxSpread.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MmaxSpread_7a2cf3c19464

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_highScore  (v_scores:(S.seq int))
  : Ghost int
      (requires (
        ((S.length (v_scores)) > (0))
      ))
      (ensures (fun ls_result ->
        (forall (v_i:nat). ((v_i < (S.length (v_scores))) ==> ((S.index (v_scores) (v_i)) <= ls_result)))
      )) =
  (R.maximum (v_scores))

let v_highScoreOrZero  (v_scores:(S.seq int))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0)) /\ (forall (v_i:nat). ((v_i < (S.length (v_scores))) ==> ((S.index (v_scores) (v_i)) <= ls_result)))
      )) =
  (R.maximum ((S.append (v_scores) ((S.build (S.empty) ((0)))))))

let v_lowScore  (v_scores:(S.seq int))
  : Ghost int
      (requires (
        ((S.length (v_scores)) > (0))
      ))
      (ensures (fun ls_result ->
        (forall (v_i:nat). ((v_i < (S.length (v_scores))) ==> (ls_result <= (S.index (v_scores) (v_i)))))
      )) =
  (R.minimum (v_scores))

let v_maxOfPrefixedAndSuffixed  (v_prefix:int) (v_scores:(S.seq int)) (v_suffix:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result >= v_prefix) /\ (ls_result >= v_suffix) /\ (forall (v_i:nat). ((v_i < (S.length (v_scores))) ==> ((S.index (v_scores) (v_i)) <= ls_result)))
      )) =
  (R.maximum ((S.append ((S.append ((S.build (S.empty) (v_prefix))) (v_scores))) ((S.build (S.empty) (v_suffix))))))

let v_maxOfTwoArrays  (v_a:(S.seq int)) (v_b:(S.seq int))
  : Ghost int
      (requires (
        (((S.length (v_a)) + (S.length (v_b))) > (0))
      ))
      (ensures (fun ls_result ->
        (forall (v_i:nat). ((v_i < (S.length (v_a))) ==> ((S.index (v_a) (v_i)) <= ls_result))) /\ (forall (v_i:nat). ((v_i < (S.length (v_b))) ==> ((S.index (v_b) (v_i)) <= ls_result)))
      )) =
  (R.maximum ((S.append (v_a) (v_b))))
