/-
  Generated by lsc from nameClash.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «nameClash.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method delKey (d : Std.HashMap String Int) (k : String) return (res : Std.HashMap String Int)
  ensures ¬(res.contains k)
  ensures ∀ j : String, j ≠ k → d.contains j → res.contains j ∧ res.get! j = d.get! j
  do
    return Pure.delKey d k

method single (n : Int) return (res : Array Int)
  ensures res.size = 1
  ensures res[0]! = n
  do
    return Pure.single n

method anyOdd (n : Int) return (res : Bool)
  ensures res → Int.tmod n 2 = 1
  ensures Int.tmod n 2 = 1 → res
  do
    return Pure.anyOdd n

method underscoreVsMangled (i_x : Int) return (res : Int)
  ensures res = i_x
  do
    return Pure.underscoreVsMangled i_x

method keywordVsMangled («match» : Int) return (res : Int)
  ensures res = «match»
  do
    return Pure.keywordVsMangled «match»

method passThrough (res : Int) return (res' : Int)
  ensures res' = res + 0
  do
    return Pure.passThrough res

method sumTo (x : Int) return (res : Int)
  require x ≥ 0
  ensures res ≥ 0
  do
    let mut res : Int := 0
    let mut i : Int := 0
    while i < x
      invariant 0 ≤ i
      invariant i ≤ x
      invariant res ≥ 0
      decreasing (x - i).toNat
    do
      res := res + i
      i := i + 1
    return res
