/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def delKey (d : Std.HashMap String Int) (k : String) : Std.HashMap String Int :=
  let rest := d.erase k
  rest

def single (n : Int) : Array Int :=
  #[n]

def anyOdd (n : Int) : Bool :=
  (single n).any (fun n => Int.tmod n 2 = 1)

def underscoreVsMangled (i_x : Int) : Int :=
  let _x := 1
  i_x

def keywordVsMangled («match» : Int) : Int :=
  let match_ := 2
  «match»

def passThrough (res : Int) : Int :=
  res

def callee (x : Int) : Int :=
  x + 1

def someEscCollision (_x : Int) (i_x : Int) : Bool :=
  (single _x).any (fun _x => _x > 0)

end Pure
