// Generated by lsc. Program source: nameClash.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MnameClash_7d9891de1a23

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_ClashVerdict  =
| C_v_ClashVerdict_v_ok : v_ClashVerdict
| C_v_ClashVerdict_v_error : R.string -> v_ClashVerdict

type v_HyphenVerdict  =
| C_v_HyphenVerdict_v_ok : v_HyphenVerdict
| C_v_HyphenVerdict_v_rpc_2d_error : int -> v_HyphenVerdict

type v__5f_Box  = {
  f_v__5f_Box_v_x: int;
}

let v_delKey  (v_d:(FM.map (list R.codeunit) int)) (v_k:R.string)
  : Ghost (FM.map (list R.codeunit) int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (not ((FM.mem ((R.to_list (v_k))) (ls_result)))) /\ (forall (v_j:R.string). ((not (S.equal (v_j) (v_k))) /\ (FM.mem ((R.to_list (v_j))) (v_d)) ==> ((FM.mem ((R.to_list (v_j))) (ls_result)) /\ ((FM.lookup ((R.to_list (v_j))) (ls_result)) == (FM.lookup ((R.to_list (v_j))) (v_d))))))
      )) =
  (let v_rest_5 = (FM.remove ((R.to_list (v_k))) (v_d)) in
  v_rest_5)

let v_single  (v_n:int)
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) == (1)) /\ ((S.index (ls_result) ((0))) == v_n)
      )) =
  (S.build (S.empty) (v_n))

let v_anyOdd  (v_n:int)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result ==> ((R.rem (v_n) ((2))) == (1))) /\ (((R.rem (v_n) ((2))) == (1)) ==> ls_result)
      )) =
  (R.some ((fun (v_n:int) ->
    (R.decide (((R.rem (v_n) ((2))) == (1)))))) ((v_single (v_n))))

let v_underscoreVsMangled  (v_i_5f_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_i_5f_x)
      )) =
  (let v__5f_x_15 = (1) in
  v_i_5f_x)

let v_keywordVsMangled  (v_match:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_match)
      )) =
  (let v_match_5f__18 = (2) in
  v_match)

let v_passThrough  (v_res:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (v_res + (0)))
      )) =
  v_res

let v_callee  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (v_x + (1)))
      )) =
  (v_x + (1))

let v_someEscCollision  (v__5f_x:int) (v_i_5f_x:int)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result ==> (v__5f_x > (0)))
      )) =
  (R.some ((fun (v__5f_x:int) ->
    (v__5f_x > (0)))) ((v_single (v__5f_x))))

let v_constructorVsLocal  (v_error:R.string)
  : Ghost v_ClashVerdict
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (match ls_result with | C_v_ClashVerdict_v_error _ -> true | _ -> false) /\ ((match ls_result with | C_v_ClashVerdict_v_error _ -> true | _ -> false) ==> (S.equal ((match ls_result with | C_v_ClashVerdict_v_error ls_field -> ls_field)) (v_error)))
      )) =
  (C_v_ClashVerdict_v_error (v_error))

let v_isRpcError  (v_verdict:v_HyphenVerdict)
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result ==> (match v_verdict with | C_v_HyphenVerdict_v_rpc_2d_error _ -> true | _ -> false))
      )) =
  (R.decide ((match v_verdict with | C_v_HyphenVerdict_v_rpc_2d_error _ -> true | _ -> false)))

let v__5f_foo  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_x)
      )) =
  v_x

let v_i_5f_foo  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_x)
      )) =
  v_x

let v_useBox  (v_b:v__5f_Box)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (v_b).f_v__5f_Box_v_x)
      )) =
  (v_b).f_v__5f_Box_v_x

let v_sumTo  (v_x:int)
  : Ghost int
      (requires (
        (v_x >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_res_40 : int = (0) in
  let v_i_41 : int = (0) in
  let rec ls_loop_42 (v_res_44:int) (v_i_45:int)
    : Ghost int
        (requires (
          0 <= v_i_45 /\ ((0) <= v_i_45) /\ (v_i_45 <= v_x) /\ (v_res_44 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int (R.nat_of_int ((v_x - v_i_45))))) =
    if (v_i_45 < v_x) then (
      let v_res_46 : int = (v_res_44 + v_i_45) in
      let v_i_47 : int = (v_i_45 + (1)) in
      (ls_loop_42 (v_res_46) (v_i_47))
    ) else (
      v_res_44
    )
  in
  (ls_loop_42 (v_res_40) (v_i_41))

let v_tempClash  (v__5f_t0:int) (v_i_5f_t0:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == ((v__5f_t0 + (1)) + (v_i_5f_t0 + (1))))
      )) =
  let v_z_51 : int = (0) in
  let v__5f_t0_27__52 : int = (v_callee (v__5f_t0)) in
  let v__5f_t1_53 : int = (v_callee (v_i_5f_t0)) in
  let v_z_54 : int = (v__5f_t0_27__52 + v__5f_t1_53) in
  v_z_54

let v_resAssignOnly  (v_x:int)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == v_x)
      )) =
  let v_res_57 : int = (0) in
  let v_res_58 : int = (1) in
  v_x
