// Generated by lsc. Program source: nestedPush.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MnestedPush_354313502851

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Bag  = {
  f_v_Bag_v_items: (S.seq int);
}

let v_pushItem  (v_items:(S.seq int)) (v_v:int)
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((S.length (ls_result)) == ((S.length (v_items)) + (1))) /\ ((S.index (ls_result) ((S.length (v_items)))) == v_v)
      )) =
  let v_b_4 : v_Bag = { f_v_Bag_v_items = v_items } in
  let v_b_5 : v_Bag = { v_b_4 with f_v_Bag_v_items = (S.build ((v_b_4).f_v_Bag_v_items) (v_v)) } in
  (v_b_5).f_v_Bag_v_items
