/-
  Generated by lsc from nestedPush.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «nestedPush.types»

set_option velvet.semantics.termination "total"

method pushItem (items : Array Int) (v : Int) returns (res : Array Int)
  ensures ensures_1: (res.size = items.size + 1 : Prop)
  ensures ensures_2: (res[items.size]! = v : Prop)
  do
    let mut b : Bag := { items := items }
    b := { b with items := Array.push b.items v }
    return b.items
