// Generated by lsc. Program source: nestedLoopInvariants.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MnestedLoopInvariants_e9a869543e49

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_nestedSum  (v_n:int)
  : Ghost int
      (requires (
        (v_n >= (0))
      ))
      (ensures (fun ls_result ->
        (ls_result >= (0))
      )) =
  let v_acc_2 : int = (0) in
  let v_i_3 : int = (0) in
  let rec ls_loop_4 (v_acc_6:int) (v_i_7:int)
    : Ghost int
        (requires (
          0 <= v_acc_6 /\ 0 <= v_i_7 /\ ((0) <= v_i_7) /\ (v_i_7 <= v_n) /\ (v_acc_6 >= (0))
        ))
        (ensures (fun ls_result ->
          (ls_result >= (0))
        ))
        (decreases (R.nat_of_int (v_n - v_i_7))) =
    if (v_i_7 < v_n) then (
      let v_j_8 : int = (0) in
      let rec ls_loop_9 (v_acc_11:int) (v_j_12:int)
        : Ghost int
            (requires (
              0 <= v_acc_11 /\ 0 <= v_j_12 /\ ((0) <= v_j_12) /\ (v_j_12 <= v_n) /\ (v_acc_11 >= (0))
            ))
            (ensures (fun ls_result ->
              (ls_result >= (0))
            ))
            (decreases (R.nat_of_int (v_n - v_j_12))) =
        if (v_j_12 < v_n) then (
          let v_acc_13 : int = (v_acc_11 + (1)) in
          let v_j_14 : int = (v_j_12 + (1)) in
          (ls_loop_9 (v_acc_13) (v_j_14))
        ) else (
          let v_i_15 : int = (v_i_7 + (1)) in
          (ls_loop_4 (v_acc_11) (v_i_15))
        )
      in
      (ls_loop_9 (v_acc_6) (v_j_8))
    ) else (
      v_acc_6
    )
  in
  (ls_loop_4 (v_acc_2) (v_i_3))
