/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Entry where
  | msg (text : String) : Entry
  | sep : Entry
deriving Repr, Inhabited

structure Rec where
  tag : String
  body : String
deriving Repr, Inhabited, DecidableEq

namespace Pure

def textOr (e : Option Entry) (dflt : String) : String :=
  let t := (match e with | .some _e_val => if (match _e_val with | .msg .. => true | _ => false) then Option.some (match _e_val with | .msg _v => _v | _ => (default : String)) else Option.none | .none => Option.none)
  match t with
  | .some _oc0_val =>
    _oc0_val
  | .none =>
    dflt

def textOrFlipped (e : Option Entry) (dflt : String) : String :=
  let t := (match e with | .some _e_val => if (match _e_val with | .msg .. => true | _ => false) then Option.some (match _e_val with | .msg _v => _v | _ => (default : String)) else Option.none | .none => Option.none)
  match t with
  | .some _oc1_val =>
    _oc1_val
  | .none =>
    dflt

def bodyOr (r : Option Rec) (dflt : String) : String :=
  let b := (match r with | .some _r_val => if _r_val.tag = "x" then Option.some _r_val.body else Option.none | .none => Option.none)
  match b with
  | .some _oc2_val =>
    _oc2_val
  | .none =>
    dflt

def firstText (e : Option Entry) (dflt : String) : String :=
  match e with
  | .some _e_val =>
    match _e_val with
    | .msg __e_val_text =>
      __e_val_text
    | .sep =>
      dflt
  | .none =>
    dflt

end Pure
