/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import Velvet.Syntax
import Velvet.Std

inductive Packet where
  | syn (seq : Int) : Packet
  | ack (seq : Int) : Packet
  | data (seq : Int) (len : Int) : Packet
  | fin : Packet
deriving Repr, Inhabited

def nextSeq_pure (state : Int) (pkt : Packet) : Int :=
  match pkt with
  | .syn seq =>
    seq
  | .ack seq =>
    state
  | .data seq len =>
    state + len
  | _ =>
    state
