/-
  Generated by lsc from packet.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «packet.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method nextSeq (state : Int) (pkt : Packet) return (res : Int)
  ensures match pkt with | .syn seq => res = seq | _ => true
  ensures match pkt with | .data seq len => res = state + len | _ => true
  ensures match pkt with | .fin => res = state | _ => true
  do
    match pkt with
    | .syn seq =>
      return seq
    | .ack seq =>
      return state
    | .data seq len =>
      return state + len
    | _ =>
      return state
