/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Packet where
  | syn (seq : Int) : Packet
  | ack (seq : Int) : Packet
  | data (seq : Int) (len : Int) : Packet
  | fin : Packet
deriving Repr, Inhabited

namespace Pure

def nextSeq (state : Int) (pkt : Packet) : Int :=
  match pkt with
  | .syn _pkt_seq =>
    _pkt_seq
  | .ack _pkt_seq =>
    state
  | .data _pkt_seq _pkt_len =>
    state + _pkt_len
  | .fin =>
    state

end Pure
