/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def countOn (xs : Array Bool) : Int :=
  if xs.size = 0 then
    0
  else
    (if xs[0]! then 1 else 0) + countOn (xs.extract 1 xs.size)
termination_by xs.size
decreasing_by all_goals (simp_wf; omega)

def permRefl (xs : Array Bool) : Bool :=
  true

def permSymm (xs : Array Bool) (ys : Array Bool) : Bool :=
  true

def permConcatComm (xs : Array Bool) (ys : Array Bool) : Bool :=
  true

def countOnPerm (xs : Array Bool) (ys : Array Bool) : Bool :=
  true

end Pure
