// Generated by lsc. Program source: preorder.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mpreorder_e409d6fa1a37

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Tree  =
| C_v_Tree_v_Nil : v_Tree
| C_v_Tree_v_Node : int -> v_Tree -> v_Tree -> v_Tree

let rec v_preorderTraversal  (v_root:v_Tree)
  : Ghost (S.seq v_Tree)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (match v_root with
  | C_v_Tree_v_Nil -> S.empty
  | C_v_Tree_v_Node v__5f_root_5f_val v__5f_root_5f_left v__5f_root_5f_right -> (if ((R.decide ((v__5f_root_5f_left =!= C_v_Tree_v_Nil))) && (R.decide ((v__5f_root_5f_right =!= C_v_Tree_v_Nil)))) then (S.append ((S.append ((S.build (S.empty) (v_root))) ((v_preorderTraversal (v__5f_root_5f_left))))) ((v_preorderTraversal (v__5f_root_5f_right)))) else (if (R.decide ((v__5f_root_5f_left =!= C_v_Tree_v_Nil))) then (S.append ((S.build (S.empty) (v_root))) ((v_preorderTraversal (v__5f_root_5f_left)))) else (if (R.decide ((v__5f_root_5f_right =!= C_v_Tree_v_Nil))) then (S.append ((S.build (S.empty) (v_root))) ((v_preorderTraversal (v__5f_root_5f_right)))) else (S.build (S.empty) (v_root))))))

let v_childStack  (v_node:v_Tree)
  : Ghost (S.seq v_Tree)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (match v_node with
  | C_v_Tree_v_Nil -> S.empty
  | C_v_Tree_v_Node v__5f_node_5f_val v__5f_node_5f_left v__5f_node_5f_right -> (if ((R.decide ((match v__5f_node_5f_right with | C_v_Tree_v_Node _ _ _ -> true | _ -> false))) && (R.decide ((match v__5f_node_5f_left with | C_v_Tree_v_Node _ _ _ -> true | _ -> false)))) then (S.build ((S.build (S.empty) (v__5f_node_5f_right))) (v__5f_node_5f_left)) else (if (R.decide ((match v__5f_node_5f_right with | C_v_Tree_v_Node _ _ _ -> true | _ -> false))) then (S.build (S.empty) (v__5f_node_5f_right)) else (if (R.decide ((match v__5f_node_5f_left with | C_v_Tree_v_Node _ _ _ -> true | _ -> false))) then (S.build (S.empty) (v__5f_node_5f_left)) else S.empty))))

// Pending traversal reads the stack from its last element, just like pop.
let rec pending (stack:S.seq v_Tree) : GTot (S.seq v_Tree)
    (decreases (S.length stack)) =
  if S.length stack = 0 then S.empty else
  S.append (v_preorderTraversal (S.index stack (S.length stack-1)))
    (pending (S.take stack (S.length stack-1)))

let rec pending_append (xs ys:S.seq v_Tree)
  : Lemma (pending (S.append xs ys) == S.append (pending ys) (pending xs))
      (decreases (S.length ys)) =
  if S.length ys = 0 then (
    assert (S.equal (S.append xs ys) xs);
    assert (S.equal (S.append (pending ys) (pending xs)) (pending xs))
  ) else (
    assert (S.equal (S.take (S.append xs ys) (S.length xs + S.length ys - 1))
      (S.append xs (S.take ys (S.length ys-1))));
    pending_append xs (S.take ys (S.length ys-1));
    assert (S.equal (pending (S.append xs ys)) (S.append (pending ys) (pending xs)))
  )

let node_step (node:v_Tree)
  : Lemma (requires (node <> C_v_Tree_v_Nil))
      (ensures (v_preorderTraversal node == S.append (S.singleton node) (pending (v_childStack node)))) =
  match node with
  | C_v_Tree_v_Nil -> ()
  | C_v_Tree_v_Node _ left right ->
    (match left, right with
    | C_v_Tree_v_Nil, C_v_Tree_v_Nil -> ()
    | C_v_Tree_v_Nil, C_v_Tree_v_Node _ _ _ -> ()
    | C_v_Tree_v_Node _ _ _, C_v_Tree_v_Nil -> ()
    | C_v_Tree_v_Node _ _ _, C_v_Tree_v_Node _ _ _ -> ());
    assert (S.equal (v_preorderTraversal node) (S.append (S.singleton node) (pending (v_childStack node))))

let pending_step (stack:S.seq v_Tree)
  : Lemma (requires (S.length stack > 0 /\ S.index stack (S.length stack-1) <> C_v_Tree_v_Nil))
      (ensures (let node = S.index stack (S.length stack-1) in
        let rest = S.append (R.slice stack 0 (S.length stack-1)) (v_childStack node) in
        pending stack == S.append (S.singleton node) (pending rest))) =
  let node = S.index stack (S.length stack-1) in
  node_step node;
  assert (S.equal (R.slice stack 0 (S.length stack-1)) (S.take stack (S.length stack-1)));
  pending_append (S.take stack (S.length stack-1)) (v_childStack node);
  assert (S.equal (pending stack)
    (S.append (S.singleton node) (pending (S.append (S.take stack (S.length stack-1)) (v_childStack node)))))

let v_traverseBasic_5f_loop0_5f_measure (_:S.seq v_Tree) (stack:S.seq v_Tree)
  : GTot nat = S.length (pending stack)

let v_traverseBasic  (v_root:v_Tree)
  : Ghost (S.seq v_Tree)
      (requires (
        (match v_root with | C_v_Tree_v_Node _ _ _ -> true | _ -> false)
      ))
      (ensures (fun ls_result ->
        (S.equal (ls_result) ((v_preorderTraversal (v_root))))
      )) =
  let v_result_10 : (S.seq v_Tree) = S.empty in
  let v_stack_11 : (S.seq v_Tree) = (S.build (S.empty) (v_root)) in
  let rec ls_loop_12 (v_result_14:(S.seq v_Tree)) (v_stack_15:(S.seq v_Tree))
    : Ghost (S.seq v_Tree)
        (requires (
          (forall (v_s:v_Tree). ((S.contains v_stack_15 v_s) ==> (match v_s with | C_v_Tree_v_Node _ _ _ -> true | _ -> false)))
          /\ S.equal (S.append v_result_14 (pending v_stack_15)) (v_preorderTraversal v_root)
        ))
        (ensures (fun ls_result ->
          (S.equal (ls_result) ((v_preorderTraversal (v_root))))
        ))
        (decreases (R.nat_of_int (v_traverseBasic_5f_loop0_5f_measure (v_result_14) (v_stack_15)))) =
    if ((S.length (v_stack_15)) > (0)) then (
      pending_step v_stack_15;
      let v_current_17 : v_Tree = (S.index (v_stack_15) (((S.length (v_stack_15)) - (1)))) in
      let v__5f_t0_18 : (S.seq v_Tree) = (v_childStack (v_current_17)) in
      let v_stack_19 : (S.seq v_Tree) = (S.append ((R.slice (v_stack_15) ((0)) (((S.length (v_stack_15)) - (1))))) (v__5f_t0_18)) in
      let v_result_20 : (S.seq v_Tree) = (S.append (v_result_14) ((S.build (S.empty) (v_current_17)))) in
      (ls_loop_12 (v_result_20) (v_stack_19))
    ) else (
      v_result_14
    )
  in
  (ls_loop_12 (v_result_10) (v_stack_11))
