// Generated by lsc from readonlyArray.ts

function firstOrZero(xs: seq<int>): int
{
  if (|xs| > 0) then
    xs[0]
  else
    0
}

lemma firstOrZero_ensures(xs: seq<int>)
  ensures ((|xs| > 0) ==> (firstOrZero(xs) == xs[0]))
  ensures ((|xs| == 0) ==> (firstOrZero(xs) == 0))
{
}

function lengthOf<T>(xs: seq<T>): int
{
  |xs|
}

lemma lengthOf_ensures<T>(xs: seq<T>)
  ensures (lengthOf(xs) == |xs|)
{
}
