// Generated by lsc. Program source: readonlyArray.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MreadonlyArray_f3124246f977

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_firstOrZero  (v_xs:(S.seq int))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((S.length (v_xs)) > (0)) ==> (ls_result == (S.index (v_xs) ((0))))) /\ (((S.length (v_xs)) == (0)) ==> (ls_result == (0)))
      )) =
  (if ((S.length (v_xs)) > (0)) then (S.index (v_xs) ((0))) else (0))

let v_lengthOf (#v_T:Type) (v_xs:(S.seq v_T))
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (S.length (v_xs)))
      )) =
  (S.length (v_xs))
