/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Level where
  | low : Level
  | medium : Level
  | high : Level
deriving Repr, Inhabited, DecidableEq

structure Budgets where
  low : Int
  medium : Int
  high : Int
deriving Repr, Inhabited, DecidableEq

structure OptBudgets where
  low : Option Int
  high : Option Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def budgetFor (b : Budgets) (level : Level) : Int :=
  match level with
  | .low =>
    b.low
  | .medium =>
    b.medium
  | .high =>
    b.high

def maybeBudget (b : OptBudgets) (level : String) : Option Int :=
  if level = "low" then
    b.low
  else
    b.high

def lowOrMid (b : Budgets) (level : String) : Int :=
  if level = "low" then
    b.low
  else
    b.medium

end Pure
