/-
  Generated by lsc from recordIndexByEnum.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «recordIndexByEnum.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method budgetFor (b : Budgets) (level : Level) return (res : Int)
  ensures res = b.low ∨ res = b.medium ∨ res = b.high
  do
    return Pure.budgetFor b level

method maybeBudget (b : OptBudgets) (level : String) return (res : Option Int)
  ensures res = b.low ∨ res = b.high
  do
    return Pure.maybeBudget b level

method lowOrMid (b : Budgets) (level : String) return (res : Int)
  ensures res = b.low ∨ res = b.medium
  do
    return Pure.lowOrMid b level
