// Generated by lsc. Program source: recordIndexByEnum.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MrecordIndexByEnum_33399fc9592c

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Level  =
| C_v_Level_v_low : v_Level
| C_v_Level_v_medium : v_Level
| C_v_Level_v_high : v_Level

type v_Budgets  = {
  f_v_Budgets_v_low: int;
  f_v_Budgets_v_medium: int;
  f_v_Budgets_v_high: int;
}

type v_OptBudgets  = {
  f_v_OptBudgets_v_low: (option int);
  f_v_OptBudgets_v_high: (option int);
}

let v_budgetFor  (v_b:v_Budgets) (v_level:v_Level)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((ls_result == (v_b).f_v_Budgets_v_low) \/ (ls_result == (v_b).f_v_Budgets_v_medium)) \/ (ls_result == (v_b).f_v_Budgets_v_high))
      )) =
  (match v_level with
  | C_v_Level_v_low -> (v_b).f_v_Budgets_v_low
  | C_v_Level_v_medium -> (v_b).f_v_Budgets_v_medium
  | C_v_Level_v_high -> (v_b).f_v_Budgets_v_high)

let v_maybeBudget  (v_b:v_OptBudgets) (v_level:R.string)
  : Ghost (option int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == (v_b).f_v_OptBudgets_v_low) \/ (ls_result == (v_b).f_v_OptBudgets_v_high))
      )) =
  (if (R.decide ((S.equal (v_level) ((S.build ((S.build ((S.build (S.empty) (108))) (111))) (119)))))) then (v_b).f_v_OptBudgets_v_low else (v_b).f_v_OptBudgets_v_high)

let v_lowOrMid  (v_b:v_Budgets) (v_level:R.string)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((ls_result == (v_b).f_v_Budgets_v_low) \/ (ls_result == (v_b).f_v_Budgets_v_medium))
      )) =
  (if (R.decide ((S.equal (v_level) ((S.build ((S.build ((S.build (S.empty) (108))) (111))) (119)))))) then (v_b).f_v_Budgets_v_low else (v_b).f_v_Budgets_v_medium)
