// Generated by lsc. Program source: resultPipeline.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MresultPipeline_29f4310d0153

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Result (v_A:Type) (v_E:Type) =
| C_v_Result_v_Success : v_A -> v_Result v_A v_E
| C_v_Result_v_Failure : v_E -> v_Result v_A v_E

type v_Order  = {
  f_v_Order_v_quantity: int;
  f_v_Order_v_unitPrice: int;
}

let v_succeed (#v_A:Type) (#v_E:Type) (v_success:v_A)
  : Ghost (v_Result v_A v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (C_v_Result_v_Success (v_success))

let v_fail (#v_A:Type) (#v_E:Type) (v_failure:v_E)
  : Ghost (v_Result v_A v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (C_v_Result_v_Failure (v_failure))

let v_map (#v_A:Type) (#v_B:Type) (#v_E:Type) (v_self:(v_Result v_A v_E)) (v_f:(v_A -> GTot v_B))
  : Ghost (v_Result v_B v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((match v_self with | C_v_Result_v_Failure _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) == (match v_self with | C_v_Result_v_Failure ls_field -> ls_field)))) /\ ((match v_self with | C_v_Result_v_Success _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))))
      )) =
  (match v_self with
  | C_v_Result_v_Failure v__5f_self_5f_failure -> (v_fail (v__5f_self_5f_failure))
  | _ -> (v_succeed ((v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))))

let v_flatMap (#v_A:Type) (#v_B:Type) (#v_E:Type) (v_self:(v_Result v_A v_E)) (v_f:(v_A -> GTot (v_Result v_B v_E)))
  : Ghost (v_Result v_B v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((match v_self with | C_v_Result_v_Failure _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) == (match v_self with | C_v_Result_v_Failure ls_field -> ls_field)))) /\ ((match v_self with | C_v_Result_v_Success _ -> true | _ -> false) ==> (ls_result == (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field)))))
      )) =
  (match v_self with
  | C_v_Result_v_Failure v__5f_self_5f_failure -> (v_fail (v__5f_self_5f_failure))
  | _ -> (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))

let v_checkQuantity  (v_order:v_Order)
  : Ghost (v_Result v_Order R.string)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_quantity <= (0)) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (S.equal ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field)) ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (113))) (117))) (97))) (110))) (116))) (105))) (116))) (121)))))) /\ (((v_order).f_v_Order_v_quantity > (0)) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == v_order)))
      )) =
  (if ((v_order).f_v_Order_v_quantity <= (0)) then (v_fail ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (113))) (117))) (97))) (110))) (116))) (105))) (116))) (121)))) else (v_succeed (v_order)))

let v_checkPrice  (v_order:v_Order)
  : Ghost (v_Result v_Order R.string)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_unitPrice < (0)) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (S.equal ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field)) ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (112))) (114))) (105))) (99))) (101)))))) /\ (((v_order).f_v_Order_v_unitPrice >= (0)) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == v_order)))
      )) =
  (if ((v_order).f_v_Order_v_unitPrice < (0)) then (v_fail ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (112))) (114))) (105))) (99))) (101)))) else (v_succeed (v_order)))

let v_priceOrder  (v_order:v_Order)
  : Ghost (v_Result int R.string)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_quantity <= (0)) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (S.equal ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field)) ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (113))) (117))) (97))) (110))) (116))) (105))) (116))) (121)))))) /\ (((v_order).f_v_Order_v_quantity > (0)) /\ ((v_order).f_v_Order_v_unitPrice < (0)) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (S.equal ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field)) ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build ((S.build (S.empty) (105))) (110))) (118))) (97))) (108))) (105))) (100))) (32))) (112))) (114))) (105))) (99))) (101)))))) /\ ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) <==> (((v_order).f_v_Order_v_quantity > (0)) /\ ((v_order).f_v_Order_v_unitPrice >= (0)))) /\ ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == ((v_order).f_v_Order_v_quantity * (v_order).f_v_Order_v_unitPrice)))
      )) =
  (let v_checked_23 = (v_flatMap ((v_checkQuantity (v_order))) (v_checkPrice)) in
  (v_map (v_checked_23) ((fun (v_valid:v_Order) ->
    ((v_valid).f_v_Order_v_quantity * (v_valid).f_v_Order_v_unitPrice)))))
