// Generated by lsc from resultTypedErrors.ts

datatype Result<A, E> = Success(success: A) | Failure(failure: E)

datatype QuantityError = InvalidQuantity(quantity: int)

datatype PriceError = InvalidPrice(unitPrice: int)

datatype OrderError = InvalidQuantity(quantity: int) | InvalidPrice(unitPrice: int)

datatype Order = Order(quantity: int, unitPrice: int)

function succeed<A, E>(success: A): Result<A, E>
{
  Success(success)
}

function fail<A, E>(failure: E): Result<A, E>
{
  Failure(failure)
}

function map_<A, B, E>(self: Result<A, E>, f: (A) -> B): Result<B, E>
{
  match self {
    case Failure(i_self_failure) =>
      fail(i_self_failure)
    case _ =>
      succeed(f(self.success))
  }
}

lemma map_ensures<A, B, E>(self: Result<A, E>, f: (A) -> B)
  ensures (self.Failure? ==> (map_(self, f).Failure? && (map_(self, f).failure == self.failure)))
  ensures (self.Success? ==> (map_(self, f).Success? && (map_(self, f).success == f(self.success))))
{
}

function flatMap<A, B, E>(self: Result<A, E>, f: (A) -> Result<B, E>): Result<B, E>
{
  match self {
    case Failure(i_self_failure) =>
      fail(i_self_failure)
    case _ =>
      f(self.success)
  }
}

lemma flatMap_ensures<A, B, E>(self: Result<A, E>, f: (A) -> Result<B, E>)
  ensures (self.Failure? ==> (flatMap(self, f).Failure? && (flatMap(self, f).failure == self.failure)))
  ensures (self.Success? ==> (flatMap(self, f) == f(self.success)))
{
}

function checkQuantity(order: Order): Result<Order, QuantityError>
{
  if (order.quantity <= 0) then
    fail(QuantityError.InvalidQuantity(order.quantity))
  else
    succeed(order)
}

lemma checkQuantity_ensures(order: Order)
  ensures ((order.quantity <= 0) ==> ((checkQuantity(order).Failure? && checkQuantity(order).failure.InvalidQuantity?) && (checkQuantity(order).failure.quantity == order.quantity)))
  ensures ((order.quantity > 0) ==> (checkQuantity(order).Success? && (checkQuantity(order).success == order)))
{
}

function checkPrice(order: Order): Result<Order, PriceError>
{
  if (order.unitPrice < 0) then
    fail(PriceError.InvalidPrice(order.unitPrice))
  else
    succeed(order)
}

lemma checkPrice_ensures(order: Order)
  ensures ((order.unitPrice < 0) ==> ((checkPrice(order).Failure? && checkPrice(order).failure.InvalidPrice?) && (checkPrice(order).failure.unitPrice == order.unitPrice)))
  ensures ((order.unitPrice >= 0) ==> (checkPrice(order).Success? && (checkPrice(order).success == order)))
{
}

function priceOrder(order: Order): Result<int, OrderError>
{
  var checked := flatMap((var i_widenValue0 := checkQuantity(order); (match i_widenValue0 { case Success(i__widenValue0_success) => Success(i__widenValue0_success) case Failure(i__widenValue0_failure) => Failure((var i_widenValue1 := i__widenValue0_failure; (match i_widenValue1 { case InvalidQuantity(i__widenValue1_quantity) => OrderError.InvalidQuantity(i__widenValue1_quantity) }))) })), (var i_widenCallback2 := checkPrice; (i_widenArg3: Order) => (var i_widenValue4 := i_widenCallback2(i_widenArg3); (match i_widenValue4 { case Success(i__widenValue4_success) => Success(i__widenValue4_success) case Failure(i__widenValue4_failure) => Failure((var i_widenValue5 := i__widenValue4_failure; (match i_widenValue5 { case InvalidPrice(i__widenValue5_unitPrice) => OrderError.InvalidPrice(i__widenValue5_unitPrice) }))) }))));
  map_(checked, (valid: Order) => (valid.quantity * valid.unitPrice))
}

lemma priceOrder_ensures(order: Order)
  ensures ((order.quantity <= 0) ==> ((priceOrder(order).Failure? && priceOrder(order).failure.InvalidQuantity?) && (priceOrder(order).failure.quantity == order.quantity)))
  ensures ((order.quantity > 0) ==> (order.unitPrice < 0) ==> ((priceOrder(order).Failure? && priceOrder(order).failure.InvalidPrice?) && (priceOrder(order).failure.unitPrice == order.unitPrice)))
  ensures (priceOrder(order).Success? <==> ((order.quantity > 0) && (order.unitPrice >= 0)))
  ensures (priceOrder(order).Success? ==> (priceOrder(order).success == (order.quantity * order.unitPrice)))
{
  checkQuantity_ensures(order);
  checkPrice_ensures(order);

}
