// Generated by lsc from resultPipeline.ts

datatype Result<A, E> = Success(success: A) | Failure(failure: E)

datatype Order = Order(quantity: int, unitPrice: int)

function succeed<A, E>(success: A): Result<A, E>
{
  Success(success)
}

function fail<A, E>(failure: E): Result<A, E>
{
  Failure(failure)
}

function map_<A, B, E>(self: Result<A, E>, f: (A) -> B): Result<B, E>
{
  match self {
    case Failure(i_self_failure) =>
      fail(i_self_failure)
    case _ =>
      succeed(f(self.success))
  }
}

lemma map_ensures<A, B, E>(self: Result<A, E>, f: (A) -> B)
  ensures (self.Failure? ==> (map_(self, f).Failure? && (map_(self, f).failure == self.failure)))
  ensures (self.Success? ==> (map_(self, f).Success? && (map_(self, f).success == f(self.success))))
{
}

function flatMap<A, B, E>(self: Result<A, E>, f: (A) -> Result<B, E>): Result<B, E>
{
  match self {
    case Failure(i_self_failure) =>
      fail(i_self_failure)
    case _ =>
      f(self.success)
  }
}

lemma flatMap_ensures<A, B, E>(self: Result<A, E>, f: (A) -> Result<B, E>)
  ensures (self.Failure? ==> (flatMap(self, f).Failure? && (flatMap(self, f).failure == self.failure)))
  ensures (self.Success? ==> (flatMap(self, f) == f(self.success)))
{
}

function checkQuantity(order: Order): Result<Order, string>
{
  if (order.quantity <= 0) then
    fail("invalid quantity")
  else
    succeed(order)
}

lemma checkQuantity_ensures(order: Order)
  ensures ((order.quantity <= 0) ==> (checkQuantity(order).Failure? && (checkQuantity(order).failure == "invalid quantity")))
  ensures ((order.quantity > 0) ==> (checkQuantity(order).Success? && (checkQuantity(order).success == order)))
{
}

function checkPrice(order: Order): Result<Order, string>
{
  if (order.unitPrice < 0) then
    fail("invalid price")
  else
    succeed(order)
}

lemma checkPrice_ensures(order: Order)
  ensures ((order.unitPrice < 0) ==> (checkPrice(order).Failure? && (checkPrice(order).failure == "invalid price")))
  ensures ((order.unitPrice >= 0) ==> (checkPrice(order).Success? && (checkPrice(order).success == order)))
{
}

function priceOrder(order: Order): Result<int, string>
{
  var checked := flatMap(checkQuantity(order), checkPrice);
  map_(checked, (valid: Order) => (valid.quantity * valid.unitPrice))
}

lemma priceOrder_ensures(order: Order)
  ensures ((order.quantity <= 0) ==> (priceOrder(order).Failure? && (priceOrder(order).failure == "invalid quantity")))
  ensures ((order.quantity > 0) ==> (order.unitPrice < 0) ==> (priceOrder(order).Failure? && (priceOrder(order).failure == "invalid price")))
  ensures (priceOrder(order).Success? <==> ((order.quantity > 0) && (order.unitPrice >= 0)))
  ensures (priceOrder(order).Success? ==> (priceOrder(order).success == (order.quantity * order.unitPrice)))
{
}
