// Generated by lsc. Program source: resultTypedErrors.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MresultTypedErrors_b83363b83143

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

noeq type v_Result (v_A:Type) (v_E:Type) =
| C_v_Result_v_Success : v_A -> v_Result v_A v_E
| C_v_Result_v_Failure : v_E -> v_Result v_A v_E

type v_QuantityError  =
| C_v_QuantityError_v_InvalidQuantity : int -> v_QuantityError

type v_PriceError  =
| C_v_PriceError_v_InvalidPrice : int -> v_PriceError

type v_OrderError  =
| C_v_OrderError_v_InvalidQuantity : int -> v_OrderError
| C_v_OrderError_v_InvalidPrice : int -> v_OrderError

type v_Order  = {
  f_v_Order_v_quantity: int;
  f_v_Order_v_unitPrice: int;
}

let v_succeed (#v_A:Type) (#v_E:Type) (v_success:v_A)
  : Ghost (v_Result v_A v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (C_v_Result_v_Success (v_success))

let v_fail (#v_A:Type) (#v_E:Type) (v_failure:v_E)
  : Ghost (v_Result v_A v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (C_v_Result_v_Failure (v_failure))

let v_map (#v_A:Type) (#v_B:Type) (#v_E:Type) (v_self:(v_Result v_A v_E)) (v_f:(v_A -> GTot v_B))
  : Ghost (v_Result v_B v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((match v_self with | C_v_Result_v_Failure _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) == (match v_self with | C_v_Result_v_Failure ls_field -> ls_field)))) /\ ((match v_self with | C_v_Result_v_Success _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))))
      )) =
  (match v_self with
  | C_v_Result_v_Failure v__5f_self_5f_failure -> (v_fail (v__5f_self_5f_failure))
  | _ -> (v_succeed ((v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))))

let v_flatMap (#v_A:Type) (#v_B:Type) (#v_E:Type) (v_self:(v_Result v_A v_E)) (v_f:(v_A -> GTot (v_Result v_B v_E)))
  : Ghost (v_Result v_B v_E)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        ((match v_self with | C_v_Result_v_Failure _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) == (match v_self with | C_v_Result_v_Failure ls_field -> ls_field)))) /\ ((match v_self with | C_v_Result_v_Success _ -> true | _ -> false) ==> (ls_result == (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field)))))
      )) =
  (match v_self with
  | C_v_Result_v_Failure v__5f_self_5f_failure -> (v_fail (v__5f_self_5f_failure))
  | _ -> (v_f ((match v_self with | C_v_Result_v_Success ls_field -> ls_field))))

let v_checkQuantity  (v_order:v_Order)
  : Ghost (v_Result v_Order v_QuantityError)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_quantity <= (0)) ==> (((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_QuantityError_v_InvalidQuantity _ -> true | _ -> false)) /\ ((match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_QuantityError_v_InvalidQuantity ls_field -> ls_field) == (v_order).f_v_Order_v_quantity))) /\ (((v_order).f_v_Order_v_quantity > (0)) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == v_order)))
      )) =
  (if ((v_order).f_v_Order_v_quantity <= (0)) then (v_fail ((C_v_QuantityError_v_InvalidQuantity ((v_order).f_v_Order_v_quantity)))) else (v_succeed (v_order)))

let v_checkPrice  (v_order:v_Order)
  : Ghost (v_Result v_Order v_PriceError)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_unitPrice < (0)) ==> (((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_PriceError_v_InvalidPrice _ -> true | _ -> false)) /\ ((match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_PriceError_v_InvalidPrice ls_field -> ls_field) == (v_order).f_v_Order_v_unitPrice))) /\ (((v_order).f_v_Order_v_unitPrice >= (0)) ==> ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) /\ ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == v_order)))
      )) =
  (if ((v_order).f_v_Order_v_unitPrice < (0)) then (v_fail ((C_v_PriceError_v_InvalidPrice ((v_order).f_v_Order_v_unitPrice)))) else (v_succeed (v_order)))

let v_priceOrder  (v_order:v_Order)
  : Ghost (v_Result int v_OrderError)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (((v_order).f_v_Order_v_quantity <= (0)) ==> (((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_OrderError_v_InvalidQuantity _ -> true | _ -> false)) /\ ((match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_OrderError_v_InvalidQuantity ls_field -> ls_field) == (v_order).f_v_Order_v_quantity))) /\ (((v_order).f_v_Order_v_quantity > (0)) /\ ((v_order).f_v_Order_v_unitPrice < (0)) ==> (((match ls_result with | C_v_Result_v_Failure _ -> true | _ -> false) /\ (match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_OrderError_v_InvalidPrice _ -> true | _ -> false)) /\ ((match (match ls_result with | C_v_Result_v_Failure ls_field -> ls_field) with | C_v_OrderError_v_InvalidPrice ls_field -> ls_field) == (v_order).f_v_Order_v_unitPrice))) /\ ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) <==> (((v_order).f_v_Order_v_quantity > (0)) /\ ((v_order).f_v_Order_v_unitPrice >= (0)))) /\ ((match ls_result with | C_v_Result_v_Success _ -> true | _ -> false) ==> ((match ls_result with | C_v_Result_v_Success ls_field -> ls_field) == ((v_order).f_v_Order_v_quantity * (v_order).f_v_Order_v_unitPrice)))
      )) =
  (let v_checked_23 = (v_flatMap ((let v__5f_widenValue0_24 = (v_checkQuantity (v_order)) in
  (match v__5f_widenValue0_24 with
  | C_v_Result_v_Success v__5f__5f_widenValue0_5f_success -> (C_v_Result_v_Success (v__5f__5f_widenValue0_5f_success))
  | C_v_Result_v_Failure v__5f__5f_widenValue0_5f_failure -> (C_v_Result_v_Failure ((let v__5f_widenValue1_27 = v__5f__5f_widenValue0_5f_failure in
  (match v__5f_widenValue1_27 with
  | C_v_QuantityError_v_InvalidQuantity v__5f__5f_widenValue1_5f_quantity -> (C_v_OrderError_v_InvalidQuantity (v__5f__5f_widenValue1_5f_quantity))))))))) ((let v__5f_widenCallback2_29 = v_checkPrice in
  (fun (v__5f_widenArg3:v_Order) ->
    (let v__5f_widenValue4_31 = (v__5f_widenCallback2_29 (v__5f_widenArg3)) in
    (match v__5f_widenValue4_31 with
    | C_v_Result_v_Success v__5f__5f_widenValue4_5f_success -> (C_v_Result_v_Success (v__5f__5f_widenValue4_5f_success))
    | C_v_Result_v_Failure v__5f__5f_widenValue4_5f_failure -> (C_v_Result_v_Failure ((let v__5f_widenValue5_34 = v__5f__5f_widenValue4_5f_failure in
    (match v__5f_widenValue5_34 with
    | C_v_PriceError_v_InvalidPrice v__5f__5f_widenValue5_5f_unitPrice -> (C_v_OrderError_v_InvalidPrice (v__5f__5f_widenValue5_5f_unitPrice)))))))))))) in
  (v_map (v_checked_23) ((fun (v_valid:v_Order) ->
    ((v_valid).f_v_Order_v_quantity * (v_valid).f_v_Order_v_unitPrice)))))
