// Generated by lsc. Program source: safeSlice.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MsafeSlice_a3196887a6ee

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_sliceNegativeStart  ()
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (S.equal (ls_result) ((S.build (S.empty) ((2)))))
      )) =
  (R.slice ((S.build ((S.build (S.empty) ((1)))) ((2)))) ((-1)) ((2)))

let v_sliceNegativeEnd  ()
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (S.equal (ls_result) ((S.build (S.empty) ((1)))))
      )) =
  (R.slice ((S.build ((S.build (S.empty) ((1)))) ((2)))) ((0)) ((-1)))

let v_sliceNegativeBounds  ()
  : Ghost (S.seq int)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (S.equal (ls_result) ((S.build ((S.build (S.empty) ((2)))) ((3)))))
      )) =
  (R.slice ((S.build ((S.build ((S.build ((S.build (S.empty) ((1)))) ((2)))) ((3)))) ((4)))) ((-3)) ((-1)))
