/-
  Generated by lsc from setFromArray.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «setFromArray.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method dedupSize (arr : Array Int) return (res : Int)
  do
    return Pure.dedupSize arr

method member (arr : Array Int) (x : Int) return (res : Bool)
  ensures res ↔ (∃ i : Nat, i < arr.size ∧ arr[i]! = x)
  do
    return Pure.member arr x
