// Generated by lsc from setFromArray.ts

function SetFromSeq<T(==)>(s: seq<T>): set<T> { set x | x in s }

function dedupSize(arr: seq<int>): int
{
  var s := SetFromSeq(arr);
  |s|
}

function member(arr: seq<int>, x: int): bool
{
  var s := SetFromSeq(arr);
  (x in s)
}

lemma member_ensures(arr: seq<int>, x: int)
  ensures (member(arr, x) <==> exists i: nat :: ((i < |arr|) && (arr[i] == x)))
{
}
