/-
  Generated by lsc from spec.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «spec.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method evalPartial (e : Expr) return (res : Int)
  ensures match e with | .lit _val => res = _val | _ => true
  ensures match e with | .add _a _b => res = _a + _b | _ => true
  do
    return Pure.evalPartial e

method evalSwitch (e : Expr) return (res : Int)
  ensures match e with | .lit _val => res = _val | _ => true
  ensures match e with | .add _a _b => res = _a + _b | _ => true
  ensures match e with | .neg _inner => res = 0 - _inner | _ => true
  do
    return Pure.evalSwitch e

method isHighPriority (p : Priority) return (res : Bool)
  ensures p = .high → res = true
  ensures p ≠ .high → res = false
  do
    return Pure.isHighPriority p

method defaultConfig  return (res : Config)
  ensures res.threshold = 0
  ensures res.enabled = true
  do
    return Pure.defaultConfig 

method withThreshold (c : Config) (t : Nat) return (res : Config)
  ensures res.threshold = t
  ensures res.enabled = c.enabled
  do
    return Pure.withThreshold c t

method clampTernary (x : Int) (lo : Int) (hi : Int) return (res : Int)
  require lo ≤ hi
  ensures res ≥ lo
  ensures res ≤ hi
  do
    return Pure.clampTernary x lo hi

method demoteOnFail (p : Priority) (ok : Bool) return (res : Priority)
  do
    return Pure.demoteOnFail p ok

method makeHighItem (v : Int) return (res : PriorityItem)
  do
    return Pure.makeHighItem v

method midpoint (lo : Int) (hi : Int) return (res : Int)
  ensures res = (lo + hi) / 2
  do
    return Pure.midpoint lo hi

method wrapOne (x : Int) return (res : Array Int)
  ensures res.size = 1
  do
    return Pure.wrapOne x

method threeElems (a : Int) (b : Int) (c : Int) return (res : Array Int)
  ensures res.size = 3
  do
    return Pure.threeElems a b c

method append (arr : Array Int) (x : Int) return (res : Array Int)
  do
    return Pure.append arr x

method doubleAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.doubleAll arr

method keepPositive (arr : Array Int) return (res : Array Int)
  do
    return Pure.keepPositive arr

method allBelow (arr : Array Int) (cap : Int) return (res : Bool)
  do
    return Pure.allBelow arr cap

method anyNegative (arr : Array Int) return (res : Bool)
  do
    return Pure.anyNegative arr

method negate (x : Int) return (res : Int)
  ensures res = 0 - x
  do
    return Pure.negate x

method negateAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.negateAll arr

method hasValue (arr : Array Int) (v : Int) return (res : Bool)
  do
    return Pure.hasValue arr v

method replaceAt (arr : Array Int) (i : Nat) (v : Int) return (res : Array Int)
  do
    return Pure.replaceAt arr i v

method replaceAtInt (arr : Array Int) (i : Int) (v : Int) return (res : Array Int)
  do
    return Pure.replaceAtInt arr i v

method findSubstr (s : String) (sub : String) return (res : Int)
  do
    return Pure.findSubstr s sub

method getSlice (s : String) (start : Nat) («end» : Nat) return (res : String)
  do
    return Pure.getSlice s start «end»

method countAbove (arr : Array Int) (threshold : Int) return (res : Int)
  ensures res ≤ arr.size
  do
    let mut count : Nat := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant i ≤ arr.size
      invariant count ≤ i
      decreasing arr.size - i
    do
      if arr[i]! > threshold then
        count := count + 1
      i := i + 1
    return count

method search (arr : Array Int) (target : Int) return (res : Int)
  ensures res ≥ -1
  ensures res < arr.size
  ensures res ≥ 0 → arr[res.toNat]! = target
  ensures arr.size > 0 → res = -1 → ∀ k : Nat, k < arr.size → arr[k]! ≠ target
  do
    let mut result : Int := -1
    let mut i : Nat := 0
    while i < arr.size
      invariant i ≤ arr.size
      invariant result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target
      invariant ∀ k : Nat, k < i → arr[k]! ≠ target
      done_with result ≠ -1 ∨ i ≥ arr.size
      decreasing arr.size - i
    do
      if arr[i]! = target then
        result := i
        break
      i := i + 1
    return result

method sumSearchResults (arr : Array Int) (a : Int) (b : Int) return (res : Int)
  do
    let mut sum : Int := 0
    let _t0 ← search arr a
    let _t1 ← search arr b
    sum := _t0 + _t1
    return sum

method forOfContains (arr : Array Int) (target : Int) return (res : Bool)
  ensures res = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
  do
    let mut found : Bool := false
    for _x_idx in [:arr.size]
      invariant found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target
      invariant found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
    do
      let x := arr[_x_idx]!
      if x = target then
        found := true
        break
    return found
