/-
  Generated by lsc from spec.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «spec.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method evalPartial (e : Expr) return (res : Int)
  ensures (match e with | .lit _e_val => res = _e_val | _ => true)
  ensures (match e with | .add _e_a _e_b => res = _e_a + _e_b | _ => true)
  do
    return Pure.evalPartial e

method evalSwitch (e : Expr) return (res : Int)
  ensures (match e with | .lit _e_val => res = _e_val | _ => true)
  ensures (match e with | .add _e_a _e_b => res = _e_a + _e_b | _ => true)
  ensures (match e with | .neg _e_inner => res = 0 - _e_inner | _ => true)
  do
    return Pure.evalSwitch e

method isHighPriority (p : Priority) return (res : Bool)
  ensures p = Priority.high → res = true
  ensures p ≠ Priority.high → res = false
  do
    return Pure.isHighPriority p

method defaultConfig  return (res : Config)
  ensures res.threshold = 0
  ensures res.enabled = true
  do
    return Pure.defaultConfig 

method withThreshold (c : Config) (t : Nat) return (res : Config)
  ensures res.threshold = t
  ensures res.enabled = c.enabled
  do
    return Pure.withThreshold c t

method clampTernary (x : Int) (lo : Int) (hi : Int) return (res : Int)
  require lo ≤ hi
  ensures res ≥ lo
  ensures res ≤ hi
  do
    return Pure.clampTernary x lo hi

method demoteOnFail (p : Priority) (ok : Bool) return (res : Priority)
  do
    return Pure.demoteOnFail p ok

method makeHighItem (v : Int) return (res : PriorityItem)
  do
    return Pure.makeHighItem v

method midpoint (lo : Int) (hi : Int) return (res : Int)
  ensures res = (lo + hi) / 2
  do
    return Pure.midpoint lo hi

method wrapOne (x : Int) return (res : Array Int)
  ensures res.size = 1
  do
    return Pure.wrapOne x

method threeElems (a : Int) (b : Int) (c : Int) return (res : Array Int)
  ensures res.size = 3
  do
    return Pure.threeElems a b c

method append (arr : Array Int) (x : Int) return (res : Array Int)
  do
    return Pure.append arr x

method doubleAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.doubleAll arr

method keepPositive (arr : Array Int) return (res : Array Int)
  do
    return Pure.keepPositive arr

method allBelow (arr : Array Int) (cap : Int) return (res : Bool)
  do
    return Pure.allBelow arr cap

method anyNegative (arr : Array Int) return (res : Bool)
  do
    return Pure.anyNegative arr

method negate (x : Int) return (res : Int)
  ensures res = 0 - x
  do
    return Pure.negate x

method negateAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.negateAll arr

method hasValue (arr : Array Int) (v : Int) return (res : Bool)
  do
    return Pure.hasValue arr v

method replaceAt (arr : Array Int) (i : Nat) (v : Int) return (res : Array Int)
  require i < arr.size
  do
    return Pure.replaceAt arr i v

method replaceAtInt (arr : Array Int) (i : Int) (v : Int) return (res : Array Int)
  require i ≥ 0
  require i < arr.size
  do
    return Pure.replaceAtInt arr i v

method findSubstr (s : String) (sub : String) return (res : Int)
  do
    return Pure.findSubstr s sub

method getSlice (s : String) (start : Nat) («end» : Nat) return (res : String)
  require start ≤ «end»
  require «end» ≤ s.length
  do
    return Pure.getSlice s start «end»

method countAbove (arr : Array Int) (threshold : Int) return (res : Int)
  ensures res ≤ arr.size
  do
    let mut count : Nat := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant i ≤ arr.size
      invariant count ≤ i
      decreasing arr.size - i
    do
      if arr[i]! > threshold then
        count := count + 1
      i := i + 1
    return count

method search (arr : Array Int) (target : Int) return (res : Int)
  ensures res ≥ -1
  ensures res < arr.size
  ensures res ≥ 0 → arr[res.toNat]! = target
  ensures arr.size > 0 → res = -1 → ∀ k : Nat, k < arr.size → arr[k]! ≠ target
  do
    let mut result : Int := -1
    let mut i : Nat := 0
    while i < arr.size
      invariant i ≤ arr.size
      invariant result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target
      invariant ∀ k : Nat, k < i → arr[k]! ≠ target
      done_with result ≠ -1 ∨ i ≥ arr.size
      decreasing arr.size - i
    do
      if arr[i]! = target then
        result := i
        break
      i := i + 1
    return result

method sumSearchResults (arr : Array Int) (a : Int) (b : Int) return (res : Int)
  do
    let mut sum : Int := 0
    let _t0 ← search arr a
    let _t1 ← search arr b
    sum := _t0 + _t1
    return sum

method forOfContains (arr : Array Int) (target : Int) return (res : Bool)
  ensures res = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
  do
    let mut found : Bool := false
    for _x_idx in [:arr.size]
      invariant _x_idx ≤ arr.size
      invariant found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target
      invariant found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
    do
      let x := arr[_x_idx]!
      if x = target then
        found := true
        break
    return found

method clampedItem (x : Int) return (res : PriorityItem)
  ensures res.level = Priority.high
  do
    let mut tmp : Int := x
    let _t2 ← clampTernary tmp 0 100
    return { level := Priority.high, value := _t2 }

method clampedMidpoint (a : Int) (b : Int) return (res : Int)
  require a ≤ b
  ensures res ≥ a
  ensures res ≤ b
  do
    let _t3 ← midpoint a b
    let mut mid : Int := _t3
    let _t4 ← clampTernary mid a b
    return _t4

method deepAccess (t : Tree) return (res : Int)
  ensures (match t.middle with | .some _t_middle_val => (match _t_middle_val.leaf with | .some _t_middle_leaf_val => res = _t_middle_leaf_val.value | .none => true) | .none => true)
  ensures (match t.middle with | .some _ => false | .none => true) → res = 0
  do
    return Pure.deepAccess t

method ocField (o : Option Outer) return (res : Option Inner)
  do
    return Pure.ocField o

method ocChain (o : Option Outer) return (res : Option Int)
  do
    return Pure.ocChain o

method ocMethodCall (s : Option (Std.HashSet String)) (k : String) return (res : Option Bool)
  do
    return Pure.ocMethodCall s k

method ocIndex (m : Option (Std.HashMap String String)) (k : String) return (res : Option String)
  do
    return Pure.ocIndex m k

method nullishVar (o : Option Inner) (fallback : Int) return (res : Int)
  do
    return Pure.nullishVar o fallback

method nullishMapGet (m : Std.HashMap String Int) (k : String) (fallback : Int) return (res : Int)
  do
    return Pure.nullishMapGet m k fallback

method negVar (o : Option Inner) (fallback : Int) return (res : Int)
  do
    return Pure.negVar o fallback

method negField (o : Outer) (fallback : Int) return (res : Int)
  do
    return Pure.negField o fallback

method nestedAndTernary (o : Option Outer) (fallback : Int) return (res : Int)
  do
    return Pure.nestedAndTernary o fallback
