/-
  Generated by lsc from spreadMerge.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «spreadMerge.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method mergeComplete (base : Budgets) (over : Budgets) return (res : Budgets)
  ensures res.low = over.low
  ensures res.high = over.high
  do
    return Pure.mergeComplete base over

method withDefaults (base : Config) (over : Config) return (res : Config)
  ensures (match over.retries with | .some _ => false | .none => true) → res.retries = base.retries
  ensures (match over.retries with | .some _over_retries_val => (match res.retries with | .some _value => _value == _over_retries_val | .none => false) | .none => true)
  ensures (match over.timeout with | .some _ => false | .none => true) → res.timeout = base.timeout
  ensures (match over.timeout with | .some _over_timeout_val => (match res.timeout with | .some _value => _value == _over_timeout_val | .none => false) | .none => true)
  do
    return Pure.withDefaults base over

method applyOverride (base : Budgets) (over : Option Budgets) return (res : Budgets)
  ensures (match over with | .some _ => false | .none => true) → res = base
  ensures (match over with | .some _over_val => res = _over_val | .none => true)
  do
    return Pure.applyOverride base over

method mergeChain (a : Budgets) (b : Budgets) (c : Budgets) return (res : Budgets)
  ensures res.low = c.low
  ensures res.high = c.high
  do
    return Pure.mergeChain a b c
