/-
  Generated by lsc from spreadMerge.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «spreadMerge.types»

set_option velvet.semantics.termination "total"

method mergeComplete (base : Budgets) (over : Budgets) returns (res : Budgets)
  ensures ensures_1: (res.low = over.low : Prop)
  ensures ensures_2: (res.high = over.high : Prop)
  do
    return Pure.mergeComplete base over

method withDefaults (base : Config) (over : Config) returns (res : Config)
  ensures ensures_1: ((match over.retries with | .some _ => false | .none => true) → res.retries = base.retries : Prop)
  ensures ensures_2: ((match over.retries with | .some _over_retries_val => (match res.retries with | .some _value => _value == _over_retries_val | .none => false) | .none => true) : Prop)
  ensures ensures_3: ((match over.timeout with | .some _ => false | .none => true) → res.timeout = base.timeout : Prop)
  ensures ensures_4: ((match over.timeout with | .some _over_timeout_val => (match res.timeout with | .some _value => _value == _over_timeout_val | .none => false) | .none => true) : Prop)
  do
    return Pure.withDefaults base over

method applyOverride (base : Budgets) (over : Option Budgets) returns (res : Budgets)
  ensures ensures_1: ((match over with | .some _ => false | .none => true) → res = base : Prop)
  ensures ensures_2: ((match over with | .some _over_val => res = _over_val | .none => true) : Prop)
  do
    return Pure.applyOverride base over

method mergeChain (a : Budgets) (b : Budgets) (c : Budgets) returns (res : Budgets)
  ensures ensures_1: (res.low = c.low : Prop)
  ensures ensures_2: (res.high = c.high : Prop)
  do
    return Pure.mergeChain a b c
