// Generated by lsc from swap.ts

method swap(arr: seq<int>, i: nat, j: nat) returns (res: seq<int>)
  requires (i < |arr|)
  requires (j < |arr|)
  ensures (|res| == |arr|)
  ensures (res[i] == arr[j])
  ensures (res[j] == arr[i])
{
  var result := arr;
  var tmp := result[i];
  result := result[i := result[j]];
  result := result[j := tmp];
  return result;
}
