// Generated by lsc from switchLambda.ts

datatype Msg = user(text: string) | system(code: int)

datatype UserMsg = UserMsg(role: string, text: string)

datatype SysMsg = SysMsg(role: string, code: int)

function priorities(msgs: seq<Msg>): seq<int>
{
  Std.Collections.Seq.Map((m: Msg) => (match m { case user(i_m_text) => 1 case system(i_m_code) => 2 }), msgs)
}

lemma priorities_ensures(msgs: seq<Msg>)
  ensures (|priorities(msgs)| == |msgs|)
{
}
