/-
  Generated by lsc from templateConcat.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «templateConcat.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method noSep (a : Int) (b : Int) return (res : String)
  do
    return Pure.noSep a b

method bracketed (a : Int) (b : Int) return (res : Int)
  ensures res ≥ 4
  do
    return Pure.bracketed a b
