/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def noSep (a : Int) (b : Int) : String :=
  "" ++ toString a ++ toString b

def bracketed (a : Int) (b : Int) : Int :=
  ("[" ++ toString a ++ "][" ++ toString b ++ "]").length

end Pure
