/-
  Generated by lsc from toposort.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «toposort.spec»

set_option velvet.semantics.termination "total"

method topologicalSort (nodeIds : Array String) (deps : Std.HashMap String (Std.HashSet String)) returns (res : Array String)
  requires require_1: (allDistinct nodeIds nodeIds.size : Prop)
  ensures ensures_1: (res.size ≤ nodeIds.size : Prop)
  do
    let mut inDegree : Std.HashMap String Int := ∅
    let mut adjacency : Std.HashMap String (Array String) := ∅
    let mut nodeIdSet : Std.HashSet String := ∅
    let _rangeStop0 : Nat := nodeIds.size
    for _id_idx in [:_rangeStop0]
      invariant invariant_1: (_id_idx ≤ nodeIds.size : Prop)
      invariant invariant_2: (∀ k : Int, 0 ≤ k → k < _id_idx → inDegree.contains nodeIds[k.toNat]! : Prop)
      invariant invariant_3: (∀ k : String, inDegree.contains k → inDegree.get! k = 0 : Prop)
      invariant invariant_4: (∀ k : String, adjacency.contains k → adjacency.get! k = #[] : Prop)
      invariant invariant_5: (nodeIdSet.size ≤ _id_idx : Prop)
      invariant invariant_6: (∀ k : Nat, k < _id_idx → nodeIdSet.contains nodeIds[k]! : Prop)
      done_with (let _id_idx : Nat := _rangeStop0; (_id_idx ≤ nodeIds.size : Prop) ∧ (∀ k : Int, 0 ≤ k → k < _id_idx → inDegree.contains nodeIds[k.toNat]! : Prop) ∧ (∀ k : String, inDegree.contains k → inDegree.get! k = 0 : Prop) ∧ (∀ k : String, adjacency.contains k → adjacency.get! k = #[] : Prop) ∧ (nodeIdSet.size ≤ _id_idx : Prop) ∧ (∀ k : Nat, k < _id_idx → nodeIdSet.contains nodeIds[k]! : Prop))
    do
      let _id_idx : Nat := _id_idx
      let id := nodeIds[_id_idx]!
      inDegree := inDegree.insert id 0
      adjacency := adjacency.insert id #[]
      nodeIdSet := nodeIdSet.insert id
    let _rangeStop1 : Nat := nodeIds.size
    for _id_idx2 in [:_rangeStop1]
      invariant invariant_7: (_id_idx2 ≤ nodeIds.size : Prop)
      invariant invariant_8: (∀ k : Int, 0 ≤ k → k < nodeIds.size → inDegree.contains nodeIds[k.toNat]! : Prop)
      invariant invariant_9: (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop)
      invariant invariant_10: (∀ k : String, inDegree.contains k → inDegree.get! k ≥ 0 : Prop)
      invariant invariant_11: (∀ k : Nat, k < nodeIds.size → nodeIdSet.contains nodeIds[k]! : Prop)
      done_with (let _id_idx2 : Nat := _rangeStop1; (_id_idx2 ≤ nodeIds.size : Prop) ∧ (∀ k : Int, 0 ≤ k → k < nodeIds.size → inDegree.contains nodeIds[k.toNat]! : Prop) ∧ (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop) ∧ (∀ k : String, inDegree.contains k → inDegree.get! k ≥ 0 : Prop) ∧ (∀ k : Nat, k < nodeIds.size → nodeIdSet.contains nodeIds[k]! : Prop))
    do
      let _id_idx2 : Nat := _id_idx2
      let id := nodeIds[_id_idx2]!
      if deps.contains id then
        let _nodeDeps_val := deps[id]!
        inDegree := inDegree.insert id _nodeDeps_val.size
        let _dep_seq := _nodeDeps_val.toArray
        let _rangeStop2 : Nat := _dep_seq.size
        for _dep_idx in [:_rangeStop2]
          invariant invariant_12: (_dep_idx ≤ _dep_seq.size : Prop)
          invariant invariant_13: (nodeIdSet.contains id : Prop)
          invariant invariant_14: (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop)
          done_with (let _dep_idx : Nat := _rangeStop2; (_dep_idx ≤ _dep_seq.size : Prop) ∧ (nodeIdSet.contains id : Prop) ∧ (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop))
        do
          let _dep_idx : Nat := _dep_idx
          let dep := _dep_seq[_dep_idx]!
          if adjacency.contains dep then
            let _adj_val := adjacency[dep]!
            adjacency := adjacency.insert dep (_adj_val ++ #[id])
    let mut enqueued : Std.HashSet String := ∅
    let mut queue : Array String := #[]
    let _rangeStop3 : Nat := nodeIds.size
    for _id_idx3 in [:_rangeStop3]
      invariant invariant_15: (_id_idx3 ≤ nodeIds.size : Prop)
      invariant invariant_16: (queue.size ≤ nodeIds.size : Prop)
      invariant invariant_17: (queue.size ≤ _id_idx3 : Prop)
      invariant invariant_18: (enqueued.size ≤ _id_idx3 : Prop)
      invariant invariant_19: (enqueued.size ≤ queue.size : Prop)
      invariant invariant_20: (queue.size ≤ enqueued.size : Prop)
      invariant invariant_21: (∀ k : String, enqueued.contains k → ∃ j : Int, 0 ≤ j ∧ j < _id_idx3 ∧ nodeIds[j.toNat]! = k : Prop)
      invariant invariant_22: (∀ k : String, enqueued.contains k → inDegree.contains k ∧ inDegree.get! k = 0 : Prop)
      invariant invariant_23: (∀ k : String, enqueued.contains k → nodeIdSet.contains k : Prop)
      done_with (let _id_idx3 : Nat := _rangeStop3; (_id_idx3 ≤ nodeIds.size : Prop) ∧ (queue.size ≤ nodeIds.size : Prop) ∧ (queue.size ≤ _id_idx3 : Prop) ∧ (enqueued.size ≤ _id_idx3 : Prop) ∧ (enqueued.size ≤ queue.size : Prop) ∧ (queue.size ≤ enqueued.size : Prop) ∧ (∀ k : String, enqueued.contains k → ∃ j : Int, 0 ≤ j ∧ j < _id_idx3 ∧ nodeIds[j.toNat]! = k : Prop) ∧ (∀ k : String, enqueued.contains k → inDegree.contains k ∧ inDegree.get! k = 0 : Prop) ∧ (∀ k : String, enqueued.contains k → nodeIdSet.contains k : Prop))
    do
      let _id_idx3 : Nat := _id_idx3
      let id := nodeIds[_id_idx3]!
      if if inDegree.contains id then let _value := inDegree[id]!
_value == 0 else false then
        assertGadget (¬(enqueued.contains id))
        queue := queue ++ #[id]
        enqueued := enqueued.insert id
    let mut sorted : Array String := #[]
    let mut qHead : Int := 0
    while qHead < queue.size
      invariant invariant_24: (qHead ≤ queue.size : Prop)
      invariant invariant_25: (sorted.size = qHead : Prop)
      invariant invariant_26: (sorted.size ≤ nodeIds.size : Prop)
      invariant invariant_27: (queue.size ≤ nodeIds.size : Prop)
      invariant invariant_28: (enqueued.size ≤ nodeIds.size : Prop)
      invariant invariant_29: (enqueued.size ≤ queue.size : Prop)
      invariant invariant_30: (queue.size ≤ enqueued.size : Prop)
      invariant invariant_31: (∀ k : String, enqueued.contains k → inDegree.contains k ∧ inDegree.get! k ≤ 0 : Prop)
      invariant invariant_32: (∀ k : String, enqueued.contains k → nodeIdSet.contains k : Prop)
      invariant invariant_33: (nodeIdSet.size ≤ nodeIds.size : Prop)
      invariant invariant_34: (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop)
      decreasing nodeIds.size - sorted.size
    do
      let id := queue[qHead.toNat]!
      sorted := sorted ++ #[id]
      qHead := qHead + 1
      if adjacency.contains id then
        let _neighbors_val := adjacency[id]!
        let _rangeStop4 : Nat := _neighbors_val.size
        for _neighbor_idx in [:_rangeStop4]
          invariant invariant_35: (_neighbor_idx ≤ _neighbors_val.size : Prop)
          invariant invariant_36: (qHead ≤ queue.size : Prop)
          invariant invariant_37: (sorted.size = qHead : Prop)
          invariant invariant_38: (enqueued.size ≤ nodeIds.size : Prop)
          invariant invariant_39: (enqueued.size ≤ queue.size : Prop)
          invariant invariant_40: (queue.size ≤ enqueued.size : Prop)
          invariant invariant_41: (∀ k : String, enqueued.contains k → inDegree.contains k ∧ inDegree.get! k ≤ 0 : Prop)
          invariant invariant_42: (∀ k : String, enqueued.contains k → nodeIdSet.contains k : Prop)
          invariant invariant_43: (nodeIdSet.size ≤ nodeIds.size : Prop)
          invariant invariant_44: (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop)
          invariant invariant_45: (∀ v : String, _neighbors_val.contains v → nodeIdSet.contains v : Prop)
          done_with (let _neighbor_idx : Nat := _rangeStop4; (_neighbor_idx ≤ _neighbors_val.size : Prop) ∧ (qHead ≤ queue.size : Prop) ∧ (sorted.size = qHead : Prop) ∧ (enqueued.size ≤ nodeIds.size : Prop) ∧ (enqueued.size ≤ queue.size : Prop) ∧ (queue.size ≤ enqueued.size : Prop) ∧ (∀ k : String, enqueued.contains k → inDegree.contains k ∧ inDegree.get! k ≤ 0 : Prop) ∧ (∀ k : String, enqueued.contains k → nodeIdSet.contains k : Prop) ∧ (nodeIdSet.size ≤ nodeIds.size : Prop) ∧ (∀ k : String, adjacency.contains k → ∀ v : String, (adjacency.get! k).contains v → nodeIdSet.contains v : Prop) ∧ (∀ v : String, _neighbors_val.contains v → nodeIdSet.contains v : Prop))
        do
          let _neighbor_idx : Nat := _neighbor_idx
          let neighbor := _neighbors_val[_neighbor_idx]!
          assertGadget ((nodeIdSet.contains neighbor) = true)
          if inDegree.contains neighbor then
            let _deg_val := inDegree[neighbor]!
            let newDeg := _deg_val - 1
            inDegree := inDegree.insert neighbor newDeg
            if newDeg = 0 then
              assertGadget (¬(enqueued.contains neighbor))
              queue := queue ++ #[neighbor]
              enqueued := enqueued.insert neighbor
    return sorted
