/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import Velvet.Syntax
import Velvet.Std

inductive State where
  | idle : State
  | connecting : State
  | connected : State
  | closing : State
deriving Repr, Inhabited, DecidableEq

inductive Event where
  | connect : Event
  | ack : Event
  | close : Event
  | timeout : Event
deriving Repr, Inhabited, DecidableEq

def transition_pure (state : State) (event : Event) : State :=
  if state = .idle ∧ event = .connect then
    .connecting
  else
    if state = .connecting ∧ event = .ack then
      .connected
    else
      if state = .connected ∧ event = .close then
        .closing
      else
        if state = .closing ∧ event = .ack then
          .idle
        else
          if event = .timeout then
            .idle
          else
            state
