// Generated by lsc from trim.ts

predicate IsJSWhitespace(c: char)
{
  c == '\U{0009}' || c == '\U{000A}' || c == '\U{000B}' || c == '\U{000C}' || c == '\U{000D}' ||
  c == '\U{0020}' || c == '\U{00A0}' || c == '\U{1680}' ||
  ('\U{2000}' <= c <= '\U{200A}') ||
  c == '\U{2028}' || c == '\U{2029}' || c == '\U{202F}' || c == '\U{205F}' ||
  c == '\U{3000}' || c == '\U{FEFF}'
}

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && !IsJSWhitespace(StringTrimLeft(s)[0]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[0]) then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  ensures StringTrimRight(s) == "" || (|StringTrimRight(s)| > 0 && !IsJSWhitespace(StringTrimRight(s)[|StringTrimRight(s)|-1]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[|s|-1]) then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

function StringFromCharCode(n: int): string
  requires 0 <= n < 0xD800 || 0xE000 <= n < 0x110000
  ensures |StringFromCharCode(n)| == 1
  ensures (StringFromCharCode(n)[0] as int) == n
{
  [n as char]
}

function trimmed(s: string): string
{
  StringTrim(s)
}

lemma trimmed_ensures(s: string)
  ensures (|trimmed(s)| <= |s|)
{
}

function trimAsciiWs(): string
{
  StringTrim("	x\n")
}

lemma trimAsciiWs_ensures()
  ensures (trimAsciiWs() == "x")
{
}

method runtimeSanityCheck() returns (res: bool)
{
  var strip := [9, 10, 11, 12, 13, 32, 160, 5760, 8192, 8193, 8194, 8195, 8196, 8197, 8198, 8199, 8200, 8201, 8202, 8232, 8233, 8239, 8287, 12288, 65279];
  var keep := [133, 8203, 8288, 65];
  var i_cp_idx := 0;
  while i_cp_idx < |strip|
    invariant (i_cp_idx <= |strip|)
  {
    var cp := strip[i_cp_idx];
    var ch := StringFromCharCode(cp);
    if (StringTrim(((ch + "x") + ch)) != "x") {
      return false;
    }
    i_cp_idx := i_cp_idx + 1;
  }
  var i_cp_idx2 := 0;
  while i_cp_idx2 < |keep|
    invariant (i_cp_idx2 <= |keep|)
  {
    var cp := keep[i_cp_idx2];
    var ch := StringFromCharCode(cp);
    if (StringTrim(((ch + "x") + ch)) == "x") {
      return false;
    }
    i_cp_idx2 := i_cp_idx2 + 1;
  }
  return true;
}
