// Generated by lsc from truthiness.ts

datatype Option<T> = None | Some(value: T)

function boolCond(b: bool): int
{
  if b then
    1
  else
    0
}

lemma boolCond_ensures(b: bool)
  ensures (b ==> (boolCond(b) == 1))
  ensures (!(b) ==> (boolCond(b) == 0))
{
}

function numCond(n: int): int
{
  if (n != 0) then
    1
  else
    0
}

lemma numCond_ensures(n: int)
  ensures ((n != 0) ==> (numCond(n) == 1))
  ensures ((n == 0) ==> (numCond(n) == 0))
{
}

function numNot(n: int): int
{
  if (n == 0) then
    1
  else
    0
}

lemma numNot_ensures(n: int)
  ensures ((n == 0) ==> (numNot(n) == 1))
  ensures ((n != 0) ==> (numNot(n) == 0))
{
}

function numTernary(n: int): int
{
  if (n != 0) then
    1
  else
    0
}

lemma numTernary_ensures(n: int)
  ensures ((n != 0) ==> (numTernary(n) == 1))
  ensures ((n == 0) ==> (numTernary(n) == 0))
{
}

function strCond(s: string): int
{
  if (|s| > 0) then
    1
  else
    0
}

lemma strCond_ensures(s: string)
  ensures ((|s| > 0) ==> (strCond(s) == 1))
  ensures ((|s| == 0) ==> (strCond(s) == 0))
{
}

function strNot(s: string): int
{
  if (s == "") then
    1
  else
    0
}

lemma strNot_ensures(s: string)
  ensures ((|s| == 0) ==> (strNot(s) == 1))
  ensures ((|s| > 0) ==> (strNot(s) == 0))
{
}

function arrCond(xs: seq<int>): int
{
  if true then
    1
  else
    0
}

lemma arrCond_ensures(xs: seq<int>)
  ensures (arrCond(xs) == 1)
{
}

function arrNot(xs: seq<int>): int
{
  if false then
    1
  else
    0
}

lemma arrNot_ensures(xs: seq<int>)
  ensures (arrNot(xs) == 0)
{
}

function andMixed(i: int, carry: int): int
{
  if ((i >= 0) && (carry != 0)) then
    1
  else
    0
}

lemma andMixed_ensures(i: int, carry: int)
  ensures ((i >= 0) ==> (carry != 0) ==> (andMixed(i, carry) == 1))
  ensures (((i < 0) || (carry == 0)) ==> (andMixed(i, carry) == 0))
{
}

function orMixed(s: string, n: int): int
{
  if ((|s| > 0) || (n != 0)) then
    1
  else
    0
}

lemma orMixed_ensures(s: string, n: int)
  ensures (((|s| > 0) || (n != 0)) ==> (orMixed(s, n) == 1))
  ensures ((|s| == 0) ==> (n == 0) ==> (orMixed(s, n) == 0))
{
}

function andOrNested(a: int, b: string, c: seq<int>): int
{
  if (((a != 0) || (|b| > 0)) && true) then
    1
  else
    0
}

lemma andOrNested_ensures(a: int, b: string, c: seq<int>)
  ensures (((a != 0) || (|b| > 0)) ==> (andOrNested(a, b, c) == 1))
  ensures ((a == 0) ==> (|b| == 0) ==> (andOrNested(a, b, c) == 0))
{
}

function optNumCond(o: Option<int>): int
{
  match o {
    case Some(i_o_val) =>
      if (i_o_val != 0) then
        1
      else
        0
    case None =>
      0
  }
}

lemma optNumCond_ensures(o: Option<int>)
  ensures ((match o { case Some(i_) => false case None => true }) ==> (optNumCond(o) == 0))
  ensures ((match o { case Some(i_value) => (i_value == 0) case None => false }) ==> (optNumCond(o) == 0))
  ensures (match o { case Some(i_o_val) => ((i_o_val != 0) ==> (optNumCond(o) == 1)) case None => true })
{
}

function optNumNot(o: Option<int>): int
{
  match o {
    case Some(i_o_val) =>
      if (i_o_val != 0) then
        0
      else
        1
    case None =>
      1
  }
}

lemma optNumNot_ensures(o: Option<int>)
  ensures ((match o { case Some(i_) => false case None => true }) ==> (optNumNot(o) == 1))
  ensures ((match o { case Some(i_value) => (i_value == 0) case None => false }) ==> (optNumNot(o) == 1))
  ensures (match o { case Some(i_o_val) => ((i_o_val != 0) ==> (optNumNot(o) == 0)) case None => true })
{
}

function optStrCond(o: Option<string>): int
{
  match o {
    case Some(i_o_val) =>
      if (|i_o_val| > 0) then
        1
      else
        0
    case None =>
      0
  }
}

lemma optStrCond_ensures(o: Option<string>)
  ensures ((match o { case Some(i_) => false case None => true }) ==> (optStrCond(o) == 0))
  ensures ((match o { case Some(i_value) => (i_value == "") case None => false }) ==> (optStrCond(o) == 0))
  ensures (match o { case Some(i_o_val) => ((i_o_val != "") ==> (optStrCond(o) == 1)) case None => true })
{
}

function optPresent(o: Option<int>): int
{
  match o {
    case Some(i_o_val) =>
      1
    case None =>
      0
  }
}

lemma optPresent_ensures(o: Option<int>)
  ensures (match o { case Some(i_o_val) => (optPresent(o) == 1) case None => true })
  ensures ((match o { case Some(i_) => false case None => true }) ==> (optPresent(o) == 0))
{
}

method carryScan(digits: seq<int>) returns (res: int)
  requires (|digits| > 0)
  ensures (res >= -1)
  ensures (res < |digits|)
{
  var i := (|digits| - 1);
  var carry := 1;
  while ((i >= 0) && (carry != 0))
    invariant (i >= -1)
    invariant (i < |digits|)
    decreases (i + 1)
  {
    if (digits[i] == 0) {
      carry := 0;
    }
    i := (i - 1);
  }
  return i;
}
