/-
  Generated by lsc from truthiness.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «truthiness.types»

set_option velvet.semantics.termination "total"

method boolCond (b : Bool) returns (res : Int)
  ensures ensures_1: (b → res = 1 : Prop)
  ensures ensures_2: (¬(b) → res = 0 : Prop)
  do
    return Pure.boolCond b

method numCond (n : Int) returns (res : Int)
  ensures ensures_1: (n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (n = 0 → res = 0 : Prop)
  do
    return Pure.numCond n

method numNot (n : Int) returns (res : Int)
  ensures ensures_1: (n = 0 → res = 1 : Prop)
  ensures ensures_2: (n ≠ 0 → res = 0 : Prop)
  do
    return Pure.numNot n

method numTernary (n : Int) returns (res : Int)
  ensures ensures_1: (n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (n = 0 → res = 0 : Prop)
  do
    return Pure.numTernary n

method strCond (s : String) returns (res : Int)
  ensures ensures_1: (s.length > 0 → res = 1 : Prop)
  ensures ensures_2: (s.length = 0 → res = 0 : Prop)
  do
    return Pure.strCond s

method strNot (s : String) returns (res : Int)
  ensures ensures_1: (s.length = 0 → res = 1 : Prop)
  ensures ensures_2: (s.length > 0 → res = 0 : Prop)
  do
    return Pure.strNot s

method arrCond (xs : Array Int) returns (res : Int)
  ensures ensures_1: (res = 1 : Prop)
  do
    return Pure.arrCond xs

method arrNot (xs : Array Int) returns (res : Int)
  ensures ensures_1: (res = 0 : Prop)
  do
    return Pure.arrNot xs

method andMixed (i : Int) (carry : Int) returns (res : Int)
  ensures ensures_1: (i ≥ 0 → carry ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (i < 0 ∨ carry = 0 → res = 0 : Prop)
  do
    return Pure.andMixed i carry

method orMixed (s : String) (n : Int) returns (res : Int)
  ensures ensures_1: (s.length > 0 ∨ n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (s.length = 0 → n = 0 → res = 0 : Prop)
  do
    return Pure.orMixed s n

method andOrNested (a : Int) (b : String) (c : Array Int) returns (res : Int)
  ensures ensures_1: (a ≠ 0 ∨ b.length > 0 → res = 1 : Prop)
  ensures ensures_2: (a = 0 → b.length = 0 → res = 0 : Prop)
  do
    return Pure.andOrNested a b c

method carryScan (digits : Array Int) returns (res : Int)
  requires require_1: (digits.size > 0 : Prop)
  ensures ensures_1: (res ≥ -1 : Prop)
  ensures ensures_2: (res < digits.size : Prop)
  do
    let mut i : Int := digits.size - 1
    let mut carry : Int := 1
    while i ≥ 0 && carry ≠ 0
      invariant invariant_1: (i ≥ -1 : Prop)
      invariant invariant_2: (i < digits.size : Prop)
      decreasing (i + 1).toNat
    do
      if digits[i.toNat]! = 0 then
        carry := 0
      i := i - 1
    return i

method optNumCond (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == 0 | .none => false) → res = 0 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ 0 → res = 1 | .none => true) : Prop)
  do
    return Pure.optNumCond o

method optNumNot (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 1 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == 0 | .none => false) → res = 1 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ 0 → res = 0 | .none => true) : Prop)
  do
    return Pure.optNumNot o

method optStrCond (o : Option String) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == "" | .none => false) → res = 0 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ "" → res = 1 | .none => true) : Prop)
  do
    return Pure.optStrCond o

method optPresent (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _o_val => res = 1 | .none => true) : Prop)
  ensures ensures_2: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  do
    return Pure.optPresent o
