/-
  Generated by lsc from truthiness.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «truthiness.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method boolCond (b : Bool) return (res : Int)
  ensures b → res = 1
  ensures ¬(b) → res = 0
  do
    return Pure.boolCond b

method numCond (n : Int) return (res : Int)
  ensures n ≠ 0 → res = 1
  ensures n = 0 → res = 0
  do
    return Pure.numCond n

method numNot (n : Int) return (res : Int)
  ensures n = 0 → res = 1
  ensures n ≠ 0 → res = 0
  do
    return Pure.numNot n

method numTernary (n : Int) return (res : Int)
  ensures n ≠ 0 → res = 1
  ensures n = 0 → res = 0
  do
    return Pure.numTernary n

method strCond (s : String) return (res : Int)
  ensures s.length > 0 → res = 1
  ensures s.length = 0 → res = 0
  do
    return Pure.strCond s

method strNot (s : String) return (res : Int)
  ensures s.length = 0 → res = 1
  ensures s.length > 0 → res = 0
  do
    return Pure.strNot s

method arrCond (xs : Array Int) return (res : Int)
  ensures res = 1
  do
    return Pure.arrCond xs

method arrNot (xs : Array Int) return (res : Int)
  ensures res = 0
  do
    return Pure.arrNot xs

method optNumCond (o : Option Int) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  ensures (match o with | .some _value => _value == 0 | .none => false) → res = 0
  ensures (match o with | .some _o_val => _o_val ≠ 0 → res = 1 | .none => true)
  do
    return Pure.optNumCond o

method optNumNot (o : Option Int) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 1
  ensures (match o with | .some _value => _value == 0 | .none => false) → res = 1
  ensures (match o with | .some _o_val => _o_val ≠ 0 → res = 0 | .none => true)
  do
    return Pure.optNumNot o

method optStrCond (o : Option String) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  ensures (match o with | .some _value => _value == "" | .none => false) → res = 0
  ensures (match o with | .some _o_val => _o_val ≠ "" → res = 1 | .none => true)
  do
    return Pure.optStrCond o

method optPresent (o : Option Int) return (res : Int)
  ensures (match o with | .some _o_val => res = 1 | .none => true)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  do
    return Pure.optPresent o
