/-
  Generated by lsc from tuples.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «tuples.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method swap (p : Int × String) return (res : String × Int)
  ensures res.1 = p.2
  ensures res.2 = p.1
  do
    return Pure.swap p

method middle (t : Int × String × Bool) return (res : String)
  ensures res = t.2.1
  do
    return Pure.middle t

method addFirstTwo (p : Int × Int × String) return (res : Int)
  ensures res = p.1 + p.2.1
  do
    return Pure.addFirstTwo p

method sumFirsts (pairs : Array (Int × String)) return (res : Array Int)
  do
    let mut out : Array Int := #[]
    for _n_idx in [:pairs.size]
      invariant _n_idx ≤ pairs.size
    do
      let _n_elem := pairs[_n_idx]!
      let n := _n_elem.1
      let label := _n_elem.2
      out := Array.push out n
    return out

method homogeneousStaysSeq (xs : Array Int) return (res : Int)
  require xs.size = 2
  ensures res = xs[0]! + xs[1]!
  do
    return Pure.homogeneousStaysSeq xs
