/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def swap (p : Int × String) : String × Int :=
  (p.2, p.1)

def middle (t : Int × String × Bool) : String :=
  t.2.1

def addFirstTwo (p : Int × Int × String) : Int :=
  let a := p.1
  let b := p.2.1
  a + b

def homogeneousStaysSeq (xs : Array Int) : Int :=
  xs[0]! + xs[1]!

end Pure
