/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Shape where
  | circle (r : Int) : Shape
  | rect (w : Int) (h : Int) : Shape
deriving Repr, Inhabited

namespace Pure

def area (s : Shape) : Int :=
  match s with
  | .circle _s_r =>
    3 * _s_r * _s_r
  | .rect _s_w _s_h =>
    _s_w * _s_h

def shapes  : Array Shape :=
  #[Shape.circle 2, Shape.rect 3 4]

def oneRect  : Array Shape :=
  let xs := #[Shape.rect 1 5]
  xs

def total  : Int :=
  let xs := shapes 
  area xs[0]! + area xs[1]!

end Pure
