/-
  Generated by lsc from unionInArray.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «unionInArray.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method area (s : Shape) return (res : Int)
  do
    return Pure.area s

method shapes  return (res : Array Shape)
  do
    return Pure.shapes 

method oneRect  return (res : Array Shape)
  do
    return Pure.oneRect 

method total  return (res : Int)
  do
    return Pure.total 
