// Generated by lsc. Program source: unionInArray.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.MunionInArray_56c7181d51de

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

type v_Shape  =
| C_v_Shape_v_circle : int -> v_Shape
| C_v_Shape_v_rect : int -> int -> v_Shape

let v_area  (v_s:v_Shape)
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (match v_s with
  | C_v_Shape_v_circle v__5f_s_5f_r -> (((3) * v__5f_s_5f_r) * v__5f_s_5f_r)
  | C_v_Shape_v_rect v__5f_s_5f_w v__5f_s_5f_h -> (v__5f_s_5f_w * v__5f_s_5f_h))

let v_shapes  ()
  : Ghost (S.seq v_Shape)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (S.build ((S.build (S.empty) ((C_v_Shape_v_circle ((2)))))) ((C_v_Shape_v_rect ((3)) ((4)))))

let v_oneRect  ()
  : Ghost (S.seq v_Shape)
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (let v_xs_4 = (S.build (S.empty) ((C_v_Shape_v_rect ((1)) ((5))))) in
  v_xs_4)

let v_total  ()
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        True
      )) =
  (let v_xs_5 = (v_shapes ()) in
  ((v_area ((S.index (v_xs_5) ((0))))) + (v_area ((S.index (v_xs_5) ((1)))))))
