// Generated by lsc. Program source: utf16.ts
// Add proofs in the .fst; regenerate with lsc regen --backend=fstar.
module LS.Mutf16_c4a3b270ce0e

module R = LS.Runtime
module S = FStar.Sequence
module FS = FStar.FiniteSet.Base
module FM = FStar.FiniteMap.Base
open FStar.FiniteSet.Ambient
open FStar.FiniteMap.Ambient
open FStar.Real

let v_emojiLength  ()
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (2))
      )) =
  (S.length ((S.build ((S.build (S.empty) (55357))) (56832))))

let v_emojiFirstCodeUnit  ()
  : Ghost int
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == (55357))
      )) =
  (S.index ((R.slice ((S.build ((S.build (S.empty) (55357))) (56832))) ((0)) ((1)))) ((0)))

let v_allTextIsNonempty  ()
  : Ghost bool
      (requires (
        True
      ))
      (ensures (fun ls_result ->
        (ls_result == true)
      )) =
  (R.every ((fun (v_value:R.string) ->
    ((S.length (v_value)) > (0)))) ((S.build ((S.build (S.empty) ((S.build ((S.build (S.empty) (55357))) (56832))))) ((S.build ((S.build ((S.build ((S.build (S.empty) (116))) (101))) (120))) (116))))))
