/-
  Generated by lsc from arraySum.ts
  Do not edit — re-run \`lsc check\` to regenerate.
-/
import Velvet.Syntax
import Velvet.Std
import LemmaScript.ArraySumSpec

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method arraySum (arr : Array Int) return (res : Int)
  ensures res = sumTo arr arr.size
  do
    let mut sum : Int := 0
    let mut i : Int := 0
    while i < arr.size
      invariant 0 ≤ i
      invariant i ≤ arr.size
      invariant sum = sumTo arr i.toNat
      decreasing arr.size - i.toNat
    do
      sum := sum + arr[i.toNat]!
      i := i + 1
    return sum

prove_correct arraySum by
  loom_solve

